import {expect,test,type Page} from "@playwright/test";

type Interaction="purchase-processing-yard"|"build-grain-mill"|"build-bakery"|"transfer-mill-input"|"collect-mill-output"|"transfer-bakery-input"|"collect-bakery-output";
async function ready(page:Page){await page.goto("");await page.getByRole("button",{name:/はじめる/}).click();await expect.poll(()=>page.evaluate(()=>window.__HGR_E2E__?.isGameReady())).toBe(true);}
async function at(page:Page,id:Interaction,ms:number){await page.evaluate(([interaction,duration])=>{const b=window.__HGR_E2E__!;b.positionAtProcessingInteraction(interaction);b.advanceProcessing(duration,40);},[id,ms] as const);}
async function diagnostics(page:Page){return page.evaluate(()=>window.__HGR_E2E__!.getProcessingDiagnostics());}
async function buildAll(page:Page,coins=4000){await page.evaluate(c=>window.__HGR_E2E__!.configureProcessing(c),coins);await at(page,"purchase-processing-yard",1240);await at(page,"build-grain-mill",1040);await at(page,"build-bakery",1040);}

test("constructs the registered processing chain once at exact costs",async({page})=>{await ready(page);await page.evaluate(()=>window.__HGR_E2E__!.configureProcessing(3000));await at(page,"purchase-processing-yard",1240);expect(await diagnostics(page)).toMatchObject({yardBuilt:true,walletCoins:2200,constructionTransactionCount:1});await at(page,"build-grain-mill",1040);expect(await diagnostics(page)).toMatchObject({millBuilt:true,walletCoins:1850,constructionTransactionCount:2});await at(page,"build-bakery",1040);expect(await diagnostics(page)).toMatchObject({bakeryBuilt:true,walletCoins:1000,constructionTransactionCount:3});await at(page,"build-bakery",1200);expect(await diagnostics(page)).toMatchObject({walletCoins:1000,constructionTransactionCount:3});});

test("moves ingredients through real mill and bakery cycles and collection",async({page})=>{await ready(page);await buildAll(page);await page.evaluate(()=>window.__HGR_E2E__!.configureProcessing(2000,{wheat:2,corn:2}));await at(page,"transfer-mill-input",700);expect(await diagnostics(page)).toMatchObject({millInput:{wheat:2,corn:2},lastManualInputResource:"corn"});await page.evaluate(()=>window.__HGR_E2E__!.advanceProcessing(4300,50));expect((await diagnostics(page)).millOutput.flour).toBeGreaterThan(0);await at(page,"collect-mill-output",200);expect(await diagnostics(page)).toMatchObject({lastManualOutputResource:"flour"});await page.evaluate(()=>window.__HGR_E2E__!.configureProcessing(2000,{flour:1,egg:1}));await at(page,"transfer-bakery-input",360);await page.evaluate(()=>window.__HGR_E2E__!.advanceProcessing(5600,50));expect((await diagnostics(page)).bakeryOutput.bread).toBe(1);await at(page,"collect-bakery-output",200);expect(await diagnostics(page)).toMatchObject({lastManualOutputResource:"bread",bakeryOutput:{bread:0}});});

test("restores active processing cycles and existing output exactly once",async({page})=>{await ready(page);await buildAll(page);await page.evaluate(()=>window.__HGR_E2E__!.configureProcessing(1000,{wheat:4,flour:2,egg:2}));await at(page,"transfer-mill-input",700);await at(page,"transfer-bakery-input",700);await page.evaluate(()=>window.__HGR_E2E__!.advanceProcessing(5600,50));const before=await diagnostics(page);expect(before.millOutput.flour).toBeGreaterThan(0);expect(before.bakeryOutput.bread).toBeGreaterThan(0);await page.evaluate(()=>window.__HGR_E2E__!.requestSave());await page.reload();await page.getByRole("button",{name:"つづきから"}).click();await expect.poll(()=>page.evaluate(()=>window.__HGR_E2E__?.isGameReady())).toBe(true);const after=await diagnostics(page);expect(after.millOutput).toEqual(before.millOutput);expect(after.bakeryOutput).toEqual(before.bakeryOutput);expect(after.millRemainingTime).toBe(before.millRemainingTime);expect(after.bakeryRemainingTime).toBe(before.bakeryRemainingTime);});
