import { expect,test,type Page } from "@playwright/test";
type E2E={getStateSummary:()=>{saveSequence:number;coins:number|null};requestSave:()=>Promise<void>;getSaveBackend:()=>string;getLastSaveError:()=>string|null;corruptPrimary:()=>Promise<void>};
const api=(page:Page)=>page.evaluate(()=>window.__HGR_E2E__ as E2E);
test("saves, reloads, continues, and rotates a backup",async({page})=>{
  await page.goto("");await page.getByRole("button",{name:"はじめる"}).click();await expect.poll(async()=>(await api(page)).getSaveBackend()).toBe("IndexedDB");
  await page.evaluate(()=>window.__HGR_E2E__!.requestSave());const first=await page.evaluate(()=>window.__HGR_E2E__!.getStateSummary());expect(first.saveSequence).toBe(1);expect(await page.evaluate(()=>window.__HGR_E2E__!.getLastSaveError())).toBeNull();
  await page.reload();await expect(page.getByRole("button",{name:"つづきから"})).toBeVisible();await page.getByRole("button",{name:"つづきから"}).click();expect((await page.evaluate(()=>window.__HGR_E2E__!.getStateSummary())).saveSequence).toBe(1);
  await page.evaluate(()=>window.__HGR_E2E__!.requestSave());expect((await page.evaluate(()=>window.__HGR_E2E__!.getStateSummary())).saveSequence).toBe(2);
  const stores=await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open("hurry-go-round",1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return new Promise<[boolean,boolean]>((resolve,reject)=>{const tx=db.transaction("saves"),store=tx.objectStore("saves"),a=store.get("primary"),b=store.get("backup");tx.oncomplete=()=>resolve([Boolean(a.result),Boolean(b.result)]);tx.onerror=()=>reject(tx.error);});});expect(stores).toEqual([true,true]);
});
test("recovers a corrupt primary from backup",async({page})=>{await page.goto("");await page.getByRole("button",{name:"はじめる"}).click();await page.evaluate(()=>window.__HGR_E2E__!.requestSave());await page.evaluate(()=>window.__HGR_E2E__!.requestSave());await page.evaluate(()=>window.__HGR_E2E__!.corruptPrimary());await page.reload();await expect(page.getByText(/バックアップから復元しました/)).toBeVisible();await expect(page.getByRole("button",{name:"つづきから"})).toBeVisible();});
test("falls back when IndexedDB is unavailable",async({context,page})=>{await context.addInitScript(()=>{Object.defineProperty(window,"indexedDB",{value:{open(){throw new Error("disabled by E2E");}}});});await page.goto("");await expect.poll(async()=>(await api(page)).getSaveBackend()).toBe("簡易保存");await page.getByRole("button",{name:"はじめる"}).click();await page.evaluate(()=>window.__HGR_E2E__!.requestSave());await page.reload();await expect(page.getByRole("button",{name:"つづきから"})).toBeVisible();});
