import { expect, test, type Page } from "@playwright/test";

async function start(page:Page):Promise<void>{await page.goto("");await page.getByRole("button",{name:/はじめる|つづきから/}).click();await expect.poll(()=>page.evaluate(()=>window.__HGR_E2E__?.isGameReady())).toBe(true);}

test("mixed cargo enters the barn once as an atomic batch and survives reload",async({page})=>{await start(page);await page.evaluate(()=>window.__HGR_E2E__!.configureInventory({cargo:{wheat:3,egg:2,flour:4,milk:1},barn:{wheat:5,egg:1,flour:0,milk:2}}));await page.evaluate(()=>window.__HGR_E2E__!.positionAtBarnDelivery());let state=await page.evaluate(()=>window.__HGR_E2E__!.getLogistics());expect(state.cargo).toMatchObject({wheat:0,egg:0,flour:0,milk:0});expect(state.barn).toMatchObject({wheat:8,egg:3,flour:4,milk:3});await page.evaluate(()=>window.__HGR_E2E__!.configureInventory({cargo:{corn:2}}));await page.waitForTimeout(250);state=await page.evaluate(()=>window.__HGR_E2E__!.getLogistics());expect(state.cargo.corn).toBe(2);await page.evaluate(()=>window.__HGR_E2E__!.requestSave());await page.reload();await page.getByRole("button",{name:"つづきから"}).click();await expect.poll(()=>page.evaluate(()=>window.__HGR_E2E__?.isGameReady())).toBe(true);state=await page.evaluate(()=>window.__HGR_E2E__!.getLogistics());expect(state.barn).toMatchObject({wheat:8,egg:3,flour:4,milk:3});expect(state.cargo.corn).toBe(2);});

test("collection stations batch partial deposit and capacity-limited withdraw independently",async({page})=>{await start(page);await page.evaluate(()=>window.__HGR_E2E__!.configureCollection({built:true,sources:{wheat:22},cargo:{wheat:7,corn:1},cargoCapacity:12}));await page.evaluate(()=>window.__HGR_E2E__!.positionAtCollectionInteraction("deposit-wheat-collection-box"));let d=await page.evaluate(()=>window.__HGR_E2E__!.getCollectionDiagnostics());expect(d.boxes.wheat.amount).toBe(24);expect(d.cargo.wheat).toBe(5);await page.evaluate(()=>window.__HGR_E2E__!.positionAtCollectionInteraction("open-collection-panel"));await page.evaluate(()=>window.__HGR_E2E__!.positionAtCollectionInteraction("withdraw-wheat-collection-box"));d=await page.evaluate(()=>window.__HGR_E2E__!.getCollectionDiagnostics());expect(d.cargo.wheat).toBe(11);expect(d.cargo.corn).toBe(1);expect(d.boxes.wheat.amount).toBe(18);await page.waitForTimeout(250);expect((await page.evaluate(()=>window.__HGR_E2E__!.getCollectionDiagnostics())).boxes.wheat.amount).toBe(18);});

test("hub construction stays still while locked or underfunded, then charges exactly once",async({page})=>{await start(page);await page.evaluate(()=>window.__HGR_E2E__!.configureCollection({coins:1000,processingYard:false,built:false}));await page.evaluate(()=>window.__HGR_E2E__!.positionAtCollectionInteraction("build-collection-hub"));await page.evaluate(()=>window.__HGR_E2E__!.advanceCollection(5000));let d=await page.evaluate(()=>window.__HGR_E2E__!.getCollectionDiagnostics());expect(d.hubBuilt).toBe(false);expect(d.walletCoins).toBe(1000);expect(d.construction.holdMs).toBe(0);await page.evaluate(()=>window.__HGR_E2E__!.configureCollection({coins:599,processingYard:true,built:false}));await page.evaluate(()=>window.__HGR_E2E__!.advanceCollection(5000));d=await page.evaluate(()=>window.__HGR_E2E__!.getCollectionDiagnostics());expect(d.hubBuilt).toBe(false);expect(d.walletCoins).toBe(599);expect(d.construction.holdMs).toBe(0);await page.evaluate(()=>window.__HGR_E2E__!.configureCollection({coins:700,processingYard:true,built:false}));await page.evaluate(()=>window.__HGR_E2E__!.advanceCollection(1200));d=await page.evaluate(()=>window.__HGR_E2E__!.getCollectionDiagnostics());expect(d.hubBuilt).toBe(true);expect(d.walletCoins).toBe(100);const changed=d.changedCommandCount;await page.evaluate(()=>window.__HGR_E2E__!.advanceCollection(5000));d=await page.evaluate(()=>window.__HGR_E2E__!.getCollectionDiagnostics());expect(d.walletCoins).toBe(100);expect(d.changedCommandCount).toBe(changed);});
