import Phaser from "phaser";
import type { Farmer } from "../entities/Farmer";
import { CollectionCourierEntity } from "../entities/CollectionCourierEntity";
import { INTERACTIONS, type InteractionId } from "../logic/facilities";
import { COLLECTION_BARN_POINT, COLLECTION_FACILITIES, type CollectionFacilityId } from "../config/collectionFacilities";
import { advanceCollectionConstruction,buildCollectionFacility,COLLECTION_SOURCES,depositPlayerResourceBatch,executeCollectionCommand,getCollectionFacilityAvailability,loadCourierOne,selectCollectionSource,selectCourierDestination,shouldCourierDepart,unloadCourierToBarnOne,unloadCourierToIntakeOne,withdrawPlayerResourceBatch,type CollectionCommand } from "../logic/collectionNetwork";
import { GAME_EVENTS,type GameState } from "../state/GameState";
import { CollectionFacilityView } from "./CollectionFacilityView";

const total=(amounts:GameState["barn"]):number=>Object.values(amounts).reduce((n,v)=>n+v,0);

export class CollectionNetworkSystem{
  private readonly view:CollectionFacilityView;private readonly courier:CollectionCourierEntity;private construction={facilityId:null as Exclude<CollectionFacilityId,"processing-intake">|null,holdMs:0,armed:true,lastAvailabilitySignature:""};private readonly transferArmed=new Map<InteractionId,boolean>();private runtimeMs=0;private panelInRange=false;private commandCount=0;private changedCommandCount=0;
  constructor(private readonly scene:Phaser.Scene,private readonly farmer:Farmer,private readonly getState:()=>GameState,private readonly setState:(state:GameState)=>void,private readonly actionKey:Phaser.Input.Keyboard.Key,private readonly spaceKey:Phaser.Input.Keyboard.Key){this.view=new CollectionFacilityView(scene);const hub=COLLECTION_FACILITIES.hub.courierPickupPoint;this.courier=new CollectionCourierEntity(scene,hub.x,hub.y);scene.game.events.on(GAME_EVENTS.collectionAction,this.handlePanelAction,this);}
  update(delta:number):void{this.view.update(this.getState());this.updateConstruction(delta);this.updatePlayerTransfer(delta);this.updatePanel();this.updateCourier(delta);}
  advanceForE2E(deltaMs:number,stepMs=50):void{let remaining=Math.max(0,Math.min(180000,Math.floor(deltaMs)));const step=Math.max(1,Math.min(250,Math.floor(stepMs)));while(remaining>0){const delta=Math.min(step,remaining);this.update(delta);remaining-=delta;}}
  getDiagnostics(){const state=this.getState(),network=state.collectionNetwork,facilities=Object.fromEntries((["hub","wheat","corn","egg","processing-intake"] as const).map(id=>{const a=getCollectionFacilityAvailability(id,state);return[id,{visible:a.visible,built:a.built,state:a.state,missingPrerequisites:[...a.missingPrerequisites]}];}));return{walletCoins:state.economy.walletCoins,hubBuilt:network.hubBuilt,facilities,boxes:{wheat:{built:network.boxes.wheat.built,amount:network.boxes.wheat.amounts.wheat},corn:{built:network.boxes.corn.built,amount:network.boxes.corn.amounts.corn},egg:{built:network.boxes.egg.built,amount:network.boxes.egg.amounts.egg}},cargo:{...state.cargo.amounts},cargoCapacity:state.cargo.capacity,construction:{...this.construction},barn:{...state.barn},processingIntake:{...network.processingIntake.amounts},routingMode:network.routingMode,courier:{...network.courier,carried:{...network.courier.carried}},lastServedSourceId:network.lastServedSourceId,commandCount:this.commandCount,changedCommandCount:this.changedCommandCount,courierPosition:{...this.courier.position}};}
  private inside(id:InteractionId):boolean{const i=INTERACTIONS.find(v=>v.id===id)!;return Phaser.Math.Distance.Between(this.farmer.x,this.farmer.y,i.center.x,i.center.y)<=i.radius;}
  private publish(priority=false):void{this.scene.game.events.emit(GAME_EVENTS.state,this.getState());this.scene.game.events.emit(GAME_EVENTS.dirty,priority?"priority":undefined);}
  private updateConstruction(delta:number):void{let facility:Exclude<CollectionFacilityId,"processing-intake">|null=null;for(const id of ["hub","wheat","corn","egg"] as const){const interaction=COLLECTION_FACILITIES[id].buildInteractionId;if(interaction&&this.inside(interaction)){facility=id;break;}}if(!facility){this.construction={facilityId:null,holdMs:0,armed:true,lastAvailabilitySignature:""};return;}const step=advanceCollectionConstruction(this.construction,facility,this.getState(),delta,(Phaser.Input.Keyboard.JustDown(this.actionKey)||Phaser.Input.Keyboard.JustDown(this.spaceKey)));this.construction=step.runtime;if(!step.availability.available){const message=step.availability.built?"建設済みです":step.availability.missingPrerequisites.length?`${step.availability.definition.publicName}\n前提条件を満たすと建設できます`:`${step.availability.definition.publicName}\nあと${step.availability.missingCoins}コイン必要です`;this.scene.game.events.emit(GAME_EVENTS.hint,message);return;}this.scene.game.events.emit(GAME_EVENTS.hint,`${step.availability.definition.publicName}　${step.availability.definition.cost}コイン　${Math.round(this.construction.holdMs/12)}%`);if(!step.execute)return;const result=buildCollectionFacility(this.getState(),facility);this.scene.game.events.emit(GAME_EVENTS.collectionResult,result);this.scene.game.events.emit(GAME_EVENTS.hint,result.message);if(result.changed){this.setState(result.state);this.publish(result.prioritySaveRequested);}}
  private updatePlayerTransfer(_delta:number):void{const candidates:Array<{id:InteractionId;source:(typeof COLLECTION_SOURCES)[number];direction:"deposit"|"withdraw";distance:number}>=[];for(const source of COLLECTION_SOURCES){const d=COLLECTION_FACILITIES[source];for(const [direction,id] of [["deposit",d.depositInteractionId],["withdraw",d.withdrawInteractionId]] as const){if(!id)continue;const interaction=INTERACTIONS.find(value=>value.id===id)!;const distance=Phaser.Math.Distance.Between(this.farmer.x,this.farmer.y,interaction.center.x,interaction.center.y);if(distance<=interaction.radius)candidates.push({id,source,direction,distance});else this.transferArmed.set(id,true);}}candidates.sort((a,b)=>a.distance-b.distance);const active=candidates[0];if(!active||this.transferArmed.get(active.id)===false)return;this.transferArmed.set(active.id,false);const state=this.getState(),box=state.collectionNetwork.boxes[active.source];if(!box.built)return;if(active.direction==="deposit"){const result=depositPlayerResourceBatch(state.cargo.amounts,active.source,box);if(!result.changed)return;const cargo={...state.cargo,amounts:result.cargo};this.setState({...state,cargo,collectionNetwork:{...state.collectionNetwork,boxes:{...state.collectionNetwork.boxes,[active.source]:result.box}}});this.finishPlayerTransfer(active.source,active.direction,result.moved,cargo);return;}const result=withdrawPlayerResourceBatch(state.cargo,active.source,box);if(!result.changed)return;this.setState({...state,cargo:result.cargo,collectionNetwork:{...state.collectionNetwork,boxes:{...state.collectionNetwork.boxes,[active.source]:result.box}}});this.finishPlayerTransfer(active.source,active.direction,result.moved,result.cargo);}
  private finishPlayerTransfer(source:(typeof COLLECTION_SOURCES)[number],direction:"deposit"|"withdraw",moved:number,cargo:GameState["cargo"]):void{this.farmer.setCargo(cargo.amounts,cargo.capacity);this.view.showTransfer(source,direction,moved);const name=source==="wheat"?"麦":source==="corn"?"とうもろこし":"たまご";this.scene.game.events.emit(GAME_EVENTS.hint,`${name}を${moved}個${direction==="deposit"?"預けました":"取り出しました"}`);this.publish(true);}
  private updateCourier(delta:number):void{let state=this.getState(),network=state.collectionNetwork,c=network.courier;this.courier.setVisible(c.hired);this.courier.setLoad(c.carried,c.capacity);if(!c.hired)return;network={...network,sourceAgesMs:{...network.sourceAgesMs,wheat:network.sourceAgesMs.wheat+(network.boxes.wheat.amounts.wheat>0?delta:0),corn:network.sourceAgesMs.corn+(network.boxes.corn.amounts.corn>0?delta:0),egg:network.sourceAgesMs.egg+(network.boxes.egg.amounts.egg>0?delta:0)}};this.runtimeMs-=delta;const target=c.stage==="moving-to-source"&&c.sourceId?COLLECTION_FACILITIES[c.sourceId].courierPickupPoint:c.stage==="moving-to-processing"?COLLECTION_FACILITIES["processing-intake"].courierPickupPoint:c.stage==="moving-to-barn"?COLLECTION_BARN_POINT:c.stage==="returning-to-hub"?COLLECTION_FACILITIES.hub.courierPickupPoint:null;if(target){const p=this.courier.position,speed=(90+c.level*18)*delta/1000,dist=Phaser.Math.Distance.Between(p.x,p.y,target.x,target.y),ratio=Math.min(1,speed/Math.max(1,dist));this.courier.setPosition(Phaser.Math.Linear(p.x,target.x,ratio),Phaser.Math.Linear(p.y,target.y,ratio));if(dist<12)c={...c,stage:c.stage==="moving-to-source"?"loading":c.stage==="moving-to-processing"?"unloading-processing":c.stage==="moving-to-barn"?"unloading-barn":"select-source"};}
    if(this.runtimeMs<=0){this.runtimeMs=Math.max(90,260-c.level*45);if(c.stage==="idle-at-hub"||c.stage==="select-source"){const source=selectCollectionSource(network.boxes,network.sourceAgesMs,{},c.sourceRoundRobinIndex);c=source?{...c,sourceId:source,stage:"moving-to-source"}:{...c,stage:"idle-at-hub"};}else if(c.stage==="loading"&&c.sourceId){const source=c.sourceId;const loaded=loadCourierOne(network.boxes[source],c,source);if(loaded.changed){network={...network,boxes:{...network.boxes,[source]:loaded.box}};c=loaded.courier;}const carried=total(c.carried),remaining=network.boxes[source].amounts[source];if(shouldCourierDepart(carried,c.capacity,remaining,c.waitMs)){c={...c,stage:"select-destination"};}else c={...c,stage:"waiting-for-batch",waitMs:0};}else if(c.stage==="waiting-for-batch"){c={...c,waitMs:c.waitMs+Math.max(90,260-c.level*45),stage:c.sourceId&&network.boxes[c.sourceId].amounts[c.sourceId]>0?"loading":"select-destination"};}else if(c.stage==="select-destination"){const resource=COLLECTION_SOURCES.find(r=>c.carried[r]>0);if(resource){const key=resource==="egg"?"bakery":"mill",machine=state.processing[key];const destination=selectCourierDestination(resource,network.routingMode,{intakeAmount:total(network.processingIntake.amounts),intakeCapacity:network.processingIntake.capacity,millBuilt:state.processing.land.millBuilt,bakeryBuilt:state.processing.land.bakeryBuilt,processingEnabled:machine.enabled,machineInputHasSpace:total(machine.input.amounts)<machine.input.capacity,needed:true});c={...c,destinationId:destination,stage:destination==="barn"?"moving-to-barn":"moving-to-processing"};}}else if(c.stage==="unloading-processing"){const unloaded=unloadCourierToIntakeOne(c,network.processingIntake);if(unloaded.changed){c=unloaded.courier;network={...network,processingIntake:unloaded.intake};}else c={...c,destinationId:"barn",stage:"moving-to-barn"};if(total(c.carried)===0)c=this.finishRoute(c,network);}else if(c.stage==="unloading-barn"){const unloaded=unloadCourierToBarnOne(c,state.barn);if(unloaded.changed){c=unloaded.courier;state={...state,barn:unloaded.destination};}if(total(c.carried)===0)c=this.finishRoute(c,network);}}
    this.setState({...state,collectionNetwork:{...network,courier:c}});}
  private finishRoute(c:GameState["collectionNetwork"]["courier"],network:GameState["collectionNetwork"]):typeof c{const source=c.sourceId;if(source){network.sourceAgesMs={...network.sourceAgesMs,[source]:0};network.lastServedSourceId=source;}return{...c,stage:"returning-to-hub",destinationId:null,sourceId:null,waitMs:0,sourceRoundRobinIndex:(c.sourceRoundRobinIndex+1)%3};}
  private updatePanel():void{const visible=this.getState().collectionNetwork.hubBuilt&&this.inside("open-collection-panel");if(visible!==this.panelInRange){this.panelInRange=visible;this.scene.game.events.emit(GAME_EVENTS.collectionRange,visible);}if(visible&&Phaser.Input.Keyboard.JustDown(this.actionKey))this.scene.game.events.emit(GAME_EVENTS.collectionOpen);}
  private handlePanelAction=(command:CollectionCommand):void=>{this.commandCount++;const result=executeCollectionCommand(this.getState(),command);if(result.changed){this.changedCommandCount++;this.setState(result.state);this.publish(result.prioritySaveRequested);}this.scene.game.events.emit(GAME_EVENTS.collectionResult,result);};
  destroy():void{this.scene.game.events.off(GAME_EVENTS.collectionAction,this.handlePanelAction,this);this.view.destroy();this.courier.destroy();}
}
