import Phaser from "phaser";
import type { Farmer } from "../entities/Farmer";
import { CollectionCourierEntity } from "../entities/CollectionCourierEntity";
import { INTERACTIONS, type InteractionId } from "../logic/facilities";
import { buildCollectionBox,buildCollectionHub,COLLECTION_SOURCES,depositPlayerResourceOne,hireCourier,loadCourierOne,selectCollectionSource,selectCourierDestination,shouldCourierDepart,trainCourier,unloadCourierToBarnOne,unloadCourierToIntakeOne,withdrawPlayerResourceOne,type CollectionRoutingMode,type CollectionSourceId } from "../logic/collectionNetwork";
import { GAME_EVENTS,type GameState } from "../state/GameState";
import { CollectionFacilityView } from "./CollectionFacilityView";

const POINTS={hub:{x:1855,y:1560},wheat:{x:775,y:790},corn:{x:2665,y:950},egg:{x:1245,y:1810},"processing-intake":{x:2055,y:1515},barn:{x:1450,y:560}} as const;
const total=(amounts:GameState["barn"]):number=>Object.values(amounts).reduce((n,v)=>n+v,0);

export class CollectionNetworkSystem{
  private readonly view:CollectionFacilityView;private readonly courier:CollectionCourierEntity;private holdId:InteractionId|null=null;private holdMs=0;private transferMs=0;private runtimeMs=0;private panelInRange=false;
  constructor(private readonly scene:Phaser.Scene,private readonly farmer:Farmer,private readonly getState:()=>GameState,private readonly setState:(state:GameState)=>void,private readonly actionKey:Phaser.Input.Keyboard.Key){this.view=new CollectionFacilityView(scene);this.courier=new CollectionCourierEntity(scene,POINTS.hub.x,POINTS.hub.y);scene.game.events.on(GAME_EVENTS.collectionAction,this.handlePanelAction,this);}
  update(delta:number):void{this.view.update(this.getState());this.updateConstruction(delta);this.updatePlayerTransfer(delta);this.updatePanel();this.updateCourier(delta);}
  private inside(id:InteractionId):boolean{const i=INTERACTIONS.find(v=>v.id===id)!;return Phaser.Math.Distance.Between(this.farmer.x,this.farmer.y,i.center.x,i.center.y)<=i.radius;}
  private publish(priority=false):void{this.scene.game.events.emit(GAME_EVENTS.state,this.getState());this.scene.game.events.emit(GAME_EVENTS.dirty,priority?"priority":undefined);}
  private updateConstruction(delta:number):void{const state=this.getState();let id:InteractionId|null=null;if(!state.collectionNetwork.hubBuilt)id="build-collection-hub";else for(const source of COLLECTION_SOURCES)if(!state.collectionNetwork.boxes[source].built&&this.sourceUnlocked(source,state)&&this.inside(`build-${source}-collection-box` as InteractionId)){id=`build-${source}-collection-box` as InteractionId;break;}if(!id||!this.inside(id)){this.holdId=null;this.holdMs=0;return;}if(this.holdId!==id){this.holdId=id;this.holdMs=0;}this.holdMs+=delta;const interaction=INTERACTIONS.find(i=>i.id===id)!;this.scene.game.events.emit(GAME_EVENTS.hint,`${interaction.title}　${Math.min(100,Math.round(this.holdMs/1200*100))}%`);if(this.holdMs<1200)return;this.holdMs=0;const current=this.getState();if(id==="build-collection-hub"){const result=buildCollectionHub(current.economy.walletCoins,current.processing.land.yardUnlocked,current.collectionNetwork.hubBuilt);if(!result.changed){this.scene.game.events.emit(GAME_EVENTS.hint,"加工場の解放と600コインが必要です");return;}this.setState({...current,economy:{...current.economy,walletCoins:result.wallet},collectionNetwork:{...current.collectionNetwork,hubBuilt:true}});}else{const source=id.includes("wheat")?"wheat":id.includes("corn")?"corn":"egg",result=buildCollectionBox(current.economy.walletCoins,true,current.collectionNetwork.boxes[source],source);if(!result.changed){this.scene.game.events.emit(GAME_EVENTS.hint,"コインが足りません");return;}this.setState({...current,economy:{...current.economy,walletCoins:result.wallet},collectionNetwork:{...current.collectionNetwork,boxes:{...current.collectionNetwork.boxes,[source]:result.box}}});}this.publish(true);}
  private sourceUnlocked(source:CollectionSourceId,state:GameState):boolean{return source==="wheat"||source==="corn"&&state.landExpansion.eastCornFieldUnlocked||source==="egg"&&state.landExpansion.southChickenCoopUnlocked;}
  private updatePlayerTransfer(delta:number):void{this.transferMs=Math.max(0,this.transferMs-delta);if(this.transferMs>0)return;for(const source of COLLECTION_SOURCES){const state=this.getState(),box=state.collectionNetwork.boxes[source];if(!box.built)continue;if(this.inside(`deposit-${source}-collection-box` as InteractionId)){const result=depositPlayerResourceOne(state.cargo.amounts,source,box);if(result.changed){this.setState({...state,cargo:{...state.cargo,amounts:result.cargo},collectionNetwork:{...state.collectionNetwork,boxes:{...state.collectionNetwork.boxes,[source]:result.box}}});this.transferMs=130;this.farmer.setCargo(result.cargo,state.cargo.capacity);this.publish();return;}}if(this.inside(`withdraw-${source}-collection-box` as InteractionId)){const result=withdrawPlayerResourceOne(state.cargo,source,box);if(result.changed){this.setState({...state,cargo:result.cargo,collectionNetwork:{...state.collectionNetwork,boxes:{...state.collectionNetwork.boxes,[source]:result.box}}});this.transferMs=150;this.farmer.setCargo(result.cargo.amounts,result.cargo.capacity);this.publish();return;}}}}
  private updateCourier(delta:number):void{let state=this.getState(),network=state.collectionNetwork,c=network.courier;this.courier.setVisible(c.hired);this.courier.setLoad(c.carried,c.capacity);if(!c.hired)return;for(const id of COLLECTION_SOURCES)network.sourceAgesMs[id]+=network.boxes[id].amounts[id]>0?delta:0;this.runtimeMs-=delta;const target=c.stage==="moving-to-source"&&c.sourceId?POINTS[c.sourceId]:c.stage==="moving-to-processing"?POINTS["processing-intake"]:c.stage==="moving-to-barn"?POINTS.barn:c.stage==="returning-to-hub"?POINTS.hub:null;if(target){const p=this.courier.position,speed=(90+c.level*18)*delta/1000,dist=Phaser.Math.Distance.Between(p.x,p.y,target.x,target.y),ratio=Math.min(1,speed/Math.max(1,dist));this.courier.setPosition(Phaser.Math.Linear(p.x,target.x,ratio),Phaser.Math.Linear(p.y,target.y,ratio));if(dist<12)c={...c,stage:c.stage==="moving-to-source"?"loading":c.stage==="moving-to-processing"?"unloading-processing":c.stage==="moving-to-barn"?"unloading-barn":"select-source"};}
    if(this.runtimeMs<=0){this.runtimeMs=Math.max(90,260-c.level*45);if(c.stage==="idle-at-hub"||c.stage==="select-source"){const source=selectCollectionSource(network.boxes,network.sourceAgesMs,{},c.sourceRoundRobinIndex);c=source?{...c,sourceId:source,stage:"moving-to-source"}:{...c,stage:"idle-at-hub"};}else if(c.stage==="loading"&&c.sourceId){const source=c.sourceId;const loaded=loadCourierOne(network.boxes[source],c,source);if(loaded.changed){network={...network,boxes:{...network.boxes,[source]:loaded.box}};c=loaded.courier;}const carried=total(c.carried),remaining=network.boxes[source].amounts[source];if(shouldCourierDepart(carried,c.capacity,remaining,c.waitMs)){c={...c,stage:"select-destination"};}else c={...c,stage:"waiting-for-batch",waitMs:0};}else if(c.stage==="waiting-for-batch"){c={...c,waitMs:c.waitMs+Math.max(90,260-c.level*45),stage:c.sourceId&&network.boxes[c.sourceId].amounts[c.sourceId]>0?"loading":"select-destination"};}else if(c.stage==="select-destination"){const resource=COLLECTION_SOURCES.find(r=>c.carried[r]>0);if(resource){const key=resource==="egg"?"bakery":"mill",machine=state.processing[key];const destination=selectCourierDestination(resource,network.routingMode,{intakeAmount:total(network.processingIntake.amounts),intakeCapacity:network.processingIntake.capacity,millBuilt:state.processing.land.millBuilt,bakeryBuilt:state.processing.land.bakeryBuilt,processingEnabled:machine.enabled,machineInputHasSpace:total(machine.input.amounts)<machine.input.capacity,needed:true});c={...c,destinationId:destination,stage:destination==="barn"?"moving-to-barn":"moving-to-processing"};}}else if(c.stage==="unloading-processing"){const unloaded=unloadCourierToIntakeOne(c,network.processingIntake);if(unloaded.changed){c=unloaded.courier;network={...network,processingIntake:unloaded.intake};}else c={...c,destinationId:"barn",stage:"moving-to-barn"};if(total(c.carried)===0)c=this.finishRoute(c,network);}else if(c.stage==="unloading-barn"){const unloaded=unloadCourierToBarnOne(c,state.barn);if(unloaded.changed){c=unloaded.courier;state={...state,barn:unloaded.destination};}if(total(c.carried)===0)c=this.finishRoute(c,network);}}
    this.setState({...state,collectionNetwork:{...network,courier:c}});}
  private finishRoute(c:GameState["collectionNetwork"]["courier"],network:GameState["collectionNetwork"]):typeof c{const source=c.sourceId;if(source){network.sourceAgesMs[source]=0;network.lastServedSourceId=source;}return{...c,stage:"returning-to-hub",destinationId:null,sourceId:null,waitMs:0,sourceRoundRobinIndex:(c.sourceRoundRobinIndex+1)%3};}
  private updatePanel():void{const visible=this.getState().collectionNetwork.hubBuilt&&this.inside("open-collection-panel");if(visible!==this.panelInRange){this.panelInRange=visible;this.scene.game.events.emit(GAME_EVENTS.collectionRange,visible);}if(visible&&Phaser.Input.Keyboard.JustDown(this.actionKey))this.scene.game.events.emit(GAME_EVENTS.collectionOpen);}
  private handlePanelAction=(action:"hire"|"train"|"mode"|"flush",value?:CollectionRoutingMode|CollectionSourceId):void=>{const state=this.getState();if(action==="hire"||action==="train"){const result=action==="hire"?hireCourier(state.economy.walletCoins,state.collectionNetwork.hubBuilt,state.collectionNetwork.courier):trainCourier(state.economy.walletCoins,state.collectionNetwork.courier);if(!result.changed){this.scene.game.events.emit(GAME_EVENTS.hint,"条件またはコインが足りません");return;}this.setState({...state,economy:{...state.economy,walletCoins:result.wallet},collectionNetwork:{...state.collectionNetwork,courier:result.courier}});}else if(action==="mode"&&value)this.setState({...state,collectionNetwork:{...state.collectionNetwork,routingMode:value as CollectionRoutingMode}});else if(action==="flush"&&value){const source=value as CollectionSourceId,box=state.collectionNetwork.boxes[source],amount=box.amounts[source];this.setState({...state,barn:{...state.barn,[source]:state.barn[source]+amount},collectionNetwork:{...state.collectionNetwork,boxes:{...state.collectionNetwork.boxes,[source]:{...box,amounts:{...box.amounts,[source]:0}}}}});}this.publish(true);};
  destroy():void{this.scene.game.events.off(GAME_EVENTS.collectionAction,this.handlePanelAction,this);this.view.destroy();this.courier.destroy();}
}
