import Phaser from "phaser";
import type { Farmer } from "../entities/Farmer";
import { CollectionCourierEntity } from "../entities/CollectionCourierEntity";
import { INTERACTIONS, type InteractionId } from "../logic/facilities";
import { COLLECTION_BARN_POINT, COLLECTION_FACILITIES, type CollectionFacilityId } from "../config/collectionFacilities";
import { buildCollectionFacility,COLLECTION_SOURCES,depositPlayerResourceOne,executeCollectionCommand,loadCourierOne,selectCollectionSource,selectCourierDestination,shouldCourierDepart,unloadCourierToBarnOne,unloadCourierToIntakeOne,withdrawPlayerResourceOne,type CollectionCommand } from "../logic/collectionNetwork";
import { GAME_EVENTS,type GameState } from "../state/GameState";
import { CollectionFacilityView } from "./CollectionFacilityView";

const total=(amounts:GameState["barn"]):number=>Object.values(amounts).reduce((n,v)=>n+v,0);

export class CollectionNetworkSystem{
  private readonly view:CollectionFacilityView;private readonly courier:CollectionCourierEntity;private holdId:InteractionId|null=null;private holdMs=0;private transferMs=0;private transferStation:InteractionId|null=null;private runtimeMs=0;private panelInRange=false;
  constructor(private readonly scene:Phaser.Scene,private readonly farmer:Farmer,private readonly getState:()=>GameState,private readonly setState:(state:GameState)=>void,private readonly actionKey:Phaser.Input.Keyboard.Key){this.view=new CollectionFacilityView(scene);const hub=COLLECTION_FACILITIES.hub.courierPickupPoint;this.courier=new CollectionCourierEntity(scene,hub.x,hub.y);scene.game.events.on(GAME_EVENTS.collectionAction,this.handlePanelAction,this);}
  update(delta:number):void{this.view.update(this.getState());this.updateConstruction(delta);this.updatePlayerTransfer(delta);this.updatePanel();this.updateCourier(delta);}
  private inside(id:InteractionId):boolean{const i=INTERACTIONS.find(v=>v.id===id)!;return Phaser.Math.Distance.Between(this.farmer.x,this.farmer.y,i.center.x,i.center.y)<=i.radius;}
  private publish(priority=false):void{this.scene.game.events.emit(GAME_EVENTS.state,this.getState());this.scene.game.events.emit(GAME_EVENTS.dirty,priority?"priority":undefined);}
  private updateConstruction(delta:number):void{let facility:Exclude<CollectionFacilityId,"processing-intake">|null=null;for(const id of ["hub","wheat","corn","egg"] as const){const interaction=COLLECTION_FACILITIES[id].buildInteractionId;if(interaction&&this.inside(interaction)){facility=id;break;}}if(!facility){this.holdId=null;this.holdMs=0;return;}const id=COLLECTION_FACILITIES[facility].buildInteractionId!;if(this.holdId!==id){this.holdId=id;this.holdMs=0;}this.holdMs+=delta;this.scene.game.events.emit(GAME_EVENTS.hint,`${COLLECTION_FACILITIES[facility].publicName}　${COLLECTION_FACILITIES[facility].cost}コイン　${Math.min(100,Math.round(this.holdMs/1200*100))}%`);if(this.holdMs<1200)return;this.holdMs=0;const result=buildCollectionFacility(this.getState(),facility);this.scene.game.events.emit(GAME_EVENTS.collectionResult,result);this.scene.game.events.emit(GAME_EVENTS.hint,result.message);if(result.changed){this.setState(result.state);this.publish(result.prioritySaveRequested);}}
  private updatePlayerTransfer(delta:number):void{let active:InteractionId|null=null;for(const source of COLLECTION_SOURCES){const d=COLLECTION_FACILITIES[source];if(d.depositInteractionId&&this.inside(d.depositInteractionId))active=d.depositInteractionId;if(d.withdrawInteractionId&&this.inside(d.withdrawInteractionId))active=d.withdrawInteractionId;}if(active!==this.transferStation){this.transferStation=active;this.transferMs=0;}this.transferMs=Math.max(0,this.transferMs-delta);if(this.transferMs>0||!active)return;for(const source of COLLECTION_SOURCES){const state=this.getState(),box=state.collectionNetwork.boxes[source],d=COLLECTION_FACILITIES[source];if(!box.built)continue;if(active===d.depositInteractionId){const result=depositPlayerResourceOne(state.cargo.amounts,source,box);if(result.changed){this.setState({...state,cargo:{...state.cargo,amounts:result.cargo},collectionNetwork:{...state.collectionNetwork,boxes:{...state.collectionNetwork.boxes,[source]:result.box}}});this.transferMs=130;this.farmer.setCargo(result.cargo,state.cargo.capacity);this.view.showTransfer(source,"deposit");this.scene.game.events.emit(GAME_EVENTS.hint,`${source==="wheat"?"麦":source==="corn"?"とうもろこし":"たまご"}を1個預けました`);this.publish();return;}}if(active===d.withdrawInteractionId){const result=withdrawPlayerResourceOne(state.cargo,source,box);if(result.changed){this.setState({...state,cargo:result.cargo,collectionNetwork:{...state.collectionNetwork,boxes:{...state.collectionNetwork.boxes,[source]:result.box}}});this.transferMs=150;this.farmer.setCargo(result.cargo.amounts,result.cargo.capacity);this.view.showTransfer(source,"withdraw");this.scene.game.events.emit(GAME_EVENTS.hint,"1個取り出しました");this.publish();return;}}}}
  private updateCourier(delta:number):void{let state=this.getState(),network=state.collectionNetwork,c=network.courier;this.courier.setVisible(c.hired);this.courier.setLoad(c.carried,c.capacity);if(!c.hired)return;network={...network,sourceAgesMs:{...network.sourceAgesMs,wheat:network.sourceAgesMs.wheat+(network.boxes.wheat.amounts.wheat>0?delta:0),corn:network.sourceAgesMs.corn+(network.boxes.corn.amounts.corn>0?delta:0),egg:network.sourceAgesMs.egg+(network.boxes.egg.amounts.egg>0?delta:0)}};this.runtimeMs-=delta;const target=c.stage==="moving-to-source"&&c.sourceId?COLLECTION_FACILITIES[c.sourceId].courierPickupPoint:c.stage==="moving-to-processing"?COLLECTION_FACILITIES["processing-intake"].courierPickupPoint:c.stage==="moving-to-barn"?COLLECTION_BARN_POINT:c.stage==="returning-to-hub"?COLLECTION_FACILITIES.hub.courierPickupPoint:null;if(target){const p=this.courier.position,speed=(90+c.level*18)*delta/1000,dist=Phaser.Math.Distance.Between(p.x,p.y,target.x,target.y),ratio=Math.min(1,speed/Math.max(1,dist));this.courier.setPosition(Phaser.Math.Linear(p.x,target.x,ratio),Phaser.Math.Linear(p.y,target.y,ratio));if(dist<12)c={...c,stage:c.stage==="moving-to-source"?"loading":c.stage==="moving-to-processing"?"unloading-processing":c.stage==="moving-to-barn"?"unloading-barn":"select-source"};}
    if(this.runtimeMs<=0){this.runtimeMs=Math.max(90,260-c.level*45);if(c.stage==="idle-at-hub"||c.stage==="select-source"){const source=selectCollectionSource(network.boxes,network.sourceAgesMs,{},c.sourceRoundRobinIndex);c=source?{...c,sourceId:source,stage:"moving-to-source"}:{...c,stage:"idle-at-hub"};}else if(c.stage==="loading"&&c.sourceId){const source=c.sourceId;const loaded=loadCourierOne(network.boxes[source],c,source);if(loaded.changed){network={...network,boxes:{...network.boxes,[source]:loaded.box}};c=loaded.courier;}const carried=total(c.carried),remaining=network.boxes[source].amounts[source];if(shouldCourierDepart(carried,c.capacity,remaining,c.waitMs)){c={...c,stage:"select-destination"};}else c={...c,stage:"waiting-for-batch",waitMs:0};}else if(c.stage==="waiting-for-batch"){c={...c,waitMs:c.waitMs+Math.max(90,260-c.level*45),stage:c.sourceId&&network.boxes[c.sourceId].amounts[c.sourceId]>0?"loading":"select-destination"};}else if(c.stage==="select-destination"){const resource=COLLECTION_SOURCES.find(r=>c.carried[r]>0);if(resource){const key=resource==="egg"?"bakery":"mill",machine=state.processing[key];const destination=selectCourierDestination(resource,network.routingMode,{intakeAmount:total(network.processingIntake.amounts),intakeCapacity:network.processingIntake.capacity,millBuilt:state.processing.land.millBuilt,bakeryBuilt:state.processing.land.bakeryBuilt,processingEnabled:machine.enabled,machineInputHasSpace:total(machine.input.amounts)<machine.input.capacity,needed:true});c={...c,destinationId:destination,stage:destination==="barn"?"moving-to-barn":"moving-to-processing"};}}else if(c.stage==="unloading-processing"){const unloaded=unloadCourierToIntakeOne(c,network.processingIntake);if(unloaded.changed){c=unloaded.courier;network={...network,processingIntake:unloaded.intake};}else c={...c,destinationId:"barn",stage:"moving-to-barn"};if(total(c.carried)===0)c=this.finishRoute(c,network);}else if(c.stage==="unloading-barn"){const unloaded=unloadCourierToBarnOne(c,state.barn);if(unloaded.changed){c=unloaded.courier;state={...state,barn:unloaded.destination};}if(total(c.carried)===0)c=this.finishRoute(c,network);}}
    this.setState({...state,collectionNetwork:{...network,courier:c}});}
  private finishRoute(c:GameState["collectionNetwork"]["courier"],network:GameState["collectionNetwork"]):typeof c{const source=c.sourceId;if(source){network.sourceAgesMs={...network.sourceAgesMs,[source]:0};network.lastServedSourceId=source;}return{...c,stage:"returning-to-hub",destinationId:null,sourceId:null,waitMs:0,sourceRoundRobinIndex:(c.sourceRoundRobinIndex+1)%3};}
  private updatePanel():void{const visible=this.getState().collectionNetwork.hubBuilt&&this.inside("open-collection-panel");if(visible!==this.panelInRange){this.panelInRange=visible;this.scene.game.events.emit(GAME_EVENTS.collectionRange,visible);}if(visible&&Phaser.Input.Keyboard.JustDown(this.actionKey))this.scene.game.events.emit(GAME_EVENTS.collectionOpen);}
  private handlePanelAction=(command:CollectionCommand):void=>{const result=executeCollectionCommand(this.getState(),command);if(result.changed){this.setState(result.state);this.publish(result.prioritySaveRequested);}this.scene.game.events.emit(GAME_EVENTS.collectionResult,result);};
  destroy():void{this.scene.game.events.off(GAME_EVENTS.collectionAction,this.handlePanelAction,this);this.view.destroy();this.courier.destroy();}
}
