import Phaser from "phaser";
import type { Farmer } from "../entities/Farmer";
import type { GameState } from "../state/GameState";
import { addCargoOne, getCarriedTotal, removeCargoOne } from "../logic/resources";
import { buildCowBarn, buyCow, createPastureNodes, expandPasture, harvestPastureNode, purchasePasture } from "../logic/dairy";
import { palette } from "../art/palette";

type Setter=(state:GameState)=>void;
export class DairySystem{
 private cooldown=0; private nodes:Phaser.GameObjects.Arc[]=[]; private cows:Phaser.GameObjects.Container[]=[];
 constructor(private scene:Phaser.Scene,private farmer:Farmer,private getState:()=>GameState,private setState:Setter){this.draw();}
 private draw():void{const g=this.scene.add.graphics().setDepth(200);g.fillStyle(0x8fbd68,.45).fillRoundedRect(3050,250,850,720,24).lineStyle(8,palette.outline,.8).strokeRoundedRect(3050,250,850,720,24);g.fillStyle(palette.path).fillRect(2870,540,260,90).fillRect(3090,930,100,740).fillRect(3090,1630,760,100);this.scene.add.text(3120,300,"牧草地予定地\n加工場解放後 1,000コイン",{fontFamily:"system-ui",fontSize:"20px",fontStyle:"bold",color:"#49382e",backgroundColor:"#fff4d8dd",padding:{x:12,y:8}}).setDepth(2000);for(let i=0;i<48;i++){const x=3180+(i%8)*82,y=460+Math.floor(i/8)*75;this.nodes.push(this.scene.add.circle(x,y,17,0x78a94f).setStrokeStyle(3,0x416d39).setDepth(y));}g.fillStyle(palette.barn,.75).fillRoundedRect(3100,1050,500,410,18).fillStyle(0xd8ddd4).fillRoundedRect(3450,1220,125,190,15).fillStyle(palette.cream,.75).fillRoundedRect(3300,1600,520,390,18);this.scene.add.text(3350,1080,"牛舎\n1,400コイン",{fontFamily:"system-ui",fontSize:"22px",fontStyle:"bold",color:"#fff4d8"}).setDepth(2000);this.scene.add.text(3560,1640,"乳製品工房\n1,000コイン",{fontFamily:"system-ui",fontSize:"21px",fontStyle:"bold",color:"#49382e"}).setOrigin(.5).setDepth(2000);}
 update(delta:number):void{this.cooldown=Math.max(0,this.cooldown-delta);const state=this.getState(),d=state.dairy;while(this.cows.length<d.cows.length){const i=this.cows.length,x=3210+i*135,y=1210+(i%2)*55,body=this.scene.add.ellipse(0,0,105,68,i%2?0x9b6845:0xf4eee1).setStrokeStyle(5,palette.outline),spot=this.scene.add.ellipse(-15,-5,30,25,0x49382e),head=this.scene.add.circle(48,-4,27,i%2?0xb77b50:0xf4eee1).setStrokeStyle(4,palette.outline);this.cows.push(this.scene.add.container(x,y,[body,spot,head]).setDepth(y));}
 this.cows.forEach((cow,i)=>cow.setVisible(d.barnBuilt&&i<d.cows.length).setPosition(3210+i*135+Math.sin(this.scene.time.now/800+i)*12,1210+(i%2)*55));this.nodes.forEach((n,i)=>n.setVisible(d.pastureUnlocked&&i<d.pastureNodes.length).setFillStyle(d.pastureNodes[i]?.state==="ready"?0x78a94f:0xb7c78b));if(this.cooldown>0)return;const near=(x:number,y:number,r=100)=>Phaser.Math.Distance.Between(this.farmer.x,this.farmer.y,x,y)<=r;let next=state;
 if(near(3110,550)&&!d.pastureUnlocked&&state.processing.land.yardUnlocked){const tx=purchasePasture(d,state.economy.walletCoins);if(tx.changed)next={...state,economy:{...state.economy,walletCoins:tx.wallet},dairy:{...d,pastureUnlocked:true}};}
 else if(d.pastureUnlocked){const index=d.pastureNodes.findIndex((node,i)=>node.state==="ready"&&near(3180+(i%8)*82,460+Math.floor(i/8)*75,55));if(index>=0){const h=harvestPastureNode(d.pastureNodes,d.pastureNodes[index]!.id,getCarriedTotal(state.cargo)<state.cargo.capacity);if(h.harvested)next={...state,cargo:addCargoOne(state.cargo,"hay").cargo,dairy:{...d,pastureNodes:h.nodes}};}
 else if(near(3120,950)&&d.pastureLevel<2){const tx=expandPasture(d.pastureLevel,state.economy.walletCoins);if(tx.changed)next={...state,economy:{...state.economy,walletCoins:tx.wallet},dairy:{...d,pastureLevel:tx.level,pastureNodes:createPastureNodes(tx.level)}};}
 else if(near(3350,1120)&&!d.barnBuilt){const tx=buildCowBarn(d,state.economy.walletCoins);if(tx.changed)next={...state,economy:{...state.economy,walletCoins:tx.wallet},dairy:{...d,barnBuilt:true,cows:[{id:"cow-1",producing:false,productionRemainingMs:0,readyMilk:0,activitySeed:1}]}};}
 else if(near(3550,1120)&&d.barnBuilt&&d.cows.length<3){const tx=buyCow(d.cows.length,state.economy.walletCoins);if(tx.changed)next={...state,economy:{...state.economy,walletCoins:tx.wallet},dairy:{...d,cows:[...d.cows,{id:`cow-${tx.count}`,producing:false,productionRemainingMs:0,readyMilk:0,activitySeed:tx.count}]}};}
 else if(near(3320,1360)&&state.cargo.amounts.hay>0&&d.hayRack<24)next={...state,cargo:removeCargoOne(state.cargo,"hay").cargo,dairy:{...d,hayRack:d.hayRack+1}};
 else if(near(3520,1360)&&d.milkTank>0&&getCarriedTotal(state.cargo)<state.cargo.capacity)next={...state,cargo:addCargoOne(state.cargo,"milk").cargo,dairy:{...d,milkTank:d.milkTank-1}};
 else if(near(3500,1640)&&d.barnBuilt&&!d.workshopBuilt&&state.economy.walletCoins>=1000)next={...state,economy:{...state.economy,walletCoins:state.economy.walletCoins-1000},dairy:{...d,workshopBuilt:true,workshopLevel:1}};
 else if(near(3310,1800)&&d.workshopBuilt&&state.cargo.amounts.milk>0&&d.workshopInput<18)next={...state,cargo:removeCargoOne(state.cargo,"milk").cargo,dairy:{...d,workshopInput:d.workshopInput+1}};
 else if(near(3820,1800)&&d.workshopBuilt&&getCarriedTotal(state.cargo)<state.cargo.capacity){const resource=d.workshopOutput.butter>0?"butter":d.workshopOutput.cheese>0?"cheese":null;if(resource)next={...state,cargo:addCargoOne(state.cargo,resource).cargo,dairy:{...d,workshopOutput:{...d.workshopOutput,[resource]:d.workshopOutput[resource]-1}}};}}
 if(next!==state){this.setState(next);this.scene.game.events.emit("persistent-state-dirty","priority");this.cooldown=180;}}
}
