import Phaser from "phaser";
import type { Farmer } from "../entities/Farmer";
import type { GameState } from "../state/GameState";
import { GAME_EVENTS } from "../state/GameState";
import { choosePoultryTask } from "../logic/poultryAutomation";
import { INTERACTIONS } from "../logic/facilities";
import { availabilityText, createWorkerProgress, getWorkerParametersForLevel, hireWorkerByRole, type WorkerRoleId } from "../logic/workforce";
import { palette } from "../art/palette";

type Runtime = { role:WorkerRoleId; body:Phaser.GameObjects.Container; phase:"source"|"destination"; timer:number; carrying:boolean };
const stateKey:Record<WorkerRoleId,keyof GameState["workers"]>={"wheat-harvester":"harvestWorker","wheat-transporter":"transportWorker","corn-harvester":"cornHarvestWorker","corn-transporter":"cornTransportWorker","poultry-caretaker":"poultryCaretaker"};
export class ExpandedAutomationSystem {
  private holds=new Map<WorkerRoleId,number>(); private armed=new Map<WorkerRoleId,boolean>(); private runtimes=new Map<WorkerRoleId,Runtime>();
  constructor(private scene:Phaser.Scene,private farmer:Farmer,private getState:()=>GameState,private setState:(s:GameState)=>void){
    for(const action of INTERACTIONS.filter(a=>a.kind==="hold-hire"&&a.workerRole?.startsWith("corn-")||a.workerRole==="poultry-caretaker")){const color=action.workerRole==="poultry-caretaker"?palette.coral:action.workerRole==="corn-transporter"?palette.sky:palette.wheat;scene.add.circle(action.center.x,action.center.y,action.visibleRadius,color,.22).setStrokeStyle(5,palette.outline).setDepth(action.center.y-1);scene.add.text(action.center.x,action.center.y,action.shortLabel,{fontFamily:"system-ui",fontSize:"18px",fontStyle:"bold",color:"#49382e",backgroundColor:"#fff4d8dd",padding:{x:7,y:4}}).setOrigin(.5).setDepth(action.center.y+2);}
    this.syncWorkers();
  }
  update(delta:number):void{this.updateHiring(delta);this.syncWorkers();for(const runtime of this.runtimes.values())this.updateRuntime(runtime,delta);}
  private prerequisites(s:GameState){const hired=new Set<WorkerRoleId>();for(const [role,key] of Object.entries(stateKey) as [WorkerRoleId,keyof GameState["workers"]][])if(s.workers[key].hired)hired.add(role);return{eastUnlocked:s.landExpansion.eastCornFieldUnlocked,coopUnlocked:s.landExpansion.southChickenCoopUnlocked,hiredRoles:hired};}
  private updateHiring(delta:number):void{for(const action of INTERACTIONS){const role=action.workerRole;if(!role||!role.startsWith("corn-")&&role!=="poultry-caretaker")continue;const near=Phaser.Math.Distance.Between(this.farmer.x,this.farmer.y,action.center.x,action.center.y)<=action.radius;if(!near){this.holds.set(role,0);this.armed.set(role,true);continue;}if(this.armed.get(role)===false)continue;const hold=(this.holds.get(role)??0)+delta;this.holds.set(role,hold);if(hold<(action.holdDurationMs??900))continue;this.holds.set(role,0);this.armed.set(role,false);const s=this.getState(),key=stateKey[role],current=s.workers[key];const result=hireWorkerByRole(role,s.economy.walletCoins,createWorkerProgress(current.hired,key==="poultryCaretaker"?s.workers.poultryCaretaker.resource:"corn",current.carried),this.prerequisites(s));if(!result.changed){this.scene.game.events.emit(GAME_EVENTS.hint,availabilityText(result.reason??"already-hired",Math.max(0,160-s.economy.walletCoins)));continue;}const worker={...current,hired:true,level:1,status:"作業場所へ移動中"};this.setState({...s,economy:{...s.economy,walletCoins:result.wallet},workers:{...s.workers,[key]:worker}});this.spawn(role);this.scene.game.events.emit(GAME_EVENTS.dirty,"priority");this.scene.game.events.emit(GAME_EVENTS.hint,`${role==="poultry-caretaker"?"飼育":"とうもろこし"}スタッフを雇いました`);}}
  private syncWorkers():void{const s=this.getState();for(const role of ["corn-harvester","corn-transporter","poultry-caretaker"] as const)if(s.workers[stateKey[role]].hired&&!this.runtimes.has(role))this.spawn(role);}
  private spawn(role:WorkerRoleId):void{if(this.runtimes.has(role))return;const start=role==="poultry-caretaker"?{x:1540,y:1530}:role==="corn-transporter"?{x:2440,y:900}:{x:2180,y:900};const color=role==="poultry-caretaker"?palette.sky:role==="corn-transporter"?palette.wheat:palette.foliage;const shadow=this.scene.add.ellipse(0,24,58,22,palette.shadow,.25),body=this.scene.add.graphics().lineStyle(4,palette.outline).fillStyle(color).fillRoundedRect(-20,-24,40,52,12).strokeRoundedRect(-20,-24,40,52,12).fillStyle(palette.cream).fillCircle(0,-31,18).strokeCircle(0,-31,18),tool=this.scene.add.graphics().lineStyle(5,palette.outline).strokeLineShape(new Phaser.Geom.Line(18,-5,34,20));const container=this.scene.add.container(start.x,start.y,[shadow,body,tool]).setDepth(start.y);this.runtimes.set(role,{role,body:container,phase:"source",timer:0,carrying:false});}
  private move(runtime:Runtime,target:{x:number;y:number},delta:number):boolean{const level=this.getState().workers[stateKey[runtime.role]].level;const speed=145*getWorkerParametersForLevel(runtime.role,level).moveSpeedMultiplier,dx=target.x-runtime.body.x,dy=target.y-runtime.body.y,d=Math.hypot(dx,dy);if(d<=speed*delta/1000){runtime.body.setPosition(target.x,target.y).setDepth(target.y);return true;}runtime.body.x+=dx/d*speed*delta/1000;runtime.body.y+=dy/d*speed*delta/1000;runtime.body.setDepth(runtime.body.y);return false;}
  private updateRuntime(r:Runtime,delta:number):void{if(r.role==="corn-harvester")this.updateCornHarvester(r,delta);else if(r.role==="corn-transporter")this.updateCornTransport(r,delta);else this.updateCaretaker(r,delta);}
  private updateCornHarvester(r:Runtime,delta:number):void{const s=this.getState(),target=r.phase==="source"?{x:2380,y:620}:{x:2480,y:900};if(!this.move(r,target,delta))return;r.timer+=delta;const interval=650*getWorkerParametersForLevel(r.role,s.workers.cornHarvestWorker.level).operationIntervalMultiplier;if(r.timer<interval)return;r.timer=0;if(r.phase==="source"){r.carrying=true;r.phase="destination";}else if(s.automation.cornFieldCrate<s.automation.cornFieldCrateCapacity){this.setState({...s,automation:{...s.automation,cornFieldCrate:s.automation.cornFieldCrate+1},workers:{...s.workers,cornHarvestWorker:{...s.workers.cornHarvestWorker,status:"集荷箱へ収穫物を入れています"}}});r.carrying=false;r.phase="source";}}
  private updateCornTransport(r:Runtime,delta:number):void{const s=this.getState(),target=r.phase==="source"?{x:2480,y:900}:{x:1450,y:610};if(!this.move(r,target,delta))return;r.timer+=delta;if(r.timer<180*getWorkerParametersForLevel(r.role,s.workers.cornTransportWorker.level).operationIntervalMultiplier)return;r.timer=0;if(r.phase==="source"&&s.automation.cornFieldCrate>0){this.setState({...s,automation:{...s.automation,cornFieldCrate:s.automation.cornFieldCrate-1},workers:{...s.workers,cornTransportWorker:{...s.workers.cornTransportWorker,carried:1,status:"倉庫へ運搬中"}}});r.carrying=true;r.phase="destination";}else if(r.phase==="destination"){this.setState({...s,barn:{...s.barn,corn:s.barn.corn+1},workers:{...s.workers,cornTransportWorker:{...s.workers.cornTransportWorker,carried:0,status:"集荷箱へ戻っています"}}});r.carrying=false;r.phase="source";}}
  private updateCaretaker(r:Runtime,delta:number):void{const s=this.getState(),task=choosePoultryTask(s.livestock.feed,10,3,s.barn.corn,s.livestock.eggs);const source=task==="collect-eggs"?{x:1390,y:1620}:{x:1450,y:610},destination=task==="collect-eggs"?{x:1450,y:610}:{x:980,y:1610};if(!this.move(r,r.phase==="source"?source:destination,delta))return;r.timer+=delta;if(r.timer<220*getWorkerParametersForLevel(r.role,s.workers.poultryCaretaker.level).operationIntervalMultiplier)return;r.timer=0;if(r.phase==="source"){if(task==="collect-eggs"&&s.livestock.eggs>0){this.setState({...s,livestock:{...s.livestock,eggs:s.livestock.eggs-1},workers:{...s.workers,poultryCaretaker:{...s.workers.poultryCaretaker,resource:"egg",carried:1,status:"卵を倉庫へ運搬中"}}});r.phase="destination";}else if((task==="emergency-feed"||task==="top-up-feed")&&s.barn.corn>0){this.setState({...s,barn:{...s.barn,corn:s.barn.corn-1},workers:{...s.workers,poultryCaretaker:{...s.workers.poultryCaretaker,resource:"corn",carried:1,status:"餌を運搬中"}}});r.phase="destination";}}else{const worker=s.workers.poultryCaretaker;if(worker.resource==="egg")this.setState({...s,barn:{...s.barn,egg:s.barn.egg+1},workers:{...s.workers,poultryCaretaker:{...worker,resource:null,carried:0,status:"作業確認中"}}});else if(worker.resource==="corn"&&s.livestock.feed<s.livestock.feedCapacity)this.setState({...s,livestock:{...s.livestock,feed:s.livestock.feed+1},workers:{...s.workers,poultryCaretaker:{...worker,resource:null,carried:0,status:"作業確認中"}}});r.phase="source";}}
}
