import Phaser from "phaser";
import type { Farmer } from "../entities/Farmer";
import { INTERACTIONS, type InteractionId } from "../logic/facilities";
import { advanceProductionCycle, buildProcessingMachine, collectManualOutputOne, purchaseProcessingYard, startProductionCycle, transferManualInputOne, type MachineId, type RecipeId } from "../logic/processing";
import type { GameState } from "../state/GameState";
import { GAME_EVENTS } from "../state/GameState";
import { ProcessingFacilityView } from "./ProcessingFacilityView";
import { ProcessingWorkerSystem } from "./ProcessingWorkerSystem";

export class ProcessingSystem{
  private readonly view:ProcessingFacilityView;private readonly workers:ProcessingWorkerSystem;private holdId:InteractionId|null=null;private holdMs=0;private transferCooldown=0;private panelInRange=false;
  constructor(private readonly scene:Phaser.Scene,private readonly farmer:Farmer,private readonly getState:()=>GameState,private readonly setState:(state:GameState)=>void,private readonly actionKey:Phaser.Input.Keyboard.Key){this.view=new ProcessingFacilityView(scene);this.workers=new ProcessingWorkerSystem(scene);scene.game.events.on(GAME_EVENTS.processingAction,this.handlePanelAction,this);}
  update(delta:number):void{let state=this.getState();let mill=advanceProductionCycle(state.processing.mill,delta).machine,bakery=advanceProductionCycle(state.processing.bakery,delta).machine;mill=startProductionCycle(mill,"grain-mill",["mill-flour","mill-cornmeal"]).machine;bakery=startProductionCycle(bakery,"bakery",["bakery-bread","bakery-cornbread"]).machine;state={...state,processing:{...state.processing,mill,bakery}};state=this.workers.update(state,delta);this.setState(state);this.view.update(state,delta);this.updateHold(delta);this.updateTransfers(delta);this.updatePanel();}
  private inside(id:InteractionId):boolean{const action=INTERACTIONS.find(i=>i.id===id)!;return Phaser.Math.Distance.Between(this.farmer.x,this.farmer.y,action.center.x,action.center.y)<=action.radius;}
  private publish(priority=false):void{this.scene.game.events.emit(GAME_EVENTS.state,this.getState());this.scene.game.events.emit(GAME_EVENTS.dirty,priority?"priority":undefined);}
  private updateHold(delta:number):void{const state=this.getState();const id:InteractionId|null=!state.processing.land.yardUnlocked?"purchase-processing-yard":!state.processing.land.millBuilt?"build-grain-mill":!state.processing.land.bakeryBuilt?"build-bakery":null;if(!id||!this.inside(id)){this.holdId=null;this.holdMs=0;return;}const action=INTERACTIONS.find(i=>i.id===id)!;if(this.holdId!==id){this.holdId=id;this.holdMs=0;}this.holdMs+=delta;this.scene.game.events.emit(GAME_EVENTS.hint,`${action.title}　${Math.min(100,Math.round(this.holdMs/(action.holdDurationMs??1000)*100))}%`);if(this.holdMs<(action.holdDurationMs??1000))return;const current=this.getState();const result=id==="purchase-processing-yard"?purchaseProcessingYard(current.processing.land,current.economy.walletCoins,current.landExpansion.eastCornFieldUnlocked,current.landExpansion.southChickenCoopUnlocked):buildProcessingMachine(current.processing.land,id==="build-grain-mill"?"grain-mill":"bakery",current.economy.walletCoins);this.holdMs=0;if(!result.ok){this.scene.game.events.emit(GAME_EVENTS.hint,result.reason==="coins"?"コインが足りません":"先に東農地と鶏小屋を解放してください");return;}const machineKey=id==="build-grain-mill"?"mill":id==="build-bakery"?"bakery":null;this.setState({...current,economy:{...current.economy,walletCoins:result.walletCoins},processing:{...current.processing,land:result.state,...(machineKey?{[machineKey]:{...current.processing[machineKey],built:true,level:1}}:{})}});this.publish(true);}
  private updateTransfers(delta:number):void{this.transferCooldown=Math.max(0,this.transferCooldown-delta);if(this.transferCooldown>0)return;const state=this.getState();const options:[InteractionId,MachineId,"input"|"output"][]=[["transfer-mill-input","grain-mill","input"],["collect-mill-output","grain-mill","output"],["transfer-bakery-input","bakery","input"],["collect-bakery-output","bakery","output"]];for(const [interaction,id,direction] of options){const key=id==="grain-mill"?"mill":"bakery";if(!state.processing[key].built||!this.inside(interaction))continue;const result=direction==="input"?transferManualInputOne(state.processing[key],id,state.cargo):collectManualOutputOne(state.processing[key],id,state.cargo);if(result.changed){this.setState({...state,cargo:result.cargo,processing:{...state.processing,[key]:result.machine}});this.transferCooldown=180;this.publish();return;}}
  }
  private updatePanel():void{const visible=this.getState().processing.land.yardUnlocked&&this.inside("open-processing-panel");if(visible!==this.panelInRange){this.panelInRange=visible;this.scene.game.events.emit(GAME_EVENTS.processingRange,visible);}if(visible&&(Phaser.Input.Keyboard.JustDown(this.actionKey))){this.scene.game.events.emit(GAME_EVENTS.state,this.getState());this.scene.game.events.emit(GAME_EVENTS.processingOpen);}}
  private handlePanelAction=(machine:MachineId,mode:"auto"|"stop"|RecipeId):void=>{const state=this.getState(),key=machine==="grain-mill"?"mill":"bakery",current=state.processing[key];this.setState({...state,processing:{...state.processing,[key]:{...current,enabled:mode!=="stop",selectedMode:mode==="stop"?current.selectedMode:mode}}});this.publish(true);};
  destroy():void{this.scene.game.events.off(GAME_EVENTS.processingAction,this.handlePanelAction,this);this.view.destroy();this.workers.destroy();}
}
