import Phaser from "phaser";
import type { GameState } from "../state/GameState";
import { getProcessingWorkerCapacity, moveProcessingOutputToBarn, type ProcessingWorkerRole } from "../logic/processingWorkers";
import type { ProcessingMachineState } from "../logic/processing";
import { diagnoseProcessingBuffer, returnProcessingExcessToBarn, transferBarnToProcessingTargets, type RecipePlan } from "../logic/processingPlan";

interface RuntimeWorker{role:ProcessingWorkerRole;sprite:Phaser.GameObjects.Container;phase:"source"|"machine";cooldown:number}
export class ProcessingWorkerSystem{
  private readonly workers:RuntimeWorker[];
  constructor(private readonly scene:Phaser.Scene){this.workers=[this.create("millOperator",2360,1480,0x5a9b78),this.create("baker",2360,1730,0xc97856)];}
  private create(role:ProcessingWorkerRole,x:number,y:number,color:number):RuntimeWorker{const body=this.scene.add.circle(0,0,17,color).setStrokeStyle(4,0x49382e),cargo=this.scene.add.rectangle(0,-27,26,12,0xf2d27a).setStrokeStyle(2,0x49382e);return{role,sprite:this.scene.add.container(x,y,[body,cargo]).setDepth(1800),phase:"source",cooldown:0};}
  update(state:GameState,delta:number,plans:Record<"grain-mill"|"bakery",RecipePlan>):GameState{let next=state;for(const runtime of this.workers){const worker=runtime.role==="millOperator"?next.processing.millOperator:next.processing.baker,machineKey=runtime.role==="millOperator"?"mill":"bakery" as const,machine=next.processing[machineKey];runtime.sprite.setVisible(worker.hired&&machine.built);if(!worker.hired||!machine.built)continue;runtime.cooldown-=delta;if(runtime.cooldown>0)continue;next=this.runBatch(next,runtime.role,machine,plans[runtime.role==="millOperator"?"grain-mill":"bakery"]);runtime.phase=runtime.phase==="source"?"machine":"source";const target=runtime.role==="millOperator"?(runtime.phase==="source"?{x:2360,y:1480}:{x:2500,y:1480}):(runtime.phase==="source"?{x:2360,y:1730}:{x:2500,y:1750});this.scene.tweens.add({targets:runtime.sprite,x:target.x,y:target.y,duration:700});runtime.cooldown=900;}return next;}
  private runBatch(state:GameState,role:ProcessingWorkerRole,machine:ProcessingMachineState,plan:RecipePlan):GameState{const key=role==="millOperator"?"millOperator":"baker",machineKey=role==="millOperator"?"mill":"bakery",machineId=role==="millOperator"?"grain-mill":"bakery",capacity=getProcessingWorkerCapacity(role,state.processing[key].level),output=moveProcessingOutputToBarn(machine,state.barn);if(output.changed)return this.apply(state,key,machineKey,output.machine,output.barn,output.totalMoved);const diagnosis=diagnoseProcessingBuffer(machineId,machine,plan),smart=Object.values(diagnosis.excess).some(n=>n>0)?returnProcessingExcessToBarn(machineId,machine,plan,state.barn,capacity):transferBarnToProcessingTargets(machineId,machine,plan,state.barn,capacity);return this.apply(state,key,machineKey,smart.machine,smart.barn??state.barn,smart.totalMoved);}
  private apply(state:GameState,key:ProcessingWorkerRole,machineKey:"mill"|"bakery",machine:ProcessingMachineState,barn:GameState["barn"],moved:number):GameState{return{...state,barn,processing:{...state.processing,[machineKey]:machine,[key]:{...state.processing[key],carriedAmount:0,carriedResource:null,publicStatus:moved?`${moved}個をまとめて運搬中`:"待機中"}}};}
  destroy():void{for(const worker of this.workers)worker.sprite.destroy();}
}
