import Phaser from "phaser";
import type { GameState } from "../state/GameState";
import { getProcessingWorkerCapacity, moveProcessingOutputToBarn, refillOneProcessingCycleFromBarn, type ProcessingWorkerRole } from "../logic/processingWorkers";
import type { ProcessingMachineState } from "../logic/processing";

interface RuntimeWorker{role:ProcessingWorkerRole;sprite:Phaser.GameObjects.Container;phase:"source"|"machine";cooldown:number}
export class ProcessingWorkerSystem{
  private readonly workers:RuntimeWorker[];
  constructor(private readonly scene:Phaser.Scene){this.workers=[this.create("millOperator",2360,1480,0x5a9b78),this.create("baker",2360,1730,0xc97856)];}
  private create(role:ProcessingWorkerRole,x:number,y:number,color:number):RuntimeWorker{const body=this.scene.add.circle(0,0,17,color).setStrokeStyle(4,0x49382e),cargo=this.scene.add.rectangle(0,-27,26,12,0xf2d27a).setStrokeStyle(2,0x49382e);return{role,sprite:this.scene.add.container(x,y,[body,cargo]).setDepth(1800),phase:"source",cooldown:0};}
  update(state:GameState,delta:number):GameState{let next=state;for(const runtime of this.workers){const worker=runtime.role==="millOperator"?next.processing.millOperator:next.processing.baker,machineKey=runtime.role==="millOperator"?"mill":"bakery" as const,machine=next.processing[machineKey];runtime.sprite.setVisible(worker.hired&&machine.built);if(!worker.hired||!machine.built)continue;runtime.cooldown-=delta;if(runtime.cooldown>0)continue;const result=this.runBatch(next,runtime.role,machine);next=result;runtime.phase=runtime.phase==="source"?"machine":"source";const target=runtime.role==="millOperator"?(runtime.phase==="source"?{x:2360,y:1480}:{x:2500,y:1480}):(runtime.phase==="source"?{x:2360,y:1730}:{x:2500,y:1750});this.scene.tweens.add({targets:runtime.sprite,x:target.x,y:target.y,duration:700});runtime.cooldown=900;}return next;}
  private runBatch(state:GameState,role:ProcessingWorkerRole,machine:ProcessingMachineState):GameState{const key=role==="millOperator"?"millOperator":"baker",machineKey=role==="millOperator"?"mill":"bakery",machineId=role==="millOperator"?"grain-mill":"bakery";getProcessingWorkerCapacity(role,state.processing[key].level);const output=moveProcessingOutputToBarn(machine,state.barn),result=output.changed?output:refillOneProcessingCycleFromBarn(machineId,machine,state.barn);const publicStatus=result.changed?`${result.totalMoved}個をまとめて運搬中`:machine.output.amounts.flour+machine.output.amounts.cornmeal+machine.output.amounts.bread+machine.output.amounts.cornbread>0?"完成品待ち":"原料待ち";return{...state,barn:result.barn,processing:{...state.processing,[machineKey]:result.machine,[key]:{...state.processing[key],carriedAmount:0,carriedResource:null,publicStatus}}};}
  destroy():void{for(const worker of this.workers)worker.sprite.destroy();}
}
