import Phaser from "phaser";
import type { GameState } from "../state/GameState";
import { getProcessingWorkerCapacity, type ProcessingWorkerRole } from "../logic/processingWorkers";
import type { ProcessingMachineState } from "../logic/processing";
import type { ResourceId } from "../config/resourceDefinitions";

interface RuntimeWorker{role:ProcessingWorkerRole;sprite:Phaser.GameObjects.Container;phase:"source"|"machine";cooldown:number}
export class ProcessingWorkerSystem{
  private readonly workers:RuntimeWorker[];
  constructor(private readonly scene:Phaser.Scene){this.workers=[this.create("millOperator",2360,1480,0x5a9b78),this.create("baker",2360,1730,0xc97856)];}
  private create(role:ProcessingWorkerRole,x:number,y:number,color:number):RuntimeWorker{const body=this.scene.add.circle(0,0,17,color).setStrokeStyle(4,0x49382e),cargo=this.scene.add.rectangle(0,-27,26,12,0xf2d27a).setStrokeStyle(2,0x49382e);return{role,sprite:this.scene.add.container(x,y,[body,cargo]).setDepth(1800),phase:"source",cooldown:0};}
  update(state:GameState,delta:number):GameState{let next=state;for(const runtime of this.workers){const worker=runtime.role==="millOperator"?next.processing.millOperator:next.processing.baker,machineKey=runtime.role==="millOperator"?"mill":"bakery" as const,machine=next.processing[machineKey];runtime.sprite.setVisible(worker.hired&&machine.built);if(!worker.hired||!machine.built)continue;runtime.cooldown-=delta;if(runtime.cooldown>0)continue;const result=this.runBatch(next,runtime.role,machine);next=result;runtime.phase=runtime.phase==="source"?"machine":"source";const target=runtime.role==="millOperator"?(runtime.phase==="source"?{x:2360,y:1480}:{x:2500,y:1480}):(runtime.phase==="source"?{x:2360,y:1730}:{x:2500,y:1750});this.scene.tweens.add({targets:runtime.sprite,x:target.x,y:target.y,duration:700});runtime.cooldown=900;}return next;}
  private runBatch(state:GameState,role:ProcessingWorkerRole,machine:ProcessingMachineState):GameState{const key=role==="millOperator"?"millOperator":"baker",machineKey=role==="millOperator"?"mill":"bakery",capacity=getProcessingWorkerCapacity(role,state.processing[key].level);let barn={...state.barn},input={...machine.input,amounts:{...machine.input.amounts}},output={...machine.output,amounts:{...machine.output.amounts}},moved=0;const outputs:ResourceId[]=role==="millOperator"?["flour","cornmeal"]:["bread","cornbread"];for(const r of outputs){const n=Math.min(output.amounts[r],capacity-moved);output.amounts[r]-=n;barn[r]+=n;moved+=n;}const inputs:ResourceId[]=role==="millOperator"?["wheat","corn"]:["flour","cornmeal","egg"];for(const r of inputs){const n=Math.min(barn[r],capacity-moved,Math.max(0,input.capacity-Object.values(input.amounts).reduce((a,b)=>a+b,0)));barn[r]-=n;input.amounts[r]+=n;moved+=n;}const publicStatus=moved?`${moved}個をまとめて運搬中`:"原料待ち";return{...state,barn,processing:{...state.processing,[machineKey]:{...machine,input,output},[key]:{...state.processing[key],carriedAmount:0,carriedResource:null,publicStatus}}};}
  destroy():void{for(const worker of this.workers)worker.sprite.destroy();}
}
