import Phaser from "phaser";
/** Accessible 48px discrete slider with pointer drag/tap and complete keyboard controls. */
export class DiscreteSlider extends Phaser.GameObjects.Container{
 private readonly track:Phaser.GameObjects.Rectangle;private readonly fill:Phaser.GameObjects.Rectangle;private readonly thumb:Phaser.GameObjects.Arc;private readonly label:Phaser.GameObjects.Text;private dragging=false;private focused=false;
 constructor(scene:Phaser.Scene,x:number,y:number,private readonly trackWidth:number,private value:number,private readonly minimum:number,private readonly maximum:number,private readonly change:(value:number)=>void){super(scene,x,y);this.track=scene.add.rectangle(0,0,trackWidth,16,0xb8aa8c).setStrokeStyle(2,0x49382e);this.fill=scene.add.rectangle(-trackWidth/2,0,0,12,0x3ca6a0).setOrigin(0,.5);this.thumb=scene.add.circle(0,0,22,0xfff4d8).setStrokeStyle(3,0x49382e);this.label=scene.add.text(0,-31,`${value}回分`,{fontFamily:"system-ui",fontSize:"14px",fontStyle:"bold",color:"#49382e"}).setOrigin(.5);this.add([this.track,this.fill,this.thumb,this.label]);this.setSize(trackWidth,48).setDepth(10001).setInteractive(new Phaser.Geom.Rectangle(-trackWidth/2,-24,trackWidth,48),Phaser.Geom.Rectangle.Contains).on("pointerdown",(pointer:Phaser.Input.Pointer)=>{this.dragging=true;this.focused=true;this.fromPointer(pointer);}).on("pointermove",(pointer:Phaser.Input.Pointer)=>{if(this.dragging)this.fromPointer(pointer);}).on("pointerup",()=>this.dragging=false).on("pointerout",()=>this.dragging=false);scene.input.keyboard?.on("keydown",this.onKey);scene.add.existing(this);this.paint();}
 private fromPointer(pointer:Phaser.Input.Pointer):void{const local=Phaser.Math.Clamp(pointer.x-(this.x-this.trackWidth/2),0,this.trackWidth);this.setValue(Math.round(this.minimum+local/this.trackWidth*(this.maximum-this.minimum)));}
 private onKey=(event:KeyboardEvent):void=>{if(!this.focused)return;const map:Record<string,number>={ArrowLeft:this.value-1,ArrowRight:this.value+1,PageDown:this.value-1,PageUp:this.value+1,Home:this.minimum,End:this.maximum};if(map[event.key]!==undefined){event.preventDefault();this.setValue(map[event.key]!);}};
 setValue(value:number):void{const next=Phaser.Math.Clamp(Math.round(value),this.minimum,this.maximum);if(next===this.value)return;this.value=next;this.paint();this.change(next);}
 setFocused(value:boolean):this{this.focused=value;this.paint();return this;}
 getSerializableRect(){return{x:this.x-this.trackWidth/2,y:this.y-24,width:this.trackWidth,height:48,label:`仕込み ${this.value}回分`,value:this.value,minimum:this.minimum,maximum:this.maximum,focused:this.focused};}
 private paint():void{const ratio=(this.value-this.minimum)/Math.max(1,this.maximum-this.minimum),position=-this.trackWidth/2+ratio*this.trackWidth;this.fill.width=ratio*this.trackWidth;this.thumb.x=position;this.thumb.setStrokeStyle(this.focused?5:3,this.focused?0x3ca6a0:0x49382e);this.label.setText(`${this.value}回分`);}
 destroy(fromScene?:boolean):void{this.scene.input.keyboard?.off("keydown",this.onKey);super.destroy(fromScene);}
}
