import { checksumPayload } from "./checksum"; import type { SaveRepository } from "./SaveRepository"; import { GAME_VERSION, SAVE_FORMAT, SAVE_SCHEMA_VERSION, type PersistedGameSnapshot, type SaveEnvelope } from "./saveSchema"; import { validateEnvelope } from "./saveValidation";
import { migrateSaveEnvelope } from "./migrations";
export class SaveService {
  private queue: Promise<unknown> = Promise.resolve();
  constructor(private readonly repository: SaveRepository) {}
  createEnvelope(payload: PersistedGameSnapshot, previous: SaveEnvelope | null, now = new Date()): Promise<SaveEnvelope> { return checksumPayload(payload).then(checksum => ({ format: SAVE_FORMAT, schemaVersion: SAVE_SCHEMA_VERSION, gameVersion: GAME_VERSION, saveId: previous?.saveId ?? crypto.randomUUID(), createdAt: previous?.createdAt ?? now.toISOString(), updatedAt: now.toISOString(), checksumAlgorithm: "SHA-256", checksum, payload })); }
  save(payload: PersistedGameSnapshot): Promise<SaveEnvelope> { const operation = this.queue.then(async () => { const old = await this.repository.loadPrimary(); if (old && (await validateEnvelope(old)).ok) await this.repository.saveBackup(old); const envelope = await this.createEnvelope(payload, old); await this.repository.savePrimary(envelope); const written = await this.repository.loadPrimary(); if (!written || !(await validateEnvelope(written)).ok) throw new Error("written save failed validation"); return envelope; }); this.queue = operation.catch(() => undefined); return operation; }
  async load(): Promise<{ envelope: SaveEnvelope | null; recovered: boolean; errors: string[] }> { const primary = await this.repository.loadPrimary(); if (primary) { const result = await migrateSaveEnvelope(primary); if (result.ok) return { envelope: result.value, recovered: false, errors: [] }; } const backup = await this.repository.loadBackup(); if (backup) { const result = await migrateSaveEnvelope(backup); if (result.ok) return { envelope: result.value, recovered: true, errors: [] }; return { envelope: null, recovered: false, errors: result.errors }; } return { envelope: null, recovered: false, errors: primary ? ["セーブデータが破損しています"] : [] }; }
}
