import {describe,expect,it} from "vitest";
import {emptyResourceAmounts} from "../config/resourceDefinitions";
import {buildCollectionBox,buildCollectionHub,createCollectionNetwork,depositPlayerResourceOne,getCollectionNetworkTotalByResource,getCourierLoadAmount,hireCourier,loadCourierOne,routeIntakeResourceOne,selectCollectionSource,selectCourierDestination,shouldCourierDepart,trainCourier,unloadCourierToBarnOne,withdrawPlayerResourceOne,unloadCourierToIntakeOne,type CollectionCourier} from "./collectionNetwork";
const amounts=(overrides:Partial<ReturnType<typeof emptyResourceAmounts>>={})=>({...emptyResourceAmounts(),...overrides});
describe("v0.9.1 collection network",()=>{
 it("builds the hub and boxes with exact prices and priority saves",()=>{expect(buildCollectionHub(600,true,false)).toMatchObject({changed:true,wallet:0,prioritySaveRequested:true});expect(buildCollectionHub(999,false,false)).toMatchObject({changed:false,wallet:999});const n=createCollectionNetwork();expect(buildCollectionBox(180,true,n.boxes.wheat,"wheat")).toMatchObject({changed:true,wallet:0,box:{built:true}});expect(buildCollectionBox(999,false,n.boxes.wheat,"wheat").changed).toBe(false)});
 it("deposits only the dedicated resource, one unit, without mutation",()=>{const n=createCollectionNetwork(),box={...n.boxes.wheat,built:true},cargo=amounts({wheat:2,corn:3});const r=depositPlayerResourceOne(cargo,"wheat",box);expect(r).toMatchObject({changed:true,cargo:{wheat:1,corn:3},box:{amounts:{wheat:1}}});expect(cargo.wheat).toBe(2);expect(depositPlayerResourceOne(amounts({corn:2}),"wheat",box).changed).toBe(false);expect(depositPlayerResourceOne(amounts({wheat:2}),"wheat",{...box,amounts:amounts({wheat:24})}).changed).toBe(false)});
 it("withdraws atomically without exceeding player capacity",()=>{const n=createCollectionNetwork(),box={...n.boxes.wheat,built:true,amounts:amounts({wheat:1})},cargo={amounts:amounts(),capacity:1};const r=withdrawPlayerResourceOne(cargo,"wheat",box);expect(r).toMatchObject({changed:true,cargo:{amounts:{wheat:1}},box:{amounts:{wheat:0}}});expect(withdrawPlayerResourceOne(r.cargo,"wheat",r.box).changed).toBe(false)});
 it("selects nonempty sources deterministically while age prevents starvation",()=>{const n=createCollectionNetwork();n.boxes.wheat={...n.boxes.wheat,built:true,amounts:amounts({wheat:12})};n.boxes.corn={...n.boxes.corn,built:true,amounts:amounts({corn:2})};expect(selectCollectionSource(n.boxes,n.sourceAgesMs)).toBe("wheat");expect(selectCollectionSource(n.boxes,{wheat:0,corn:100000,egg:0})).toBe("corn");expect(selectCollectionSource(n.boxes,n.sourceAgesMs,{},1)).toBe("wheat")});
 it("loads useful batches and applies every departure condition",()=>{expect(getCourierLoadAmount(20,0,10)).toBe(10);expect(getCourierLoadAmount(6,0,10)).toBe(6);expect(getCourierLoadAmount(20,8,10)).toBe(2);expect(shouldCourierDepart(1,10,9,0)).toBe(false);expect(shouldCourierDepart(10,10,20,0)).toBe(true);expect(shouldCourierDepart(3,10,0,0)).toBe(true);expect(shouldCourierDepart(3,10,20,900)).toBe(true);expect(shouldCourierDepart(1,10,20,0,true)).toBe(true);expect(shouldCourierDepart(0,10,0,900,true)).toBe(false)});
 it("routes by mode and always falls back safely",()=>{const ready={intakeAmount:0,intakeCapacity:36,millBuilt:true,bakeryBuilt:true,processingEnabled:true,machineInputHasSpace:true,needed:true};expect(selectCourierDestination("wheat","auto",ready)).toBe("processing-intake");expect(selectCourierDestination("egg","auto",{...ready,bakeryBuilt:false})).toBe("barn");expect(selectCourierDestination("corn","processing-first",{...ready,intakeAmount:36})).toBe("barn");expect(selectCourierDestination("bread","processing-first",ready)).toBe("barn");expect(selectCourierDestination("wheat","barn-first",ready)).toBe("barn")});
 it("preserves totals through loading and both unloading paths",()=>{const n=createCollectionNetwork();let box={...n.boxes.wheat,built:true,amounts:amounts({wheat:2})},courier:CollectionCourier={...n.courier,hired:true,level:1 as const,capacity:10,stage:"loading" as const};const before=box.amounts.wheat+courier.carried.wheat;const loaded=loadCourierOne(box,courier,"wheat");expect(loaded.changed).toBe(true);if(!loaded.changed)return;box=loaded.box;courier=loaded.courier;expect(box.amounts.wheat+courier.carried.wheat).toBe(before);const intake=unloadCourierToIntakeOne(courier,n.processingIntake);expect(intake.changed).toBe(true);if(!intake.changed)return;expect(intake.courier.carried.wheat+intake.intake.amounts.wheat).toBe(1);const barnUnload=unloadCourierToBarnOne({...courier,carried:amounts({wheat:1})},amounts());expect(barnUnload.changed).toBe(true)});
 it("sorts intake round-robin without overflowing machine buffers",()=>{let intake={amounts:amounts({wheat:1,corn:1,egg:1}),capacity:36,roundRobinIndex:0};let mill=amounts(),bakery=amounts();const a=routeIntakeResourceOne(intake,mill,bakery,{mill:2,bakery:2});expect(a).toMatchObject({changed:true,resource:"wheat"});intake=a.intake;mill=a.mill;bakery=a.bakery;const b=routeIntakeResourceOne(intake,mill,bakery,{mill:2,bakery:2});expect(b.resource).toBe("corn");const c=routeIntakeResourceOne(b.intake,b.mill,b.bakery,{mill:2,bakery:2});expect(c.resource).toBe("egg")});
 it("hires and trains the courier at exact costs/capacities",()=>{const n=createCollectionNetwork(),h=hireCourier(480,true,n.courier);expect(h).toMatchObject({changed:true,wallet:0,courier:{level:1,capacity:10}});const l2=trainCourier(260,h.courier);expect(l2).toMatchObject({changed:true,wallet:0,courier:{level:2,capacity:14}});const l3=trainCourier(620,l2.courier);expect(l3).toMatchObject({changed:true,wallet:0,courier:{level:3,capacity:18}});expect(trainCourier(999,l3.courier).changed).toBe(false)});
 it("includes every collection location in invariant totals",()=>{const n=createCollectionNetwork();n.boxes.wheat.amounts.wheat=2;n.courier.carried.wheat=3;n.processingIntake.amounts.wheat=4;expect(getCollectionNetworkTotalByResource(n,"wheat")).toBe(9)});
});
