import type { CarriedCargo } from "./resources";
import { RESOURCE_IDS, emptyResourceAmounts, type ResourceAmounts, type ResourceId } from "../config/resourceDefinitions";
import { COLLECTION_FACILITIES, type CollectionFacilityId, type CollectionPrerequisite } from "../config/collectionFacilities";
import type { GameState } from "../state/GameState";

export type CollectionSourceId = "wheat" | "corn" | "egg";
export type CollectionDestinationId = "processing-intake" | "barn";
export type CollectionRoutingMode = "auto" | "processing-first" | "barn-first";
export type CollectionCourierStage = "not-hired"|"idle-at-hub"|"select-source"|"moving-to-source"|"loading"|"waiting-for-batch"|"select-destination"|"moving-to-processing"|"moving-to-barn"|"unloading-processing"|"unloading-barn"|"returning-to-hub";
export interface CollectionBox { built:boolean; amounts:ResourceAmounts; capacity:number }
export interface ProcessingIntake { amounts:ResourceAmounts; capacity:number; roundRobinIndex:number }
export interface CollectionCourier { hired:boolean; level:0|1|2|3; carried:ResourceAmounts; capacity:number; stage:CollectionCourierStage; sourceId:CollectionSourceId|null; destinationId:CollectionDestinationId|null; waitMs:number; sourceRoundRobinIndex:number }
export interface CollectionNetwork { hubBuilt:boolean; boxes:Record<CollectionSourceId,CollectionBox>; processingIntake:ProcessingIntake; courier:CollectionCourier; routingMode:CollectionRoutingMode; lastServedSourceId:CollectionSourceId|null; sourceAgesMs:Record<CollectionSourceId,number> }
export const COLLECTION_SOURCES:readonly CollectionSourceId[]=["wheat","corn","egg"];
export const COLLECTION_BOX_COSTS:Readonly<Record<CollectionSourceId,number>>={wheat:COLLECTION_FACILITIES.wheat.cost,corn:COLLECTION_FACILITIES.corn.cost,egg:COLLECTION_FACILITIES.egg.cost};
export const COLLECTION_BOX_CAPACITIES:Readonly<Record<CollectionSourceId,number>>={wheat:COLLECTION_FACILITIES.wheat.capacity,corn:COLLECTION_FACILITIES.corn.capacity,egg:COLLECTION_FACILITIES.egg.capacity};
export const COURIER_CAPACITIES= [0,10,14,18] as const;
export const createCollectionNetwork=():CollectionNetwork=>({hubBuilt:false,boxes:{wheat:{built:false,amounts:emptyResourceAmounts(),capacity:COLLECTION_FACILITIES.wheat.capacity},corn:{built:false,amounts:emptyResourceAmounts(),capacity:COLLECTION_FACILITIES.corn.capacity},egg:{built:false,amounts:emptyResourceAmounts(),capacity:COLLECTION_FACILITIES.egg.capacity}},processingIntake:{amounts:emptyResourceAmounts(),capacity:COLLECTION_FACILITIES["processing-intake"].capacity,roundRobinIndex:0},courier:{hired:false,level:0,carried:emptyResourceAmounts(),capacity:0,stage:"not-hired",sourceId:null,destinationId:null,waitMs:0,sourceRoundRobinIndex:0},routingMode:"auto",lastServedSourceId:null,sourceAgesMs:{wheat:0,corn:0,egg:0}});
const total=(a:ResourceAmounts)=>RESOURCE_IDS.reduce((n,r)=>n+a[r],0);
export const getCollectionBoxCapacity=(source:CollectionSourceId)=>COLLECTION_BOX_CAPACITIES[source];
export const canDepositToCollectionBox=(source:CollectionSourceId,box:CollectionBox,resource:ResourceId)=>box.built&&resource===source&&total(box.amounts)<box.capacity;
export function depositPlayerResourceOne(cargo:ResourceAmounts,source:CollectionSourceId,box:CollectionBox){if(!box.built)return{changed:false,reason:"not-built" as const,cargo,box};if(cargo[source]<=0)return{changed:false,reason:"empty" as const,cargo,box};if(total(box.amounts)>=box.capacity)return{changed:false,reason:"full" as const,cargo,box};return{changed:true,cargo:{...cargo,[source]:cargo[source]-1},box:{...box,amounts:{...box.amounts,[source]:box.amounts[source]+1}}};}
export function withdrawPlayerResourceOne(cargo:CarriedCargo,source:CollectionSourceId,box:CollectionBox){if(!box.built)return{changed:false,reason:"not-built" as const,cargo,box};if(box.amounts[source]<=0)return{changed:false,reason:"empty" as const,cargo,box};if(total(cargo.amounts)>=cargo.capacity)return{changed:false,reason:"full" as const,cargo,box};return{changed:true,cargo:{...cargo,amounts:{...cargo.amounts,[source]:cargo.amounts[source]+1}},box:{...box,amounts:{...box.amounts,[source]:box.amounts[source]-1}}};}
export function buildCollectionHub(wallet:number,processingYardUnlocked:boolean,alreadyBuilt:boolean){if(alreadyBuilt)return{changed:false,reason:"already-built" as const,wallet,prioritySaveRequested:false};if(!processingYardUnlocked)return{changed:false,reason:"prerequisite" as const,wallet,prioritySaveRequested:false};if(wallet<600)return{changed:false,reason:"insufficient-coins" as const,wallet,prioritySaveRequested:false};return{changed:true,wallet:wallet-600,prioritySaveRequested:true};}
export function buildCollectionBox(wallet:number,hubBuilt:boolean,box:CollectionBox,source:CollectionSourceId){const cost=COLLECTION_BOX_COSTS[source];if(!hubBuilt)return{changed:false,reason:"prerequisite" as const,wallet,box,prioritySaveRequested:false};if(box.built)return{changed:false,reason:"already-built" as const,wallet,box,prioritySaveRequested:false};if(wallet<cost)return{changed:false,reason:"insufficient-coins" as const,wallet,box,prioritySaveRequested:false};return{changed:true,wallet:wallet-cost,box:{...box,built:true},prioritySaveRequested:true};}
export function selectCollectionSource(boxes:Record<CollectionSourceId,CollectionBox>,ages:Record<CollectionSourceId,number>,demand:Partial<Record<CollectionSourceId,number>>={},start=0):CollectionSourceId|null{let best:CollectionSourceId|null=null,bestScore=-Infinity;for(let offset=0;offset<COLLECTION_SOURCES.length;offset++){const id=COLLECTION_SOURCES[(start+offset)%3],box=boxes[id];if(!box.built||box.amounts[id]<=0)continue;const score=box.amounts[id]/box.capacity*100+(demand[id]??0)*20+ages[id]/1000;if(score>bestScore){best=id;bestScore=score}}return best;}
export const getCourierLoadAmount=(sourceAmount:number,carried:number,capacity:number)=>Math.max(0,Math.min(Math.floor(sourceAmount),Math.floor(capacity-carried)));
export const shouldCourierDepart=(carried:number,capacity:number,sourceAmount:number,waitMs:number,urgent=false)=>carried>0&&(carried>=capacity||sourceAmount<=0||waitMs>=900||urgent);
export function loadCourierOne(box:CollectionBox,courier:CollectionCourier,source:CollectionSourceId){if(!box.built||box.amounts[source]<=0)return{changed:false,box,courier,reason:"empty" as const};if(total(courier.carried)>=courier.capacity)return{changed:false,box,courier,reason:"full" as const};return{changed:true,box:{...box,amounts:{...box.amounts,[source]:box.amounts[source]-1}},courier:{...courier,carried:{...courier.carried,[source]:courier.carried[source]+1}}};}
export function selectCourierDestination(resource:ResourceId,mode:CollectionRoutingMode,input:{intakeAmount:number;intakeCapacity:number;millBuilt:boolean;bakeryBuilt:boolean;processingEnabled:boolean;machineInputHasSpace:boolean;needed:boolean}):CollectionDestinationId{if(mode==="barn-first"||["bread","cornbread"].includes(resource))return"barn";const machine=resource==="wheat"||resource==="corn"?input.millBuilt:input.bakeryBuilt;return machine&&input.processingEnabled&&input.machineInputHasSpace&&input.intakeAmount<input.intakeCapacity&&(mode==="processing-first"||input.needed)?"processing-intake":"barn";}
function unloadOne(courier:CollectionCourier,destination:ResourceAmounts,capacity:number,allowed:(r:ResourceId)=>boolean){if(total(destination)>=capacity)return{changed:false,courier,destination,reason:"full" as const};const resource=RESOURCE_IDS.find(r=>courier.carried[r]>0&&allowed(r));if(!resource)return{changed:false,courier,destination,reason:"empty" as const};return{changed:true,resource,courier:{...courier,carried:{...courier.carried,[resource]:courier.carried[resource]-1}},destination:{...destination,[resource]:destination[resource]+1}};}
export const unloadCourierToIntakeOne=(courier:CollectionCourier,intake:ProcessingIntake)=>{const r=unloadOne(courier,intake.amounts,intake.capacity,r=>!["bread","cornbread"].includes(r));return r.changed?{...r,intake:{...intake,amounts:r.destination}}:{...r,intake};};
export const unloadCourierToBarnOne=(courier:CollectionCourier,barn:ResourceAmounts)=>unloadOne(courier,barn,Number.MAX_SAFE_INTEGER,()=>true);
export function routeIntakeResourceOne(intake:ProcessingIntake,mill:ResourceAmounts,bakery:ResourceAmounts,capacities:{mill:number;bakery:number}){for(let n=0;n<RESOURCE_IDS.length;n++){const index=(intake.roundRobinIndex+n)%RESOURCE_IDS.length,r=RESOURCE_IDS[index];if(intake.amounts[r]<=0)continue;const target=(r==="wheat"||r==="corn")?mill:(r==="egg"||r==="flour"||r==="cornmeal")?bakery:null,capacity=target===mill?capacities.mill:capacities.bakery;if(!target||total(target)>=capacity)continue;return{changed:true,resource:r,intake:{...intake,amounts:{...intake.amounts,[r]:intake.amounts[r]-1},roundRobinIndex:(index+1)%RESOURCE_IDS.length},mill:target===mill?{...mill,[r]:mill[r]+1}:mill,bakery:target===bakery?{...bakery,[r]:bakery[r]+1}:bakery};}return{changed:false,intake,mill,bakery};}
export const getCollectionNetworkTotalByResource=(network:CollectionNetwork,resource:ResourceId)=>COLLECTION_SOURCES.reduce((n,id)=>n+network.boxes[id].amounts[resource],0)+network.courier.carried[resource]+network.processingIntake.amounts[resource];
export function hireCourier(wallet:number,hubBuilt:boolean,courier:CollectionCourier){if(!hubBuilt||courier.hired||wallet<480)return{changed:false,wallet,courier,prioritySaveRequested:false};return{changed:true,wallet:wallet-480,courier:{...courier,hired:true,level:1 as const,capacity:10,stage:"idle-at-hub" as const},prioritySaveRequested:true};}
export function trainCourier(wallet:number,courier:CollectionCourier){const costs=[0,260,620,0],cost=costs[courier.level];if(!courier.hired||courier.level===0||courier.level===3||wallet<cost)return{changed:false,wallet,courier,prioritySaveRequested:false};const level=(courier.level+1) as 2|3;return{changed:true,wallet:wallet-cost,courier:{...courier,level,capacity:COURIER_CAPACITIES[level]},prioritySaveRequested:true};}

export type CollectionCommand=
 | {type:"build";facilityId:Exclude<CollectionFacilityId,"processing-intake">}
 | {type:"hire-courier"}|{type:"train-courier"}
 | {type:"select-routing-mode";mode:CollectionRoutingMode}
 | {type:"flush-source";source:CollectionSourceId}
 | {type:"locate";facilityId:CollectionFacilityId};
export type CollectionCommandFailure="prerequisite-missing"|"insufficient-coins"|"already-built"|"already-hired"|"maximum-level"|"source-empty"|"facility-unavailable"|"mode-already-selected";
export interface CollectionCommandResult {changed:boolean;command:CollectionCommand;reason?:CollectionCommandFailure;message:string;prioritySaveRequested:boolean;state:GameState}
export interface CollectionFacilityAvailability {definition:typeof COLLECTION_FACILITIES[CollectionFacilityId];visible:boolean;built:boolean;available:boolean;missingPrerequisites:CollectionPrerequisite[];missingCoins:number;state:"built"|"planned"|"locked"}
const prerequisiteMet=(p:CollectionPrerequisite,s:GameState)=>p==="processing-yard"?s.processing.land.yardUnlocked:p==="collection-hub"?s.collectionNetwork.hubBuilt:p==="east-field"?s.landExpansion.eastCornFieldUnlocked:s.landExpansion.southChickenCoopUnlocked;
export function getCollectionFacilityAvailability(id:CollectionFacilityId,state:GameState):CollectionFacilityAvailability{const definition=COLLECTION_FACILITIES[id],built=id==="hub"?state.collectionNetwork.hubBuilt:id==="processing-intake"?state.collectionNetwork.hubBuilt&&state.processing.land.yardUnlocked:state.collectionNetwork.boxes[id].built;const missingPrerequisites=definition.prerequisites.filter(p=>!prerequisiteMet(p,state));const visible=id==="hub"||id==="processing-intake"?true:id==="wheat"?state.collectionNetwork.hubBuilt:id==="corn"?state.collectionNetwork.hubBuilt&&state.landExpansion.eastCornFieldUnlocked:state.collectionNetwork.hubBuilt&&state.landExpansion.southChickenCoopUnlocked;return{definition,visible,built,available:!built&&!missingPrerequisites.length&&state.economy.walletCoins>=definition.cost,missingPrerequisites,missingCoins:Math.max(0,definition.cost-state.economy.walletCoins),state:built?"built":missingPrerequisites.length?"locked":"planned"};}
const failureMessage=(a:CollectionFacilityAvailability)=>a.missingPrerequisites.length?(a.definition.id==="hub"?"加工場の解放後に建設できます":"前提施設を解放してください"):a.missingCoins?`あと${a.missingCoins}コイン必要です`:"すでに建設済みです";
export function buildCollectionFacility(state:GameState,id:Exclude<CollectionFacilityId,"processing-intake">):CollectionCommandResult{const command:CollectionCommand={type:"build",facilityId:id},a=getCollectionFacilityAvailability(id,state);if(a.built)return{changed:false,command,reason:"already-built",message:"すでに建設済みです",prioritySaveRequested:false,state};if(a.missingPrerequisites.length)return{changed:false,command,reason:"prerequisite-missing",message:failureMessage(a),prioritySaveRequested:false,state};if(a.missingCoins)return{changed:false,command,reason:"insufficient-coins",message:failureMessage(a),prioritySaveRequested:false,state};const network=id==="hub"?{...state.collectionNetwork,hubBuilt:true}:{...state.collectionNetwork,boxes:{...state.collectionNetwork.boxes,[id]:{...state.collectionNetwork.boxes[id],built:true}}};return{changed:true,command,message:`${a.definition.publicName}を建設しました\n${a.definition.cost}コインを使用しました`,prioritySaveRequested:true,state:{...state,economy:{...state.economy,walletCoins:state.economy.walletCoins-a.definition.cost},collectionNetwork:network}};}
export function flushCollectionSourceToBarn(state:GameState,source:CollectionSourceId):CollectionCommandResult{const command:CollectionCommand={type:"flush-source",source},box=state.collectionNetwork.boxes[source],amount=box.amounts[source];if(!box.built)return{changed:false,command,reason:"facility-unavailable",message:"集配ボックスが利用できません",prioritySaveRequested:false,state};if(amount<=0)return{changed:false,command,reason:"source-empty",message:"移送できる在庫がありません",prioritySaveRequested:false,state};return{changed:true,command,message:`${COLLECTION_FACILITIES[source].publicName}から倉庫へ${amount}個移しました`,prioritySaveRequested:true,state:{...state,barn:{...state.barn,[source]:state.barn[source]+amount},collectionNetwork:{...state.collectionNetwork,boxes:{...state.collectionNetwork.boxes,[source]:{...box,amounts:{...box.amounts,[source]:0}}}}}};}
export function selectCollectionRoutingMode(state:GameState,mode:CollectionRoutingMode):CollectionCommandResult{const command:CollectionCommand={type:"select-routing-mode",mode},name=mode==="auto"?"自動":mode==="processing-first"?"加工場優先":"倉庫優先";if(state.collectionNetwork.routingMode===mode)return{changed:false,command,reason:"mode-already-selected",message:`すでに「${name}」が選択されています`,prioritySaveRequested:false,state};return{changed:true,command,message:`配送モードを「${name}」に変更しました`,prioritySaveRequested:true,state:{...state,collectionNetwork:{...state.collectionNetwork,routingMode:mode}}};}
export function executeCollectionCommand(state:GameState,command:CollectionCommand):CollectionCommandResult{if(command.type==="build")return buildCollectionFacility(state,command.facilityId);if(command.type==="flush-source")return flushCollectionSourceToBarn(state,command.source);if(command.type==="select-routing-mode")return selectCollectionRoutingMode(state,command.mode);if(command.type==="locate")return{changed:false,command,message:`${COLLECTION_FACILITIES[command.facilityId].publicName}へ案内します`,prioritySaveRequested:false,state};if(command.type==="hire-courier"){if(state.collectionNetwork.courier.hired)return{changed:false,command,reason:"already-hired",message:"すでに雇用済みです",prioritySaveRequested:false,state};const r=hireCourier(state.economy.walletCoins,state.collectionNetwork.hubBuilt,state.collectionNetwork.courier);if(!r.changed)return{changed:false,command,reason:state.economy.walletCoins<480?"insufficient-coins":"facility-unavailable",message:state.economy.walletCoins<480?`あと${480-state.economy.walletCoins}コイン必要です`:"集配所が利用できません",prioritySaveRequested:false,state};return{changed:true,command,message:"集配スタッフを雇用しました\n480コインを使用しました",prioritySaveRequested:true,state:{...state,economy:{...state.economy,walletCoins:r.wallet},collectionNetwork:{...state.collectionNetwork,courier:r.courier}}};}const c=state.collectionNetwork.courier;if(c.level===3)return{changed:false,command,reason:"maximum-level",message:"すでに最大レベルです",prioritySaveRequested:false,state};const cost=[0,260,620,0][c.level],r=trainCourier(state.economy.walletCoins,c);if(!r.changed)return{changed:false,command,reason:"insufficient-coins",message:`あと${Math.max(0,cost-state.economy.walletCoins)}コイン必要です`,prioritySaveRequested:false,state};return{changed:true,command,message:`集配スタッフをLv${r.courier.level}へ研修しました\n${cost}コインを使用しました`,prioritySaveRequested:true,state:{...state,economy:{...state.economy,walletCoins:r.wallet},collectionNetwork:{...state.collectionNetwork,courier:r.courier}}};}
export function getCollectionGuideTarget(id:CollectionFacilityId){const d=COLLECTION_FACILITIES[id];return{id,label:d.publicName,point:{...d.guidePoint}};}
export function getCollectionPanelViewModel(state:GameState,lastResult?:Pick<CollectionCommandResult,"message"|"reason">){const n=state.collectionNetwork,c=n.courier;return{walletCoins:state.economy.walletCoins,facilities:(["hub","wheat","corn","egg","processing-intake"] as const).map(id=>({...getCollectionFacilityAvailability(id,state),amount:id==="processing-intake"?total(n.processingIntake.amounts):id==="hub"?0:n.boxes[id].amounts[id]})),routingMode:n.routingMode,courier:{...c,load:total(c.carried),trainingCost:c.level===1?260:c.level===2?620:null},lastResult};}
