import { RESOURCE_IDS, emptyResourceAmounts, type ResourceAmounts, type ResourceId } from "../config/resourceDefinitions";

export type CollectionSourceId = "wheat" | "corn" | "egg";
export type CollectionDestinationId = "processing-intake" | "barn";
export type CollectionRoutingMode = "auto" | "processing-first" | "barn-first";
export type CollectionCourierStage = "not-hired"|"idle-at-hub"|"select-source"|"moving-to-source"|"loading"|"waiting-for-batch"|"select-destination"|"moving-to-processing"|"moving-to-barn"|"unloading-processing"|"unloading-barn"|"returning-to-hub";
export interface CollectionBox { built:boolean; amounts:ResourceAmounts; capacity:number }
export interface ProcessingIntake { amounts:ResourceAmounts; capacity:number; roundRobinIndex:number }
export interface CollectionCourier { hired:boolean; level:0|1|2|3; carried:ResourceAmounts; capacity:number; stage:CollectionCourierStage; sourceId:CollectionSourceId|null; destinationId:CollectionDestinationId|null; waitMs:number; sourceRoundRobinIndex:number }
export interface CollectionNetwork { hubBuilt:boolean; boxes:Record<CollectionSourceId,CollectionBox>; processingIntake:ProcessingIntake; courier:CollectionCourier; routingMode:CollectionRoutingMode; lastServedSourceId:CollectionSourceId|null; sourceAgesMs:Record<CollectionSourceId,number> }
export const COLLECTION_SOURCES:readonly CollectionSourceId[]=["wheat","corn","egg"];
export const COLLECTION_BOX_COSTS:Readonly<Record<CollectionSourceId,number>>={wheat:180,corn:260,egg:280};
export const COLLECTION_BOX_CAPACITIES:Readonly<Record<CollectionSourceId,number>>={wheat:24,corn:28,egg:18};
export const COURIER_CAPACITIES= [0,10,14,18] as const;
export const createCollectionNetwork=():CollectionNetwork=>({hubBuilt:false,boxes:{wheat:{built:false,amounts:emptyResourceAmounts(),capacity:24},corn:{built:false,amounts:emptyResourceAmounts(),capacity:28},egg:{built:false,amounts:emptyResourceAmounts(),capacity:18}},processingIntake:{amounts:emptyResourceAmounts(),capacity:36,roundRobinIndex:0},courier:{hired:false,level:0,carried:emptyResourceAmounts(),capacity:0,stage:"not-hired",sourceId:null,destinationId:null,waitMs:0,sourceRoundRobinIndex:0},routingMode:"auto",lastServedSourceId:null,sourceAgesMs:{wheat:0,corn:0,egg:0}});
const total=(a:ResourceAmounts)=>RESOURCE_IDS.reduce((n,r)=>n+a[r],0);
export const getCollectionBoxCapacity=(source:CollectionSourceId)=>COLLECTION_BOX_CAPACITIES[source];
export const canDepositToCollectionBox=(source:CollectionSourceId,box:CollectionBox,resource:ResourceId)=>box.built&&resource===source&&total(box.amounts)<box.capacity;
export function depositPlayerResourceOne(cargo:ResourceAmounts,source:CollectionSourceId,box:CollectionBox){if(!box.built)return{changed:false,reason:"not-built" as const,cargo,box};if(cargo[source]<=0)return{changed:false,reason:"empty" as const,cargo,box};if(total(box.amounts)>=box.capacity)return{changed:false,reason:"full" as const,cargo,box};return{changed:true,cargo:{...cargo,[source]:cargo[source]-1},box:{...box,amounts:{...box.amounts,[source]:box.amounts[source]+1}}};}
export function buildCollectionHub(wallet:number,processingYardUnlocked:boolean,alreadyBuilt:boolean){if(alreadyBuilt)return{changed:false,reason:"already-built" as const,wallet,prioritySaveRequested:false};if(!processingYardUnlocked)return{changed:false,reason:"prerequisite" as const,wallet,prioritySaveRequested:false};if(wallet<600)return{changed:false,reason:"insufficient-coins" as const,wallet,prioritySaveRequested:false};return{changed:true,wallet:wallet-600,prioritySaveRequested:true};}
export function buildCollectionBox(wallet:number,hubBuilt:boolean,box:CollectionBox,source:CollectionSourceId){const cost=COLLECTION_BOX_COSTS[source];if(!hubBuilt)return{changed:false,reason:"prerequisite" as const,wallet,box,prioritySaveRequested:false};if(box.built)return{changed:false,reason:"already-built" as const,wallet,box,prioritySaveRequested:false};if(wallet<cost)return{changed:false,reason:"insufficient-coins" as const,wallet,box,prioritySaveRequested:false};return{changed:true,wallet:wallet-cost,box:{...box,built:true},prioritySaveRequested:true};}
export function selectCollectionSource(boxes:Record<CollectionSourceId,CollectionBox>,ages:Record<CollectionSourceId,number>,demand:Partial<Record<CollectionSourceId,number>>={},start=0):CollectionSourceId|null{let best:CollectionSourceId|null=null,bestScore=-Infinity;for(let offset=0;offset<COLLECTION_SOURCES.length;offset++){const id=COLLECTION_SOURCES[(start+offset)%3],box=boxes[id];if(!box.built||box.amounts[id]<=0)continue;const score=box.amounts[id]/box.capacity*100+(demand[id]??0)*20+ages[id]/1000;if(score>bestScore){best=id;bestScore=score}}return best;}
export const getCourierLoadAmount=(sourceAmount:number,carried:number,capacity:number)=>Math.max(0,Math.min(Math.floor(sourceAmount),Math.floor(capacity-carried)));
export const shouldCourierDepart=(carried:number,capacity:number,sourceAmount:number,waitMs:number,urgent=false)=>carried>0&&(carried>=capacity||sourceAmount<=0||waitMs>=900||urgent);
export function loadCourierOne(box:CollectionBox,courier:CollectionCourier,source:CollectionSourceId){if(!box.built||box.amounts[source]<=0)return{changed:false,box,courier,reason:"empty" as const};if(total(courier.carried)>=courier.capacity)return{changed:false,box,courier,reason:"full" as const};return{changed:true,box:{...box,amounts:{...box.amounts,[source]:box.amounts[source]-1}},courier:{...courier,carried:{...courier.carried,[source]:courier.carried[source]+1}}};}
export function selectCourierDestination(resource:ResourceId,mode:CollectionRoutingMode,input:{intakeAmount:number;intakeCapacity:number;millBuilt:boolean;bakeryBuilt:boolean;processingEnabled:boolean;machineInputHasSpace:boolean;needed:boolean}):CollectionDestinationId{if(mode==="barn-first"||["bread","cornbread"].includes(resource))return"barn";const machine=resource==="wheat"||resource==="corn"?input.millBuilt:input.bakeryBuilt;return machine&&input.processingEnabled&&input.machineInputHasSpace&&input.intakeAmount<input.intakeCapacity&&(mode==="processing-first"||input.needed)?"processing-intake":"barn";}
function unloadOne(courier:CollectionCourier,destination:ResourceAmounts,capacity:number,allowed:(r:ResourceId)=>boolean){if(total(destination)>=capacity)return{changed:false,courier,destination,reason:"full" as const};const resource=RESOURCE_IDS.find(r=>courier.carried[r]>0&&allowed(r));if(!resource)return{changed:false,courier,destination,reason:"empty" as const};return{changed:true,resource,courier:{...courier,carried:{...courier.carried,[resource]:courier.carried[resource]-1}},destination:{...destination,[resource]:destination[resource]+1}};}
export const unloadCourierToIntakeOne=(courier:CollectionCourier,intake:ProcessingIntake)=>{const r=unloadOne(courier,intake.amounts,intake.capacity,r=>!["bread","cornbread"].includes(r));return r.changed?{...r,intake:{...intake,amounts:r.destination}}:{...r,intake};};
export const unloadCourierToBarnOne=(courier:CollectionCourier,barn:ResourceAmounts)=>unloadOne(courier,barn,Number.MAX_SAFE_INTEGER,()=>true);
export function routeIntakeResourceOne(intake:ProcessingIntake,mill:ResourceAmounts,bakery:ResourceAmounts,capacities:{mill:number;bakery:number}){for(let n=0;n<RESOURCE_IDS.length;n++){const index=(intake.roundRobinIndex+n)%RESOURCE_IDS.length,r=RESOURCE_IDS[index];if(intake.amounts[r]<=0)continue;const target=(r==="wheat"||r==="corn")?mill:(r==="egg"||r==="flour"||r==="cornmeal")?bakery:null,capacity=target===mill?capacities.mill:capacities.bakery;if(!target||total(target)>=capacity)continue;return{changed:true,resource:r,intake:{...intake,amounts:{...intake.amounts,[r]:intake.amounts[r]-1},roundRobinIndex:(index+1)%RESOURCE_IDS.length},mill:target===mill?{...mill,[r]:mill[r]+1}:mill,bakery:target===bakery?{...bakery,[r]:bakery[r]+1}:bakery};}return{changed:false,intake,mill,bakery};}
export const getCollectionNetworkTotalByResource=(network:CollectionNetwork,resource:ResourceId)=>COLLECTION_SOURCES.reduce((n,id)=>n+network.boxes[id].amounts[resource],0)+network.courier.carried[resource]+network.processingIntake.amounts[resource];
export function hireCourier(wallet:number,hubBuilt:boolean,courier:CollectionCourier){if(!hubBuilt||courier.hired||wallet<480)return{changed:false,wallet,courier,prioritySaveRequested:false};return{changed:true,wallet:wallet-480,courier:{...courier,hired:true,level:1 as const,capacity:10,stage:"idle-at-hub" as const},prioritySaveRequested:true};}
export function trainCourier(wallet:number,courier:CollectionCourier){const costs=[0,260,620,0],cost=costs[courier.level];if(!courier.hired||courier.level===0||courier.level===3||wallet<cost)return{changed:false,wallet,courier,prioritySaveRequested:false};const level=(courier.level+1) as 2|3;return{changed:true,wallet:wallet-cost,courier:{...courier,level,capacity:COURIER_CAPACITIES[level]},prioritySaveRequested:true};}
