import { describe,expect,it } from "vitest";
import { acceptContract, advanceContractActiveTime, calculateContractReward, cancelActiveContract, completeContract, createContractState, declineContractOffer, deliverNextContractResourceOne, generateContractOffers } from "./contracts";

describe("delivery contracts",()=>{
 it("generates three stable wheat-only offers",()=>{const input={seed:42,nextSequence:7,count:3,unlockedResources:["wheat"] as const,reputationLevel:0};expect(generateContractOffers(input)).toEqual(generateContractOffers(input));const r=generateContractOffers(input);expect(r.offers).toHaveLength(3);expect(new Set(r.offers.map(o=>o.id)).size).toBe(3);expect(r.offers.every(o=>o.requirements.wheat>0&&o.requirements.corn===0&&o.requirements.egg===0)).toBe(true);});
 it("uses unlocked resources only and integer rewards",()=>{const r=generateContractOffers({seed:99,nextSequence:1,count:30,unlockedResources:["wheat","corn","egg"],reputationLevel:3});expect(r.offers.every(o=>Object.values(o.requirements).every(Number.isInteger)&&Number.isInteger(o.baseRewardCoins))).toBe(true);expect(r.offers.some(o=>o.requirements.corn>0||o.requirements.egg>0)).toBe(true);});
 it("accepts and replaces without inventory mutation",()=>{const s=createContractState();const r=acceptContract(s,s.offers[0]!.id,["wheat"]);expect(r.ok).toBe(true);if(r.ok){expect(r.state.active?.elapsedActiveMs).toBe(0);expect(r.state.offers).toHaveLength(3);expect(acceptContract(r.state,r.state.offers[0]!.id,["wheat"]).ok).toBe(false);}});
 it("declines with cooldown",()=>{const s=createContractState();const r=declineContractOffer(s,s.offers[0]!.id,["wheat"]);expect(r.ok).toBe(true);if(r.ok){expect(r.state.statistics.offersDeclined).toBe(1);expect(declineContractOffer(r.state,r.state.offers[0]!.id,["wheat"]).ok).toBe(false);}});
 it("delivers one barn unit and cancellation conserves it",()=>{const s=createContractState();const accepted=acceptContract(s,s.offers[0]!.id,["wheat"]);if(!accepted.ok)throw Error();const delivered=deliverNextContractResourceOne(accepted.state,{wheat:2,corn:5,egg:5,flour:0,cornmeal:0,bread:0,cornbread:0,hay:0,milk:0,butter:0,cheese:0});expect(delivered.barn).toEqual({wheat:1,corn:5,egg:5,flour:0,cornmeal:0,bread:0,cornbread:0,hay:0,milk:0,butter:0,cheese:0});expect(delivered.resource).toBe("wheat");const cancelled=cancelActiveContract(delivered.state,delivered.barn);expect(cancelled.ok&&cancelled.barn).toEqual({wheat:2,corn:5,egg:5,flour:0,cornmeal:0,bread:0,cornbread:0,hay:0,milk:0,butter:0,cheese:0});});
 it("completes once into wallet and not till",()=>{let s=createContractState();const a=acceptContract(s,s.offers[0]!.id,["wheat"]);if(!a.ok)throw Error();const active=a.state.active!;s={...a.state,active:{...active,delivered:{...active.requirements}}};const r=completeContract(s,10);expect(r.ok).toBe(true);if(r.ok){expect(r.wallet).toBe(10+r.reward.total);expect(r.state.statistics.contractsCompleted).toBe(1);expect(completeContract(r.state,r.wallet).ok).toBe(false);}});
 it("advances only active unpaused time and retains base after bonus",()=>{const a=acceptContract(createContractState(),"contract-000001",["wheat"]);if(!a.ok)throw Error();expect(advanceContractActiveTime(a.state,1000,true).active?.elapsedActiveMs).toBe(0);expect(advanceContractActiveTime(a.state,1000,false).active?.elapsedActiveMs).toBe(1000);const req={wheat:20,corn:0,egg:0,flour:0,cornmeal:0,bread:0,cornbread:0,hay:0,milk:0,butter:0,cheese:0};expect(calculateContractReward(req,"single",0,999999,100).bonus).toBe(0);expect(calculateContractReward(req,"single",0,999999,100).base).toBeGreaterThan(0);});
});
