import {describe,expect,it} from "vitest";
import {emptyResourceAmounts,RESOURCE_DEFINITIONS,RESOURCE_IDS,type ResourceId} from "../config/resourceDefinitions";
import {createCarriedCargo} from "./resources";
import type {ContractState} from "../contracts/contractTypes";
import {acceptContract,advanceContractActiveTime,cancelActiveContract,completeContract,createContractState,declineContractOffer,deliverNextContractResourceOne,formatContractIdentity,generateContractOffers} from "./contracts";
const barn=(values:Partial<Record<ResourceId,number>>={})=>({...emptyResourceAmounts(),...values});
const cargo=(values:Partial<Record<ResourceId,number>>={})=>({ ...createCarriedCargo(),amounts:barn(values)});
describe("contracts",()=>{
 it("uses truthful labels and stable identities for every eligible resource",()=>{for(const id of RESOURCE_IDS.filter(id=>RESOURCE_DEFINITIONS[id].contractEligible)){const generated=generateContractOffers({seed:7,nextSequence:123,count:1,unlockedResources:[id],reputationLevel:0});expect(generated.offers[0]!.requirements[id]).toBeGreaterThan(0);expect(RESOURCE_DEFINITIONS[id].publicName).not.toBe(id==="egg"?"":"たまご");expect(formatContractIdentity(generated.offers[0]!)).toBe("依頼 #000123");}expect(()=>generateContractOffers({seed:1,nextSequence:1,count:1,unlockedResources:["hay"],reputationLevel:0})).toThrow();});
 it("repeatedly declines exact IDs with distinct replacements and no business cooldown",()=>{let state=createContractState();for(let count=1;count<=4;count++){const old=state.offers.map(o=>o.id),selected=old[1]!;const command=declineContractOffer(state,selected,["wheat"]);expect(command.changed).toBe(true);state=command.state;expect(state.offers).toHaveLength(3);expect(state.offers.map(o=>o.id)).not.toContain(selected);expect(state.offers.filter(o=>!old.includes(o.id))).toHaveLength(1);expect(state.statistics.offersDeclined).toBe(count);expect(state.declineCooldownMs).toBe(0);}const failed=declineContractOffer(state,"missing",["wheat"]);expect(failed).toMatchObject({changed:false,reason:"offer-not-found",prioritySaveRequested:false});});
 it("delivers cargo first, warehouse second, and reports exact missing stock",()=>{const accepted=acceptContract(createContractState(),"contract-000001",["wheat"]);let state=accepted.state;state={...state,active:{...state.active!,requirements:{...emptyResourceAmounts(),wheat:3},delivered:emptyResourceAmounts()}};let delivery=deliverNextContractResourceOne(state,cargo({wheat:1}),barn({wheat:2,egg:9}));expect(delivery).toMatchObject({changed:true,resource:"wheat",source:"cargo"});expect(delivery.cargo.amounts.wheat).toBe(0);delivery=deliverNextContractResourceOne(delivery.state,delivery.cargo,delivery.barn);expect(delivery.source).toBe("barn");expect(delivery.barn).toMatchObject({wheat:1,egg:9});const noStock=deliverNextContractResourceOne({...delivery.state,active:{...delivery.state.active!,requirements:{...emptyResourceAmounts(),milk:3},delivered:emptyResourceAmounts()}},cargo(),barn());expect(noStock).toMatchObject({changed:false,reason:"no-deliverable-stock"});expect(noStock.message).toBe("出荷できる商品がありません\n不足：牛乳 3");});
 it("round robins mixed egg, processed, and dairy resources without consuming unrelated locations",()=>{const accepted=acceptContract(createContractState(),"contract-000001",["wheat"]);let state:ContractState={...accepted.state,active:{...accepted.state.active!,requirements:{...emptyResourceAmounts(),egg:1,flour:1,bread:1,milk:1,butter:1,cheese:1},delivered:emptyResourceAmounts()}};let c=cargo({egg:1,flour:1,bread:1,milk:1,butter:1,cheese:1}),b=barn();const seen:ResourceId[]=[];for(let i=0;i<6;i++){const d=deliverNextContractResourceOne(state,c,b);expect(d.changed).toBe(true);seen.push(d.resource!);state=d.state;c=d.cargo;b=d.barn;}expect(seen).toEqual(["egg","flour","bread","milk","butter","cheese"]);});
 it("cancellation conserves delivered quantities and reports returns",()=>{const accepted=acceptContract(createContractState(),"contract-000001",["wheat"]);const state={...accepted.state,active:{...accepted.state.active!,requirements:{...emptyResourceAmounts(),egg:2,cheese:1},delivered:{...emptyResourceAmounts(),egg:2,cheese:1}}};const cancelled=cancelActiveContract(state,barn({egg:4}));expect(cancelled.changed).toBe(true);expect(cancelled.barn).toMatchObject({egg:6,cheese:1});expect(cancelled.returned).toMatchObject({egg:2,cheese:1});expect(cancelled.message).toContain("たまご 2個");});
 it("completes immediately and exactly once",()=>{const accepted=acceptContract(createContractState(),"contract-000001",["wheat"]);const state={...accepted.state,active:{...accepted.state.active!,delivered:{...accepted.state.active!.requirements}}};const done=completeContract(state,10);expect(done.changed).toBe(true);if(!("reward" in done))throw Error();expect(done.wallet).toBe(10+done.reward.total);expect(done.state.statistics.contractsCompleted).toBe(1);expect(completeContract(done.state,done.wallet)).toMatchObject({changed:false,reason:"no-active-contract"});});
 it("normalizes obsolete cooldown and advances only active unpaused time",()=>{const state={...createContractState(),declineCooldownMs:30000};expect(advanceContractActiveTime(state,1000,false).declineCooldownMs).toBe(0);const accepted=acceptContract(state,"contract-000001",["wheat"]);expect(advanceContractActiveTime(accepted.state,1000,true).active?.elapsedActiveMs).toBe(0);expect(advanceContractActiveTime(accepted.state,1000,false).active?.elapsedActiveMs).toBe(1000);});
});
