import {describe,expect,it} from "vitest";
import {emptyResourceAmounts,RESOURCE_DEFINITIONS,RESOURCE_IDS,type ResourceId} from "../config/resourceDefinitions";
import {createCarriedCargo} from "./resources";
import type {ContractState} from "../contracts/contractTypes";
import {acceptContract,advanceContractActiveTime,cancelActiveContract,completeContract,createContractState,declineContractOffer,deliverContractBatch,deliverNextContractResourceOne,formatContractIdentity,generateContractOffers} from "./contracts";
const barn=(values:Partial<Record<ResourceId,number>>={})=>({...emptyResourceAmounts(),...values});
const cargo=(values:Partial<Record<ResourceId,number>>={})=>({ ...createCarriedCargo(),amounts:barn(values)});
describe("contracts",()=>{
 it("uses truthful labels and stable identities for every eligible resource",()=>{for(const id of RESOURCE_IDS.filter(id=>RESOURCE_DEFINITIONS[id].contractEligible)){const generated=generateContractOffers({seed:7,nextSequence:123,count:1,unlockedResources:[id],reputationLevel:0});expect(generated.offers[0]!.requirements[id]).toBeGreaterThan(0);expect(RESOURCE_DEFINITIONS[id].publicName).not.toBe(id==="egg"?"":"たまご");expect(formatContractIdentity(generated.offers[0]!)).toBe("依頼 #000123");}expect(()=>generateContractOffers({seed:1,nextSequence:1,count:1,unlockedResources:["hay"],reputationLevel:0})).toThrow();});
 it("repeatedly declines exact IDs with distinct replacements and no business cooldown",()=>{let state=createContractState();for(let count=1;count<=4;count++){const old=state.offers.map(o=>o.id),selected=old[1]!;const command=declineContractOffer(state,selected,["wheat"]);expect(command.changed).toBe(true);state=command.state;expect(state.offers).toHaveLength(3);expect(state.offers.map(o=>o.id)).not.toContain(selected);expect(state.offers.filter(o=>!old.includes(o.id))).toHaveLength(1);expect(state.statistics.offersDeclined).toBe(count);expect(state.declineCooldownMs).toBe(0);}const failed=declineContractOffer(state,"missing",["wheat"]);expect(failed).toMatchObject({changed:false,reason:"offer-not-found",prioritySaveRequested:false});});
 it("delivers cargo first, warehouse second, and reports exact missing stock",()=>{const accepted=acceptContract(createContractState(),"contract-000001",["wheat"]);let state=accepted.state;state={...state,active:{...state.active!,requirements:{...emptyResourceAmounts(),wheat:3},delivered:emptyResourceAmounts()}};let delivery=deliverNextContractResourceOne(state,cargo({wheat:1}),barn({wheat:2,egg:9}));expect(delivery).toMatchObject({changed:true,resource:"wheat",source:"cargo"});expect(delivery.cargo.amounts.wheat).toBe(0);delivery=deliverNextContractResourceOne(delivery.state,delivery.cargo,delivery.barn);expect(delivery.source).toBe("barn");expect(delivery.barn).toMatchObject({wheat:1,egg:9});const noStock=deliverNextContractResourceOne({...delivery.state,active:{...delivery.state.active!,requirements:{...emptyResourceAmounts(),milk:3},delivered:emptyResourceAmounts()}},cargo(),barn());expect(noStock).toMatchObject({changed:false,reason:"no-deliverable-stock"});expect(noStock.message).toBe("出荷できる商品がありません\n不足：牛乳 3");});
 it("round robins mixed egg, processed, and dairy resources without consuming unrelated locations",()=>{const accepted=acceptContract(createContractState(),"contract-000001",["wheat"]);let state:ContractState={...accepted.state,active:{...accepted.state.active!,requirements:{...emptyResourceAmounts(),egg:1,flour:1,bread:1,milk:1,butter:1,cheese:1},delivered:emptyResourceAmounts()}};let c=cargo({egg:1,flour:1,bread:1,milk:1,butter:1,cheese:1}),b=barn();const seen:ResourceId[]=[];for(let i=0;i<6;i++){const d=deliverNextContractResourceOne(state,c,b);expect(d.changed).toBe(true);seen.push(d.resource!);state=d.state;c=d.cargo;b=d.barn;}expect(seen).toEqual(["egg","flour","bread","milk","butter","cheese"]);});
 it("cancellation conserves delivered quantities and reports returns",()=>{const accepted=acceptContract(createContractState(),"contract-000001",["wheat"]);const state={...accepted.state,active:{...accepted.state.active!,requirements:{...emptyResourceAmounts(),egg:2,cheese:1},delivered:{...emptyResourceAmounts(),egg:2,cheese:1}}};const cancelled=cancelActiveContract(state,barn({egg:4}));expect(cancelled.changed).toBe(true);expect(cancelled.barn).toMatchObject({egg:6,cheese:1});expect(cancelled.returned).toMatchObject({egg:2,cheese:1});expect(cancelled.message).toContain("たまご 2個");});
 it("completes immediately and exactly once",()=>{const accepted=acceptContract(createContractState(),"contract-000001",["wheat"]);const state={...accepted.state,active:{...accepted.state.active!,delivered:{...accepted.state.active!.requirements}}};const done=completeContract(state,10);expect(done.changed).toBe(true);if(!("reward" in done))throw Error();expect(done.wallet).toBe(10+done.reward.total);expect(done.state.statistics.contractsCompleted).toBe(1);expect(completeContract(done.state,done.wallet)).toMatchObject({changed:false,reason:"no-active-contract"});});
 it("normalizes obsolete cooldown and advances only active unpaused time",()=>{const state={...createContractState(),declineCooldownMs:30000};expect(advanceContractActiveTime(state,1000,false).declineCooldownMs).toBe(0);const accepted=acceptContract(state,"contract-000001",["wheat"]);expect(advanceContractActiveTime(accepted.state,1000,true).active?.elapsedActiveMs).toBe(0);expect(advanceContractActiveTime(accepted.state,1000,false).active?.elapsedActiveMs).toBe(1000);});
 describe("atomic batch delivery",()=>{
  const active=(requirements:Partial<Record<ResourceId,number>>,delivered:Partial<Record<ResourceId,number>>={})=>{const accepted=acceptContract(createContractState(),"contract-000001",["wheat"]);return{...accepted.state,active:{...accepted.state.active!,requirements:barn(requirements),delivered:barn(delivered)}};};
  it("delivers a full single-resource batch from cargo or warehouse",()=>{const fromCargo=deliverContractBatch(active({wheat:12}),cargo({wheat:12}),barn());expect(fromCargo).toMatchObject({changed:true,totalDelivered:12,complete:true,breakdown:[{resource:"wheat",fromCargo:12,fromBarn:0,remaining:0}]});const fromBarn=deliverContractBatch(active({wheat:12}),cargo(),barn({wheat:12}));expect(fromBarn.breakdown[0]).toMatchObject({fromCargo:0,fromBarn:12});});
  it("uses cargo first, then barn, and reports exact mixed partial remainder",()=>{const beforeCargo=cargo({egg:2,bread:1,cheese:9}),beforeBarn=barn({egg:7,bread:2,flour:1,cheese:4});const result=deliverContractBatch(active({egg:5,bread:4,flour:3}),beforeCargo,beforeBarn);expect(result).toMatchObject({changed:true,totalDelivered:9,complete:false});expect(result.breakdown).toEqual(expect.arrayContaining([{resource:"egg",fromCargo:2,fromBarn:3,deliveredThisBatch:5,deliveredTotal:5,requirement:5,remaining:0},{resource:"flour",fromCargo:0,fromBarn:1,deliveredThisBatch:1,deliveredTotal:1,requirement:3,remaining:2},{resource:"bread",fromCargo:1,fromBarn:2,deliveredThisBatch:3,deliveredTotal:3,requirement:4,remaining:1}]));expect(result.cargo.amounts.cheese).toBe(9);expect(result.barn.cheese).toBe(4);expect(result.message).toContain("小麦粉 2");});
  it("conserves every resource exactly and cancellation returns a partial batch once",()=>{const state=active({egg:5,cheese:3}),c=cargo({egg:2,cheese:1}),b=barn({egg:2,cheese:8});const batch=deliverContractBatch(state,c,b);for(const id of RESOURCE_IDS)expect(c.amounts[id]+b[id]+state.active!.delivered[id]).toBe(batch.cargo.amounts[id]+batch.barn[id]+batch.state.active!.delivered[id]);const cancelled=cancelActiveContract(batch.state,batch.barn);expect(cancelled.barn.egg).toBe(4);expect(cancelled.barn.cheese).toBe(9);expect(cancelActiveContract(cancelled.state,cancelled.barn).changed).toBe(false);});
  it("is a no-op without stock and processes large quantities with one breakdown row",()=>{expect(deliverContractBatch(active({milk:3}),cargo(),barn())).toMatchObject({changed:false,reason:"no-deliverable-stock"});const large=deliverContractBatch(active({butter:100000}),cargo({butter:40000}),barn({butter:60000}));expect(large).toMatchObject({totalDelivered:100000,complete:true});expect(large.breakdown).toHaveLength(1);});
  it("can be completed and rewarded exactly once after the same batch",()=>{const batch=deliverContractBatch(active({cheese:2}),cargo({cheese:2}),barn());const completed=completeContract(batch.state,20);expect(completed.changed).toBe(true);if(!("reward" in completed))throw Error();expect(completeContract(completed.state,completed.wallet)).toMatchObject({changed:false,reason:"no-active-contract"});});
 });
});
