import { emptyResourceAmounts, type ResourceAmounts } from "../config/resourceDefinitions";
import type { CarriedCargo } from "./resources";
import { getCarriedTotal } from "./resources";

export type PastureLevel=0|1|2; export type DairyLevel=0|1|2|3; export type DairyRecipe="butter"|"cheese";
export interface CowState { id:string; producing:boolean; productionRemainingMs:number; readyMilk:number; activitySeed:number }
export type PastureNodeState="growing"|"ready"|"cut";
export interface PastureNode { id:string; state:PastureNodeState; remainingMs:number }
export interface DairyCycle { recipe:DairyRecipe; remainingMs:number; durationMs:number; reservedMilk:number }
export interface DairyState { pastureUnlocked:boolean; pastureLevel:PastureLevel; pastureNodes:PastureNode[]; barnBuilt:boolean; cows:CowState[]; hayRack:number; milkTank:number; workshopBuilt:boolean; workshopLevel:DairyLevel; workshopMode:"auto"|"butter"|"cheese"|"stopped"; workshopInput:number; workshopOutput:{butter:number;cheese:number}; cycle:DairyCycle|null; protectedMilk:number; dairyWorker:{hired:boolean;level:DairyLevel;carried:"hay"|"milk"|null;amount:number}; workshopWorker:{hired:boolean;level:DairyLevel;carried:"milk"|"butter"|"cheese"|null;amount:number} }
export const createPastureNodes=(level:PastureLevel):PastureNode[]=>Array.from({length:getPasturePlots(level)},(_,i)=>({id:`pasture-${String(i).padStart(2,"0")}`,state:"ready",remainingMs:0}));
export const createDairyState=():DairyState=>({pastureUnlocked:false,pastureLevel:0,pastureNodes:createPastureNodes(0),barnBuilt:false,cows:[],hayRack:0,milkTank:0,workshopBuilt:false,workshopLevel:0,workshopMode:"auto",workshopInput:0,workshopOutput:{butter:0,cheese:0},cycle:null,protectedMilk:6,dairyWorker:{hired:false,level:0,carried:null,amount:0},workshopWorker:{hired:false,level:0,carried:null,amount:0}});
type Tx={changed:boolean;wallet:number;reason?:"prerequisite"|"coins"|"duplicate"|"maximum"};
export function purchasePasture(s:DairyState,wallet:number):Tx{if(!s.pastureUnlocked&&wallet>=1000)return{changed:true,wallet:wallet-1000};return{changed:false,wallet,reason:s.pastureUnlocked?"duplicate":"coins"}}
export function expandPasture(level:PastureLevel,wallet:number):{level:PastureLevel}&Tx{if(level===2)return{changed:false,wallet,level,reason:"maximum"};const cost=level===0?300:700;return wallet>=cost?{changed:true,wallet:wallet-cost,level:(level+1) as PastureLevel}:{changed:false,wallet,level,reason:"coins"}}
export const getPasturePlots=(level:PastureLevel)=>[24,36,48][level]!;
export function advancePastureNodes(nodes:PastureNode[],deltaMs:number):PastureNode[]{return nodes.map(node=>node.state==="ready"?node:{...node,remainingMs:Math.max(0,node.remainingMs-deltaMs),...(node.remainingMs<=deltaMs?{state:"ready" as const}: {})})}
export function harvestPastureNode(nodes:PastureNode[],id:string,hasCapacity:boolean){if(!hasCapacity)return{nodes,harvested:false};const index=nodes.findIndex(n=>n.id===id&&n.state==="ready");if(index<0)return{nodes,harvested:false};const next=nodes.slice(),stagger=8000+(index%9)*500;next[index]={...next[index]!,state:"cut",remainingMs:stagger};return{nodes:next,harvested:true}}
export function buildCowBarn(s:DairyState,wallet:number):Tx{if(!s.pastureUnlocked)return{changed:false,wallet,reason:"prerequisite"};if(s.barnBuilt)return{changed:false,wallet,reason:"duplicate"};return wallet>=1400?{changed:true,wallet:wallet-1400}:{changed:false,wallet,reason:"coins"}}
export function buyCow(count:number,wallet:number):{count:number}&Tx{if(count>=3)return{changed:false,wallet,count,reason:"maximum"};const cost=count===1?550:950;return wallet>=cost?{changed:true,wallet:wallet-cost,count:count+1}:{changed:false,wallet,count,reason:"coins"}}
export function advanceCows(cows:CowState[],hayRack:number,milkTank:number,deltaMs:number){const next=cows.map(c=>({...c}));let hay=hayRack,tank=milkTank;for(const cow of next){if(cow.readyMilk>0&&tank<24){tank++;cow.readyMilk--; }if(cow.producing){cow.productionRemainingMs=Math.max(0,cow.productionRemainingMs-deltaMs);if(cow.productionRemainingMs===0){cow.producing=false;if(tank<24)tank++;else cow.readyMilk++;}}if(!cow.producing&&cow.readyMilk===0&&hay>0){hay--;cow.producing=true;cow.productionRemainingMs=10000}}return{cows:next,hayRack:hay,milkTank:tank};}
const recipe=(id:DairyRecipe)=>id==="butter"?{milk:2,time:6000}:{milk:3,time:10000}; const capacities=[0,18,24,32],outCaps=[0,12,18,24],speed=[0,1,.75,.55];
export function startDairyCycle(s:DairyState,preferred:DairyRecipe="butter"):DairyState{if(!s.workshopBuilt||s.workshopMode==="stopped"||s.cycle)return s;const id=s.workshopMode==="auto"?preferred:s.workshopMode,r=recipe(id);if(s.workshopInput<r.milk||s.workshopOutput.butter+s.workshopOutput.cheese>=outCaps[s.workshopLevel]!)return s;const duration=Math.round(r.time*speed[s.workshopLevel]!);return{...s,workshopInput:s.workshopInput-r.milk,cycle:{recipe:id,remainingMs:duration,durationMs:duration,reservedMilk:r.milk}}}
export function advanceDairyCycle(s:DairyState,deltaMs:number):DairyState{if(!s.cycle)return s;const remaining=Math.max(0,s.cycle.remainingMs-deltaMs);if(remaining>0)return{...s,cycle:{...s.cycle,remainingMs:remaining}};if(s.workshopOutput.butter+s.workshopOutput.cheese>=outCaps[s.workshopLevel]!)return{...s,cycle:{...s.cycle,remainingMs:0}};return{...s,workshopOutput:{...s.workshopOutput,[s.cycle.recipe]:s.workshopOutput[s.cycle.recipe]+1},cycle:null}}
export function cancelDairyCycle(s:DairyState,barn:ResourceAmounts){if(!s.cycle)return{s,barn};const room=capacities[s.workshopLevel]!-s.workshopInput,returned=Math.min(room,s.cycle.reservedMilk);return{s:{...s,workshopInput:s.workshopInput+returned,cycle:null},barn:{...barn,milk:barn.milk+s.cycle.reservedMilk-returned}}}
export const getProtectedMilkAmount=(market:number,contract:number,base=6)=>Math.max(0,Math.floor(market)+Math.floor(contract)+Math.floor(base));
export const canSendMilkToWorkshop=(barnMilk:number,input:number,level:DairyLevel,protectedAmount:number)=>barnMilk>protectedAmount&&input<capacities[level]!;
export const getDairyInputBatch=(available:number,input:number,level:DairyLevel,recipeId:DairyRecipe,capacity:number)=>Math.max(0,Math.min(available,capacities[level]!-input,capacity)-Math.min(available,capacities[level]!-input,capacity)%recipe(recipeId).milk);
export const getDairyOutputBatch=(available:number,capacity:number)=>Math.max(0,Math.min(Math.floor(available),Math.floor(capacity)));
export type DairyTask="feed-emergency"|"collect-milk"|"feed"|"wait";
export function selectDairyTask(input:{hired:boolean;hayRack:number;milkTank:number;hayAvailable:number}) :DairyTask {if(!input.hired)return"wait";if(input.hayRack<=5&&input.hayAvailable>0)return"feed-emergency";if(input.milkTank>=5)return"collect-milk";if(input.hayRack<18&&input.hayAvailable>0)return"feed";return"wait"}
export const emptyDairyCargo=():ResourceAmounts=>emptyResourceAmounts();

export type DairyFacilityId="pasture-purchase"|"pasture-expansion"|"cow-barn"|"cow-purchase"|"hay-rack"|"milk-tank"|"workshop-build"|"workshop-input"|"workshop-output"|"dairy-board";
export interface DairyFacilityDefinition {id:DairyFacilityId;publicName:string;center:{x:number;y:number};radius:number;visibleRadius:number;capacity?:number;acceptedResources?:readonly (keyof ResourceAmounts)[];producedResources?:readonly (keyof ResourceAmounts)[]}
export const DAIRY_FACILITIES:Readonly<Record<DairyFacilityId,DairyFacilityDefinition>>={
 "pasture-purchase":{id:"pasture-purchase",publicName:"牧草地購入地点",center:{x:3110,y:550},radius:100,visibleRadius:120},
 "pasture-expansion":{id:"pasture-expansion",publicName:"牧草地拡張地点",center:{x:3120,y:950},radius:100,visibleRadius:120},
 "cow-barn":{id:"cow-barn",publicName:"牛舎建設地点",center:{x:3350,y:1120},radius:100,visibleRadius:120},
 "cow-purchase":{id:"cow-purchase",publicName:"牛購入地点",center:{x:3550,y:1120},radius:100,visibleRadius:120},
 "hay-rack":{id:"hay-rack",publicName:"干し草台",center:{x:3220,y:1360},radius:105,visibleRadius:125,capacity:24,acceptedResources:["hay"]},
 "milk-tank":{id:"milk-tank",publicName:"ミルクタンク",center:{x:3520,y:1360},radius:105,visibleRadius:125,capacity:24,producedResources:["milk"]},
 "workshop-build":{id:"workshop-build",publicName:"乳製品工房建設地点",center:{x:3500,y:1640},radius:100,visibleRadius:120},
 "workshop-input":{id:"workshop-input",publicName:"工房搬入口",center:{x:3310,y:1800},radius:100,visibleRadius:120,acceptedResources:["milk"]},
 "workshop-output":{id:"workshop-output",publicName:"工房受取口",center:{x:3820,y:1800},radius:100,visibleRadius:120,producedResources:["butter","cheese"]},
 "dairy-board":{id:"dairy-board",publicName:"酪農管理板",center:{x:3650,y:1510},radius:120,visibleRadius:145},
};
export interface DairyTransferResult<T>{changed:boolean;value:T;moved:number;fromBefore:number;fromAfter:number;toBefore:number;toAfter:number;reason?:"empty"|"full"|"target-reached"}
export function fillHayRackFromBarn(barn:ResourceAmounts,hayRack:number,target=18,capacity=24):DairyTransferResult<{barn:ResourceAmounts;hayRack:number}>{const to=Math.min(Math.max(0,target),capacity),moved=Math.min(Math.max(0,Math.floor(barn.hay)),Math.max(0,to-hayRack));return{changed:moved>0,value:{barn:{...barn,hay:barn.hay-moved},hayRack:hayRack+moved},moved,fromBefore:barn.hay,fromAfter:barn.hay-moved,toBefore:hayRack,toAfter:hayRack+moved,...(!moved?{reason:barn.hay<=0?"empty" as const:hayRack>=to?"target-reached" as const:"full" as const}:{})}}
export function depositHayBatchFromCargo(cargo:CarriedCargo,hayRack:number,capacity=24):DairyTransferResult<{cargo:CarriedCargo;hayRack:number}>{const moved=Math.min(Math.max(0,cargo.amounts.hay),Math.max(0,capacity-hayRack));const amounts={...cargo.amounts,hay:cargo.amounts.hay-moved};return{changed:moved>0,value:{cargo:{...cargo,amounts},hayRack:hayRack+moved},moved,fromBefore:cargo.amounts.hay,fromAfter:amounts.hay,toBefore:hayRack,toAfter:hayRack+moved,...(!moved?{reason:cargo.amounts.hay<=0?"empty" as const:"full" as const}:{})}}
export function collectMilkBatchToCargo(milkTank:number,cargo:CarriedCargo):DairyTransferResult<{milkTank:number;cargo:CarriedCargo}>{const room=Math.max(0,cargo.capacity-getCarriedTotal(cargo)),moved=Math.min(Math.max(0,milkTank),room);const amounts={...cargo.amounts,milk:cargo.amounts.milk+moved};return{changed:moved>0,value:{milkTank:milkTank-moved,cargo:{...cargo,amounts}},moved,fromBefore:milkTank,fromAfter:milkTank-moved,toBefore:cargo.amounts.milk,toAfter:amounts.milk,...(!moved?{reason:milkTank<=0?"empty" as const:"full" as const}:{})}}
export function moveMilkTankToBarn(milkTank:number,barn:ResourceAmounts):DairyTransferResult<{milkTank:number;barn:ResourceAmounts}>{const moved=Math.max(0,Math.floor(milkTank));return{changed:moved>0,value:{milkTank:milkTank-moved,barn:{...barn,milk:barn.milk+moved}},moved,fromBefore:milkTank,fromAfter:milkTank-moved,toBefore:barn.milk,toAfter:barn.milk+moved,...(!moved?{reason:"empty" as const}:{})}}
export const getDairyWorkerCapacity=(level:number)=>[0,8,12,16][level]??0;
export type DairyWorkerRole="dairyWorker"|"workshopWorker";
export function hireDairyWorker(role:DairyWorkerRole,worker:DairyState[DairyWorkerRole],wallet:number){const cost=role==="dairyWorker"?650:750;if(worker.hired)return{changed:false,worker,wallet,reason:"duplicate"};if(wallet<cost)return{changed:false,worker,wallet,reason:"coins"};return{changed:true,worker:{...worker,hired:true,level:1 as const},wallet:wallet-cost}}
export function trainDairyWorker(role:DairyWorkerRole,worker:DairyState[DairyWorkerRole],wallet:number){if(!worker.hired||worker.level===0)return{changed:false,worker,wallet,reason:"not-hired"};if(worker.level===3)return{changed:false,worker,wallet,reason:"maximum"};const costs=role==="dairyWorker"?[0,280,620]:[0,360,760],cost=costs[worker.level]!;if(wallet<cost)return{changed:false,worker,wallet,reason:"coins"};return{changed:true,worker:{...worker,level:(worker.level+1) as 2|3},wallet:wallet-cost}}
export function getCowBarnStatus(d:DairyState){const active=d.cows.filter(c=>c.producing).length,waiting=d.cows.filter(c=>!c.producing&&c.readyMilk===0).length,held=d.cows.reduce((n,c)=>n+c.readyMilk,0),times=d.cows.filter(c=>c.producing).map(c=>c.productionRemainingMs);return{active,waiting,held,nextMilkMs:times.length?Math.min(...times):null};}
