import { emptyResourceAmounts, type ResourceAmounts } from "../config/resourceDefinitions";

export type PastureLevel=0|1|2; export type DairyLevel=0|1|2|3; export type DairyRecipe="butter"|"cheese";
export interface CowState { id:string; producing:boolean; productionRemainingMs:number; readyMilk:number; activitySeed:number }
export type PastureNodeState="growing"|"ready"|"cut";
export interface PastureNode { id:string; state:PastureNodeState; remainingMs:number }
export interface DairyCycle { recipe:DairyRecipe; remainingMs:number; durationMs:number; reservedMilk:number }
export interface DairyState { pastureUnlocked:boolean; pastureLevel:PastureLevel; pastureNodes:PastureNode[]; barnBuilt:boolean; cows:CowState[]; hayRack:number; milkTank:number; workshopBuilt:boolean; workshopLevel:DairyLevel; workshopMode:"auto"|"butter"|"cheese"|"stopped"; workshopInput:number; workshopOutput:{butter:number;cheese:number}; cycle:DairyCycle|null; protectedMilk:number; dairyWorker:{hired:boolean;level:DairyLevel;carried:"hay"|"milk"|null;amount:number}; workshopWorker:{hired:boolean;level:DairyLevel;carried:"milk"|"butter"|"cheese"|null;amount:number} }
export const createPastureNodes=(level:PastureLevel):PastureNode[]=>Array.from({length:getPasturePlots(level)},(_,i)=>({id:`pasture-${String(i).padStart(2,"0")}`,state:"ready",remainingMs:0}));
export const createDairyState=():DairyState=>({pastureUnlocked:false,pastureLevel:0,pastureNodes:createPastureNodes(0),barnBuilt:false,cows:[],hayRack:0,milkTank:0,workshopBuilt:false,workshopLevel:0,workshopMode:"auto",workshopInput:0,workshopOutput:{butter:0,cheese:0},cycle:null,protectedMilk:6,dairyWorker:{hired:false,level:0,carried:null,amount:0},workshopWorker:{hired:false,level:0,carried:null,amount:0}});
type Tx={changed:boolean;wallet:number;reason?:"prerequisite"|"coins"|"duplicate"|"maximum"};
export function purchasePasture(s:DairyState,wallet:number):Tx{if(!s.pastureUnlocked&&wallet>=1000)return{changed:true,wallet:wallet-1000};return{changed:false,wallet,reason:s.pastureUnlocked?"duplicate":"coins"}}
export function expandPasture(level:PastureLevel,wallet:number):{level:PastureLevel}&Tx{if(level===2)return{changed:false,wallet,level,reason:"maximum"};const cost=level===0?300:700;return wallet>=cost?{changed:true,wallet:wallet-cost,level:(level+1) as PastureLevel}:{changed:false,wallet,level,reason:"coins"}}
export const getPasturePlots=(level:PastureLevel)=>[24,36,48][level]!;
export function advancePastureNodes(nodes:PastureNode[],deltaMs:number):PastureNode[]{return nodes.map(node=>node.state==="ready"?node:{...node,remainingMs:Math.max(0,node.remainingMs-deltaMs),...(node.remainingMs<=deltaMs?{state:"ready" as const}: {})})}
export function harvestPastureNode(nodes:PastureNode[],id:string,hasCapacity:boolean){if(!hasCapacity)return{nodes,harvested:false};const index=nodes.findIndex(n=>n.id===id&&n.state==="ready");if(index<0)return{nodes,harvested:false};const next=nodes.slice(),stagger=8000+(index%9)*500;next[index]={...next[index]!,state:"cut",remainingMs:stagger};return{nodes:next,harvested:true}}
export function buildCowBarn(s:DairyState,wallet:number):Tx{if(!s.pastureUnlocked)return{changed:false,wallet,reason:"prerequisite"};if(s.barnBuilt)return{changed:false,wallet,reason:"duplicate"};return wallet>=1400?{changed:true,wallet:wallet-1400}:{changed:false,wallet,reason:"coins"}}
export function buyCow(count:number,wallet:number):{count:number}&Tx{if(count>=3)return{changed:false,wallet,count,reason:"maximum"};const cost=count===1?550:950;return wallet>=cost?{changed:true,wallet:wallet-cost,count:count+1}:{changed:false,wallet,count,reason:"coins"}}
export function advanceCows(cows:CowState[],hayRack:number,milkTank:number,deltaMs:number){const next=cows.map(c=>({...c}));let hay=hayRack,tank=milkTank;for(const cow of next){if(cow.readyMilk>0&&tank<24){tank++;cow.readyMilk--; }if(cow.producing){cow.productionRemainingMs=Math.max(0,cow.productionRemainingMs-deltaMs);if(cow.productionRemainingMs===0){cow.producing=false;if(tank<24)tank++;else cow.readyMilk++;}}if(!cow.producing&&cow.readyMilk===0&&hay>0){hay--;cow.producing=true;cow.productionRemainingMs=10000}}return{cows:next,hayRack:hay,milkTank:tank};}
const recipe=(id:DairyRecipe)=>id==="butter"?{milk:2,time:6000}:{milk:3,time:10000}; const capacities=[0,18,24,32],outCaps=[0,12,18,24],speed=[0,1,.75,.55];
export function startDairyCycle(s:DairyState,preferred:DairyRecipe="butter"):DairyState{if(!s.workshopBuilt||s.workshopMode==="stopped"||s.cycle)return s;const id=s.workshopMode==="auto"?preferred:s.workshopMode,r=recipe(id);if(s.workshopInput<r.milk||s.workshopOutput.butter+s.workshopOutput.cheese>=outCaps[s.workshopLevel]!)return s;const duration=Math.round(r.time*speed[s.workshopLevel]!);return{...s,workshopInput:s.workshopInput-r.milk,cycle:{recipe:id,remainingMs:duration,durationMs:duration,reservedMilk:r.milk}}}
export function advanceDairyCycle(s:DairyState,deltaMs:number):DairyState{if(!s.cycle)return s;const remaining=Math.max(0,s.cycle.remainingMs-deltaMs);if(remaining>0)return{...s,cycle:{...s.cycle,remainingMs:remaining}};if(s.workshopOutput.butter+s.workshopOutput.cheese>=outCaps[s.workshopLevel]!)return{...s,cycle:{...s.cycle,remainingMs:0}};return{...s,workshopOutput:{...s.workshopOutput,[s.cycle.recipe]:s.workshopOutput[s.cycle.recipe]+1},cycle:null}}
export function cancelDairyCycle(s:DairyState,barn:ResourceAmounts){if(!s.cycle)return{s,barn};const room=capacities[s.workshopLevel]!-s.workshopInput,returned=Math.min(room,s.cycle.reservedMilk);return{s:{...s,workshopInput:s.workshopInput+returned,cycle:null},barn:{...barn,milk:barn.milk+s.cycle.reservedMilk-returned}}}
export const getProtectedMilkAmount=(market:number,contract:number,base=6)=>Math.max(0,Math.floor(market)+Math.floor(contract)+Math.floor(base));
export const canSendMilkToWorkshop=(barnMilk:number,input:number,level:DairyLevel,protectedAmount:number)=>barnMilk>protectedAmount&&input<capacities[level]!;
export const getDairyInputBatch=(available:number,input:number,level:DairyLevel,recipeId:DairyRecipe,capacity:number)=>Math.max(0,Math.min(available,capacities[level]!-input,capacity)-Math.min(available,capacities[level]!-input,capacity)%recipe(recipeId).milk);
export const getDairyOutputBatch=(available:number,capacity:number)=>Math.max(0,Math.min(Math.floor(available),Math.floor(capacity)));
export type DairyTask="feed-emergency"|"collect-milk"|"feed"|"wait";
export function selectDairyTask(input:{hired:boolean;hayRack:number;milkTank:number;hayAvailable:number}) :DairyTask {if(!input.hired)return"wait";if(input.hayRack<=5&&input.hayAvailable>0)return"feed-emergency";if(input.milkTank>=5)return"collect-milk";if(input.hayRack<18&&input.hayAvailable>0)return"feed";return"wait"}
export const emptyDairyCargo=():ResourceAmounts=>emptyResourceAmounts();
