import type { GameState } from "../state/GameState";
import type { Rect, SignDefinition } from "./signLayout";
import type { WorkerRoleId } from "./workforce";
export type FacilityId = "barn"|"delivery-zone"|"market"|"cash-pickup"|"contract-board"|"contract-dock"|"harvest-speed-upgrade"|"carry-capacity-upgrade"|"wheat-worker-board"|"wheat-harvest-hire"|"wheat-transport-hire"|"wheat-field-crate"|"east-land-gate"|"corn-field"|"corn-worker-board"|"corn-harvest-hire"|"corn-transport-hire"|"corn-field-crate"|"south-land-gate"|"chicken-coop"|"feed-trough"|"egg-storage"|"poultry-worker-board"|"poultry-caretaker-hire"|"training-lodge"|"collection-hub"|"wheat-collection-box"|"corn-collection-box"|"egg-collection-box"|"processing-intake";
export interface FacilityDefinition { id:FacilityId; worldBounds:Rect; landmarkPoint:{x:number;y:number}; signGroupId?:string; signPriority:number; label:string }
const f=(id:FacilityId,x:number,y:number,w:number,h:number,label:string,group?:string,priority=10):FacilityDefinition=>({id,worldBounds:{x,y,width:w,height:h},landmarkPoint:{x:x+w/2,y:y+h/2},signGroupId:group,signPriority:priority,label});
export const FACILITIES:readonly FacilityDefinition[]=[f("barn",1320,360,310,250,"倉庫"),f("delivery-zone",1325,435,250,250,"納品場所"),f("market",1650,350,400,350,"市場"),f("cash-pickup",1670,630,180,180,"売上台"),f("contract-board",1550,815,160,155,"出荷契約"),f("contract-dock",1255,775,240,120,"契約出荷場"),f("harvest-speed-upgrade",1720,990,180,180,"収穫速度","farm"),f("carry-capacity-upgrade",1178,608,164,164,"運搬かご","farm"),f("wheat-worker-board",1690,1130,300,170,"農場管理","farm",100),f("wheat-harvest-hire",1658,1158,164,164,"麦の収穫スタッフ","farm"),f("wheat-transport-hire",1828,1158,164,164,"麦の運搬スタッフ","farm"),f("wheat-field-crate",1015,695,190,190,"麦の集荷箱"),f("east-land-gate",2020,545,160,210,"東農地入口"),f("corn-field",2180,230,680,690,"とうもろこし畑"),f("corn-worker-board",2080,840,380,100,"東農地管理","east",90),f("corn-harvest-hire",2098,898,164,164,"とうもろこし収穫スタッフ","east"),f("corn-transport-hire",2238,898,164,164,"とうもろこし運搬スタッフ","east"),f("corn-field-crate",2390,820,180,160,"とうもろこし集荷箱","east"),f("south-land-gate",1050,1370,200,120,"鶏小屋入口"),f("chicken-coop",650,1400,1000,450,"鶏小屋"),f("feed-trough",898,1528,164,164,"餌箱","poultry"),f("egg-storage",1308,1538,164,164,"卵置き場","poultry"),f("poultry-worker-board",1420,1390,270,100,"鶏小屋管理","poultry",90),f("poultry-caretaker-hire",1508,1448,164,164,"飼育スタッフ","poultry"),f("training-lodge",55,655,285,210,"研修小屋","training",110),f("collection-hub",1730,1430,250,190,"集配所","collection",105),f("wheat-collection-box",710,690,130,110,"麦畑集配ボックス","collection"),f("corn-collection-box",2600,850,130,110,"東農地集配ボックス","collection"),f("egg-collection-box",1180,1710,130,110,"鶏小屋集配ボックス","collection"),f("processing-intake",1990,1460,130,110,"加工場受入ボックス","collection")];
export type InteractionId="upgrade-harvest-speed"|"upgrade-carry-capacity"|"hire-wheat-harvester"|"hire-wheat-transporter"|"purchase-east-land"|"hire-corn-harvester"|"hire-corn-transporter"|"purchase-south-coop"|"hire-poultry-caretaker"|"open-operations"|"open-contracts"|"deliver-contract"|"transfer-feed"|"collect-eggs"|"collect-corn-crate"|"collect-wheat-crate"|"deliver-barn"|"collect-cash";
export interface InteractionDefinition{id:InteractionId;facilityId:FacilityId;kind:"hold-purchase"|"hold-hire"|"automatic-transfer"|"open-panel"|"collect"|"deliver";center:{x:number;y:number};radius:number;visibleRadius:number;title:string;shortLabel:string;workerRole?:WorkerRoleId;holdDurationMs?:number}
const i=(id:InteractionId,facilityId:FacilityId,kind:InteractionDefinition["kind"],x:number,y:number,radius:number,title:string,shortLabel:string,workerRole?:WorkerRoleId,holdDurationMs?:number):InteractionDefinition=>({id,facilityId,kind,center:{x,y},radius,visibleRadius:radius,title,shortLabel,workerRole,holdDurationMs});
export const INTERACTIONS:readonly InteractionDefinition[]=[i("upgrade-harvest-speed","harvest-speed-upgrade","hold-purchase",1810,1080,90,"収穫速度を上げる","速度",undefined,900),i("upgrade-carry-capacity","carry-capacity-upgrade","hold-purchase",1260,690,82,"運搬かごを大きくする","運搬かご",undefined,900),i("hire-wheat-harvester","wheat-harvest-hire","hold-hire",1740,1240,82,"麦の収穫スタッフ","収穫", "wheat-harvester",900),i("hire-wheat-transporter","wheat-transport-hire","hold-hire",1910,1240,82,"麦の運搬スタッフ","運搬","wheat-transporter",900),i("purchase-east-land","east-land-gate","hold-purchase",2050,650,105,"東農地を購入","東農地",undefined,1200),i("hire-corn-harvester","corn-harvest-hire","hold-hire",2180,980,82,"とうもろこし収穫スタッフ","収穫","corn-harvester",900),i("hire-corn-transporter","corn-transport-hire","hold-hire",2320,980,82,"とうもろこし運搬スタッフ","運搬","corn-transporter",900),i("purchase-south-coop","south-land-gate","hold-purchase",1150,1480,105,"鶏小屋を購入","鶏小屋",undefined,1200),i("hire-poultry-caretaker","poultry-caretaker-hire","hold-hire",1590,1530,82,"飼育スタッフ","飼育","poultry-caretaker",900),i("open-operations","training-lodge","open-panel",350,780,96,"研修小屋を開く","スタッフ管理"),i("open-contracts","contract-board","open-panel",1630,940,125,"契約を見る","契約"),i("deliver-contract","contract-dock","deliver",1370,830,115,"契約へ納品","出荷"),i("transfer-feed","feed-trough","automatic-transfer",980,1610,82,"餌箱へ入れる","餌"),i("collect-eggs","egg-storage","collect",1390,1620,82,"たまごを受け取る","卵"),i("collect-corn-crate","corn-field-crate","collect",2480,900,82,"とうもろこしを受け取る","集荷"),i("collect-wheat-crate","wheat-field-crate","collect",1110,790,95,"麦を受け取る","集荷"),i("deliver-barn","delivery-zone","deliver",1450,560,125,"倉庫へ納品","納品"),i("collect-cash","cash-pickup","collect",1760,720,95,"売上を受け取る","売上")];
export const facilityById=(id:FacilityId)=>FACILITIES.find(facility=>facility.id===id);
export const normalizeFacilityId=(id:string|null):FacilityId|null=>id==="operations-office"?"training-lodge":FACILITIES.some(facility=>facility.id===id)?id as FacilityId:null;
export const interactionById=(id:InteractionId)=>INTERACTIONS.find(interaction=>interaction.id===id);
export const isInteractionReachable=(interaction:InteractionDefinition,state:Pick<GameState,"landExpansion">):boolean=>interaction.id.startsWith("hire-corn")?state.landExpansion.eastCornFieldUnlocked:interaction.id==="hire-poultry-caretaker"?state.landExpansion.southChickenCoopUnlocked:true;
export const PRODUCTION_SIGNS:readonly SignDefinition[]=[{id:"farm-management",facilityId:"wheat-worker-board",priority:100,preferredAnchors:["west","south-west","north-west"],facilityBounds:{x:1690,y:1130,width:300,height:170},width:148,height:66},{id:"east-management",facilityId:"corn-worker-board",priority:90,preferredAnchors:["south","east","north"],facilityBounds:{x:2080,y:840,width:380,height:100},width:148,height:66},{id:"poultry-management",facilityId:"poultry-worker-board",priority:90,preferredAnchors:["north-east","east","south-east"],facilityBounds:{x:1420,y:1390,width:270,height:100},width:148,height:66},{id:"training-lodge",facilityId:"training-lodge",priority:110,preferredAnchors:["east","south-east"],facilityBounds:{x:55,y:655,width:285,height:210},width:148,height:66}];
