import type { ResourceAmounts,ResourceId } from "../config/resourceDefinitions";
import { RESOURCE_IDS } from "../config/resourceDefinitions";
import { RECIPES, getBufferRemainingCapacity, type MachineId, type ProcessingMachineState, type RecipeId } from "./processing";
export type ProcessingWorkerRole="millOperator"|"baker";
export interface ProcessingWorkerState{hired:boolean;level:0|1|2|3;carriedResource:ResourceId|null;carriedAmount:number;publicStatus:string}
const allowed:Record<ProcessingWorkerRole,readonly ResourceId[]>={millOperator:["wheat","corn","flour","cornmeal"],baker:["flour","cornmeal","egg","bread","cornbread"]};
export const isWorkerResourceAllowed=(role:ProcessingWorkerRole,r:ResourceId|null)=>r===null||allowed[role].includes(r);
export const getProcessingWorkerCapacity=(role:ProcessingWorkerRole,level:number)=>role==="millOperator"?[0,8,12,16][level]??0:[0,6,9,12][level]??0;
export function hireProcessingWorker(role:ProcessingWorkerRole,worker:ProcessingWorkerState,walletCoins:number){const cost=role==="millOperator"?450:700;if(worker.hired)return{ok:false as const,worker,walletCoins,reason:"duplicate"};if(walletCoins<cost)return{ok:false as const,worker,walletCoins,reason:"coins"};return{ok:true as const,worker:{...worker,hired:true,level:1 as const,publicStatus:"待機中"},walletCoins:walletCoins-cost,prioritySave:true as const}}
export function trainProcessingWorker(role:ProcessingWorkerRole,worker:ProcessingWorkerState,walletCoins:number){if(!worker.hired||worker.level===0)return{ok:false as const,worker,walletCoins,reason:"not-hired"};if(worker.level===3)return{ok:false as const,worker,walletCoins,reason:"maximum"};const costs=role==="millOperator"?[0,420,900]:[0,650,1300];const cost=costs[worker.level]!;if(walletCoins<cost)return{ok:false as const,worker,walletCoins,reason:"coins"};return{ok:true as const,worker:{...worker,level:(worker.level+1) as 2|3},walletCoins:walletCoins-cost,prioritySave:true as const}}
export function chooseBlockingIngredient(required:ResourceAmounts,input:ResourceAmounts):ResourceId|null{let best:ResourceId|null=null,bestMissing=0;for(const r of ["flour","cornmeal","egg"] as const){const missing=Math.max(0,required[r]-input[r]);if(missing>bestMissing){best=r;bestMissing=missing}}return best}
export const getWorkerBatchAmount=(available:number,needed:number,capacity:number)=>Math.max(0,Math.min(Math.floor(available),Math.floor(needed),capacity));
export interface ProcessingSupplyResult{changed:boolean;machine:ProcessingMachineState;barn:ResourceAmounts;breakdown:Partial<Record<ResourceId,number>>;totalMoved:number;reason?:"not-built"|"no-recipe"|"unavailable"|"full"}
const recipeOrder:Record<MachineId,readonly RecipeId[]>={"grain-mill":["mill-flour","mill-cornmeal"],bakery:["bakery-bread","bakery-cornbread"]};
export function selectSupplyRecipe(machineId:MachineId,machine:ProcessingMachineState):RecipeId|null{if(machine.selectedMode!=="auto")return RECIPES[machine.selectedMode]?.machine===machineId?machine.selectedMode:null;return recipeOrder[machineId].find(id=>RESOURCE_IDS.every(r=>machine.input.amounts[r]>=RECIPES[id].inputs[r]))??recipeOrder[machineId][0]??null;}
export function refillOneProcessingCycleFromBarn(machineId:MachineId,machine:ProcessingMachineState,barn:ResourceAmounts):ProcessingSupplyResult{if(!machine.built)return{changed:false,machine,barn,breakdown:{},totalMoved:0,reason:"not-built"};const id=selectSupplyRecipe(machineId,machine);if(!id)return{changed:false,machine,barn,breakdown:{},totalMoved:0,reason:"no-recipe"};const needs=RECIPES[id].inputs,missing=RESOURCE_IDS.map(r=>[r,Math.max(0,needs[r]-machine.input.amounts[r])] as const).filter(([,n])=>n>0);const total=missing.reduce((n,[,v])=>n+v,0);if(total===0)return{changed:false,machine,barn,breakdown:{},totalMoved:0,reason:"unavailable"};if(total>getBufferRemainingCapacity(machine.input))return{changed:false,machine,barn,breakdown:{},totalMoved:0,reason:"full"};if(missing.some(([r,n])=>barn[r]<n))return{changed:false,machine,barn,breakdown:{},totalMoved:0,reason:"unavailable"};const nextBarn={...barn},amounts={...machine.input.amounts},breakdown:Partial<Record<ResourceId,number>>={};for(const [r,n] of missing){nextBarn[r]-=n;amounts[r]+=n;breakdown[r]=n;}return{changed:true,machine:{...machine,input:{...machine.input,amounts}},barn:nextBarn,breakdown,totalMoved:total};}
export function moveProcessingOutputToBarn(machine:ProcessingMachineState,barn:ResourceAmounts):ProcessingSupplyResult{const amounts={...machine.output.amounts},nextBarn={...barn},breakdown:Partial<Record<ResourceId,number>>={};let total=0;for(const r of RESOURCE_IDS){const n=Math.max(0,Math.floor(amounts[r]));if(n){amounts[r]=0;nextBarn[r]+=n;breakdown[r]=n;total+=n;}}return{changed:total>0,machine:{...machine,output:{...machine.output,amounts}},barn:nextBarn,breakdown,totalMoved:total,...(!total?{reason:"unavailable" as const}:{})};}
