import { RESOURCE_IDS, emptyResourceAmounts, type ResourceAmounts } from "../config/resourceDefinitions";
import type { CarriedCargo } from "./resources";
import { getMachineDuration, RECIPES, type MachineId, type ProcessingMachineState, type RecipeId } from "./processing";

export interface RecipePlan { targetCyclesByRecipe: Partial<Record<RecipeId, number>> }
export type ProcessingSupplyMode="cargo-first"|"barn-first"|"cargo-only"|"barn-only";
export type ProcessingBlockedReason="missing-input"|"wrong-mix-full-input"|"output-full"|"stopped"|"not-built"|"plan-zero"|null;
export interface ProcessingBufferDiagnosis {target:ResourceAmounts;current:ResourceAmounts;reserved:ResourceAmounts;deficit:ResourceAmounts;excess:ResourceAmounts;capacity:number;freeCapacity:number;canStart:boolean;blockedReason:ProcessingBlockedReason}
export interface ProcessingTransferResult {changed:boolean;machine:ProcessingMachineState;cargo?:CarriedCargo;barn?:ResourceAmounts;moved:ResourceAmounts;returned:ResourceAmounts;remainingDeficit:ResourceAmounts;totalMoved:number}
export interface RecipePlanCard { recipeId:RecipeId; name:string; inputs:ResourceAmounts; outputs:ResourceAmounts; baseDurationMs:number; currentDurationMs:number; targetCycles:number; craftableCycles:number; cargo:ResourceAmounts; barn:ResourceAmounts; machineInput:ResourceAmounts; missingInputs:ResourceAmounts }
export interface ProcessingPlanViewModel { machineId:MachineId; recipeCards:RecipePlanCard[]; targetInputs:ResourceAmounts; targetInputTotal:number; inputCapacity:number; remainingPlanCapacity:number; valid:boolean; validationMessage:string|null }
export interface SetRecipeTargetResult { accepted:boolean; plan:RecipePlan; maximumCycles:number; message:string|null }

const recipesFor=(machineId:MachineId)=>Object.values(RECIPES).filter(recipe=>recipe.machine===machineId);
const cycles=(value:number|undefined)=>Number.isFinite(value)?Math.max(0,Math.min(10,Math.trunc(value??0))):0;
export function calculateRecipePlanTargets(machineId:MachineId,plan:RecipePlan):ResourceAmounts{const result=emptyResourceAmounts();for(const recipe of recipesFor(machineId)){const count=cycles(plan.targetCyclesByRecipe[recipe.id]);for(const id of RESOURCE_IDS)result[id]+=recipe.inputs[id]*count;}return result;}
export function getMaximumCyclesForRecipe(machineId:MachineId,recipeId:RecipeId,plan:RecipePlan,inputCapacity:number):number{const recipe=RECIPES[recipeId];if(recipe.machine!==machineId)return 0;const without={targetCyclesByRecipe:{...plan.targetCyclesByRecipe,[recipeId]:0}};const used=RESOURCE_IDS.reduce((sum,id)=>sum+calculateRecipePlanTargets(machineId,without)[id],0);const perCycle=RESOURCE_IDS.reduce((sum,id)=>sum+recipe.inputs[id],0);return Math.max(0,Math.min(10,Math.floor((inputCapacity-used)/perCycle)));}
export function setRecipeTargetCycles(machineId:MachineId,recipeId:RecipeId,value:number,plan:RecipePlan,inputCapacity:number):SetRecipeTargetResult{const maximumCycles=getMaximumCyclesForRecipe(machineId,recipeId,plan,inputCapacity),requested=cycles(value);if(requested>maximumCycles)return{accepted:false,plan:{targetCyclesByRecipe:{...plan.targetCyclesByRecipe}},maximumCycles,message:`入力庫容量${inputCapacity}を超えます`};return{accepted:true,plan:{targetCyclesByRecipe:{...plan.targetCyclesByRecipe,[recipeId]:requested}},maximumCycles,message:null};}
export function getCraftableCycles(recipeId:RecipeId,cargo:ResourceAmounts,barn:ResourceAmounts,machineInput:ResourceAmounts,includeBarn=true):number{const recipe=RECIPES[recipeId];let result=Number.POSITIVE_INFINITY;for(const id of RESOURCE_IDS)if(recipe.inputs[id]>0)result=Math.min(result,Math.floor((cargo[id]+machineInput[id]+(includeBarn?barn[id]:0))/recipe.inputs[id]));return Number.isFinite(result)?Math.max(0,result):0;}
export function createProcessingPlanViewModel(machineId:MachineId,machine:ProcessingMachineState,plan:RecipePlan,cargo:ResourceAmounts,barn:ResourceAmounts,includeBarn=true):ProcessingPlanViewModel{const targetInputs=calculateRecipePlanTargets(machineId,plan),targetInputTotal=RESOURCE_IDS.reduce((sum,id)=>sum+targetInputs[id],0),valid=targetInputTotal<=machine.input.capacity;return{machineId,targetInputs,targetInputTotal,inputCapacity:machine.input.capacity,remainingPlanCapacity:Math.max(0,machine.input.capacity-targetInputTotal),valid,validationMessage:valid?null:`入力庫容量${machine.input.capacity}を超えます`,recipeCards:recipesFor(machineId).map(recipe=>{const targetCycles=cycles(plan.targetCyclesByRecipe[recipe.id]),missingInputs=emptyResourceAmounts();for(const id of RESOURCE_IDS)missingInputs[id]=Math.max(0,recipe.inputs[id]*targetCycles-machine.input.amounts[id]);return{recipeId:recipe.id,name:recipe.publicName,inputs:{...recipe.inputs},outputs:{...recipe.outputs},baseDurationMs:recipe.baseDurationMs,currentDurationMs:getMachineDuration(recipe.id,machine.level),targetCycles,craftableCycles:getCraftableCycles(recipe.id,cargo,barn,machine.input.amounts,includeBarn),cargo:{...cargo},barn:{...barn},machineInput:{...machine.input.amounts},missingInputs};})};}

const sum=(a:ResourceAmounts)=>RESOURCE_IDS.reduce((n,id)=>n+a[id],0);
const zero=()=>emptyResourceAmounts();
export function selectPlannedRecipe(machineId:MachineId,machine:ProcessingMachineState,plan:RecipePlan,roundRobin=0):RecipeId|null{const candidates=recipesFor(machineId).filter(r=>(plan.targetCyclesByRecipe[r.id]??0)>0);if(!candidates.length)return null;if(machine.selectedMode!=="auto")return candidates.some(r=>r.id===machine.selectedMode)?machine.selectedMode:null;for(let n=0;n<candidates.length;n++){const recipe=candidates[(roundRobin+n)%candidates.length]!;if(RESOURCE_IDS.every(id=>machine.input.amounts[id]>=recipe.inputs[id]))return recipe.id;}return candidates[roundRobin%candidates.length]!.id;}
export function diagnoseProcessingBuffer(machineId:MachineId,machine:ProcessingMachineState,plan:RecipePlan):ProcessingBufferDiagnosis{const target=calculateRecipePlanTargets(machineId,plan),current={...machine.input.amounts},reserved=machine.activeCycle?{...machine.activeCycle.reservedInputs}:zero(),deficit=zero(),excess=zero();for(const id of RESOURCE_IDS){deficit[id]=Math.max(0,target[id]-current[id]);excess[id]=Math.max(0,current[id]-target[id]);}const selected=selectPlannedRecipe(machineId,machine,plan),canStart=selected!==null&&RESOURCE_IDS.every(id=>current[id]>=RECIPES[selected].inputs[id]);const freeCapacity=Math.max(0,machine.input.capacity-sum(current));let blockedReason:ProcessingBlockedReason=null;if(!machine.built)blockedReason="not-built";else if(!machine.enabled)blockedReason="stopped";else if(sum(target)===0)blockedReason="plan-zero";else if(machine.activeCycle?.remainingMs===0||(!machine.activeCycle&&machine.output.capacity-sum(machine.output.amounts)<=0))blockedReason="output-full";else if(!machine.activeCycle&&!canStart)blockedReason=freeCapacity===0&&sum(deficit)>0?"wrong-mix-full-input":"missing-input";return{target,current,reserved,deficit,excess,capacity:machine.input.capacity,freeCapacity,canStart:canStart||machine.activeCycle!==null,blockedReason};}
function transfer(machineId:MachineId,machine:ProcessingMachineState,plan:RecipePlan,source:ResourceAmounts,limit=Infinity){const diagnosis=diagnoseProcessingBuffer(machineId,machine,plan),amounts={...machine.input.amounts},nextSource={...source},moved=zero();let remaining=Math.max(0,Math.floor(limit));for(const id of RESOURCE_IDS){const n=Math.min(diagnosis.deficit[id],nextSource[id],remaining,Math.max(0,machine.input.capacity-sum(amounts)));if(n>0){amounts[id]+=n;nextSource[id]-=n;moved[id]=n;remaining-=n;}}const nextMachine={...machine,input:{...machine.input,amounts}},remainingDeficit=diagnoseProcessingBuffer(machineId,nextMachine,plan).deficit;return{nextMachine,nextSource,moved,remainingDeficit,totalMoved:sum(moved)};}
export function transferCargoToProcessingTargets(machineId:MachineId,machine:ProcessingMachineState,plan:RecipePlan,cargo:CarriedCargo,limit=Infinity):ProcessingTransferResult{const r=transfer(machineId,machine,plan,cargo.amounts,limit);return{changed:r.totalMoved>0,machine:r.nextMachine,cargo:{...cargo,amounts:r.nextSource},moved:r.moved,returned:zero(),remainingDeficit:r.remainingDeficit,totalMoved:r.totalMoved};}
export function transferBarnToProcessingTargets(machineId:MachineId,machine:ProcessingMachineState,plan:RecipePlan,barn:ResourceAmounts,limit=Infinity):ProcessingTransferResult{const r=transfer(machineId,machine,plan,barn,limit);return{changed:r.totalMoved>0,machine:r.nextMachine,barn:r.nextSource,moved:r.moved,returned:zero(),remainingDeficit:r.remainingDeficit,totalMoved:r.totalMoved};}
export function returnProcessingExcessToBarn(machineId:MachineId,machine:ProcessingMachineState,plan:RecipePlan,barn:ResourceAmounts,limit=Infinity):ProcessingTransferResult{const diagnosis=diagnoseProcessingBuffer(machineId,machine,plan),amounts={...machine.input.amounts},nextBarn={...barn},returned=zero();let remaining=Math.max(0,Math.floor(limit));for(const id of RESOURCE_IDS){const n=Math.min(diagnosis.excess[id],remaining);amounts[id]-=n;nextBarn[id]+=n;returned[id]=n;remaining-=n;}const nextMachine={...machine,input:{...machine.input,amounts}},d=diagnoseProcessingBuffer(machineId,nextMachine,plan);return{changed:sum(returned)>0,machine:nextMachine,barn:nextBarn,moved:zero(),returned,remainingDeficit:d.deficit,totalMoved:sum(returned)};}
export function emptyProcessingInputToBarn(machineId:MachineId,machine:ProcessingMachineState,plan:RecipePlan,barn:ResourceAmounts):ProcessingTransferResult{const amounts={...machine.input.amounts},nextBarn={...barn},returned=zero();for(const id of RESOURCE_IDS){returned[id]=amounts[id];nextBarn[id]+=amounts[id];amounts[id]=0;}const nextMachine={...machine,input:{...machine.input,amounts}};return{changed:sum(returned)>0,machine:nextMachine,barn:nextBarn,moved:zero(),returned,remainingDeficit:diagnoseProcessingBuffer(machineId,nextMachine,plan).deficit,totalMoved:sum(returned)};}
export function rebalanceProcessingInput(machineId:MachineId,machine:ProcessingMachineState,plan:RecipePlan,cargo:CarriedCargo,barn:ResourceAmounts,mode:ProcessingSupplyMode):ProcessingTransferResult{const returned=returnProcessingExcessToBarn(machineId,machine,plan,barn),sources=mode.startsWith("cargo")?["cargo",...(mode==="cargo-first"?["barn"]:[])]:["barn",...(mode==="barn-first"?["cargo"]:[])];let nextMachine=returned.machine,nextBarn=returned.barn!,nextCargo=cargo,moved=zero();for(const source of sources){const r=source==="cargo"?transferCargoToProcessingTargets(machineId,nextMachine,plan,nextCargo):transferBarnToProcessingTargets(machineId,nextMachine,plan,nextBarn);nextMachine=r.machine;if(r.cargo)nextCargo=r.cargo;if(r.barn)nextBarn=r.barn;for(const id of RESOURCE_IDS)moved[id]+=r.moved[id];}const totalMoved=sum(moved)+sum(returned.returned);return{changed:totalMoved>0,machine:nextMachine,cargo:nextCargo,barn:nextBarn,moved,returned:returned.returned,remainingDeficit:diagnoseProcessingBuffer(machineId,nextMachine,plan).deficit,totalMoved};}

export const DEFAULT_PROCESSING_PLANS:Readonly<Record<MachineId,RecipePlan>>={"grain-mill":{targetCyclesByRecipe:{"mill-flour":6,"mill-cornmeal":6}},bakery:{targetCyclesByRecipe:{"bakery-bread":3,"bakery-cornbread":3}}};
