import {describe,expect,it} from "vitest";
import {emptyResourceAmounts} from "../config/resourceDefinitions";
import {createMachine,startProductionCycle,type ProcessingMachineState} from "./processing";
import {diagnoseProcessingBuffer,emptyProcessingInputToBarn,rebalanceProcessingInput,returnProcessingExcessToBarn,selectPlannedRecipe,transferBarnToProcessingTargets,transferCargoToProcessingTargets,type RecipePlan} from "./processingPlan";

const cargo=(values:Partial<ReturnType<typeof emptyResourceAmounts>>)=>({amounts:{...emptyResourceAmounts(),...values},capacity:24});
const barn=(values:Partial<ReturnType<typeof emptyResourceAmounts>>)=>({...emptyResourceAmounts(),...values});

describe("smart processing input",()=>{
  it("moves an entire cargo deficit without exceeding the target",()=>{const machine={...createMachine("grain-mill"),built:true,level:1 as const},plan:RecipePlan={targetCyclesByRecipe:{"mill-flour":4}};const result=transferCargoToProcessingTargets("grain-mill",machine,plan,cargo({wheat:20}));expect(result.moved.wheat).toBe(8);expect(result.machine.input.amounts.wheat).toBe(8);expect(result.cargo?.amounts.wheat).toBe(12);expect(result.remainingDeficit.wheat).toBe(0);});
  it("allows a partial barn fill and reports the exact deficit",()=>{const machine={...createMachine("bakery"),built:true,level:1 as const},plan:RecipePlan={targetCyclesByRecipe:{"bakery-bread":4}};const result=transferBarnToProcessingTargets("bakery",machine,plan,barn({flour:3,egg:2}));expect(result.moved).toMatchObject({flour:3,egg:2});expect(result.remainingDeficit).toMatchObject({flour:1,egg:2});});
  it("recovers the bakery wrong-mix deadlock without touching reserved inputs",()=>{let machine:ProcessingMachineState={...createMachine("bakery"),built:true,level:1,input:{amounts:barn({flour:18}),capacity:18}};const plan:RecipePlan={targetCyclesByRecipe:{"bakery-bread":4}};const result=rebalanceProcessingInput("bakery",machine,plan,cargo({}),barn({egg:4}),"barn-only");expect(result.returned.flour).toBe(14);expect(result.moved.egg).toBe(4);expect(result.barn).toMatchObject({flour:14,egg:0});machine=startProductionCycle(result.machine,"bakery",["bakery-bread"]).machine;expect(machine.activeCycle?.recipeId).toBe("bakery-bread");expect(machine.activeCycle?.reservedInputs).toMatchObject({flour:1,egg:1});});
  it("recovers the mill wrong-mix deadlock and preserves all resources",()=>{const machine={...createMachine("grain-mill"),built:true,level:1 as const,input:{amounts:barn({corn:24}),capacity:24}},plan:RecipePlan={targetCyclesByRecipe:{"mill-flour":4}};const before=machine.input.amounts.corn+8,result=rebalanceProcessingInput("grain-mill",machine,plan,cargo({}),barn({wheat:8}),"barn-only");expect(result.machine.input.amounts).toMatchObject({corn:0,wheat:8});expect(result.barn).toMatchObject({corn:24,wheat:0});expect(result.machine.input.amounts.corn+result.machine.input.amounts.wheat+result.barn!.corn+result.barn!.wheat).toBe(before);});
  it("diagnoses all distinct blocking states",()=>{const plan:RecipePlan={targetCyclesByRecipe:{"bakery-bread":4}},base={...createMachine("bakery"),built:true,level:1 as const};expect(diagnoseProcessingBuffer("bakery",createMachine("bakery"),plan).blockedReason).toBe("not-built");expect(diagnoseProcessingBuffer("bakery",{...base,enabled:false},plan).blockedReason).toBe("stopped");expect(diagnoseProcessingBuffer("bakery",base,{targetCyclesByRecipe:{}}).blockedReason).toBe("plan-zero");expect(diagnoseProcessingBuffer("bakery",base,plan).blockedReason).toBe("missing-input");expect(diagnoseProcessingBuffer("bakery",{...base,input:{amounts:barn({flour:18}),capacity:18}},plan).blockedReason).toBe("wrong-mix-full-input");expect(diagnoseProcessingBuffer("bakery",{...base,output:{amounts:barn({bread:12}),capacity:12}},plan).blockedReason).toBe("output-full");});
  it("returns excess or all waiting input and selects only planned recipes",()=>{const machine={...createMachine("grain-mill"),built:true,level:1 as const,input:{amounts:barn({wheat:10,corn:2}),capacity:24}},plan:RecipePlan={targetCyclesByRecipe:{"mill-flour":4,"mill-cornmeal":0}};expect(selectPlannedRecipe("grain-mill",machine,plan)).toBe("mill-flour");const excess=returnProcessingExcessToBarn("grain-mill",machine,plan,barn({}));expect(excess.returned).toMatchObject({wheat:2,corn:2});const emptied=emptyProcessingInputToBarn("grain-mill",excess.machine,plan,excess.barn!);expect(emptied.machine.input.amounts.wheat).toBe(0);expect(emptied.barn?.wheat).toBe(10);});
});
