import { RESOURCE_IDS, emptyResourceAmounts, type ResourceAmounts } from "../config/resourceDefinitions";
import { getMachineDuration, RECIPES, type MachineId, type ProcessingMachineState, type RecipeId } from "./processing";

export interface RecipePlan { targetCyclesByRecipe: Partial<Record<RecipeId, number>> }
export interface RecipePlanCard { recipeId:RecipeId; name:string; inputs:ResourceAmounts; outputs:ResourceAmounts; baseDurationMs:number; currentDurationMs:number; targetCycles:number; craftableCycles:number; cargo:ResourceAmounts; barn:ResourceAmounts; machineInput:ResourceAmounts; missingInputs:ResourceAmounts }
export interface ProcessingPlanViewModel { machineId:MachineId; recipeCards:RecipePlanCard[]; targetInputs:ResourceAmounts; targetInputTotal:number; inputCapacity:number; remainingPlanCapacity:number; valid:boolean; validationMessage:string|null }
export interface SetRecipeTargetResult { accepted:boolean; plan:RecipePlan; maximumCycles:number; message:string|null }

const recipesFor=(machineId:MachineId)=>Object.values(RECIPES).filter(recipe=>recipe.machine===machineId);
const cycles=(value:number|undefined)=>Number.isFinite(value)?Math.max(0,Math.min(10,Math.trunc(value??0))):0;
export function calculateRecipePlanTargets(machineId:MachineId,plan:RecipePlan):ResourceAmounts{const result=emptyResourceAmounts();for(const recipe of recipesFor(machineId)){const count=cycles(plan.targetCyclesByRecipe[recipe.id]);for(const id of RESOURCE_IDS)result[id]+=recipe.inputs[id]*count;}return result;}
export function getMaximumCyclesForRecipe(machineId:MachineId,recipeId:RecipeId,plan:RecipePlan,inputCapacity:number):number{const recipe=RECIPES[recipeId];if(recipe.machine!==machineId)return 0;const without={targetCyclesByRecipe:{...plan.targetCyclesByRecipe,[recipeId]:0}};const used=RESOURCE_IDS.reduce((sum,id)=>sum+calculateRecipePlanTargets(machineId,without)[id],0);const perCycle=RESOURCE_IDS.reduce((sum,id)=>sum+recipe.inputs[id],0);return Math.max(0,Math.min(10,Math.floor((inputCapacity-used)/perCycle)));}
export function setRecipeTargetCycles(machineId:MachineId,recipeId:RecipeId,value:number,plan:RecipePlan,inputCapacity:number):SetRecipeTargetResult{const maximumCycles=getMaximumCyclesForRecipe(machineId,recipeId,plan,inputCapacity),requested=cycles(value);if(requested>maximumCycles)return{accepted:false,plan:{targetCyclesByRecipe:{...plan.targetCyclesByRecipe}},maximumCycles,message:`入力庫容量${inputCapacity}を超えます`};return{accepted:true,plan:{targetCyclesByRecipe:{...plan.targetCyclesByRecipe,[recipeId]:requested}},maximumCycles,message:null};}
export function getCraftableCycles(recipeId:RecipeId,cargo:ResourceAmounts,barn:ResourceAmounts,machineInput:ResourceAmounts,includeBarn=true):number{const recipe=RECIPES[recipeId];let result=Number.POSITIVE_INFINITY;for(const id of RESOURCE_IDS)if(recipe.inputs[id]>0)result=Math.min(result,Math.floor((cargo[id]+machineInput[id]+(includeBarn?barn[id]:0))/recipe.inputs[id]));return Number.isFinite(result)?Math.max(0,result):0;}
export function createProcessingPlanViewModel(machineId:MachineId,machine:ProcessingMachineState,plan:RecipePlan,cargo:ResourceAmounts,barn:ResourceAmounts,includeBarn=true):ProcessingPlanViewModel{const targetInputs=calculateRecipePlanTargets(machineId,plan),targetInputTotal=RESOURCE_IDS.reduce((sum,id)=>sum+targetInputs[id],0),valid=targetInputTotal<=machine.input.capacity;return{machineId,targetInputs,targetInputTotal,inputCapacity:machine.input.capacity,remainingPlanCapacity:Math.max(0,machine.input.capacity-targetInputTotal),valid,validationMessage:valid?null:`入力庫容量${machine.input.capacity}を超えます`,recipeCards:recipesFor(machineId).map(recipe=>{const targetCycles=cycles(plan.targetCyclesByRecipe[recipe.id]),missingInputs=emptyResourceAmounts();for(const id of RESOURCE_IDS)missingInputs[id]=Math.max(0,recipe.inputs[id]*targetCycles-machine.input.amounts[id]);return{recipeId:recipe.id,name:recipe.publicName,inputs:{...recipe.inputs},outputs:{...recipe.outputs},baseDurationMs:recipe.baseDurationMs,currentDurationMs:getMachineDuration(recipe.id,machine.level),targetCycles,craftableCycles:getCraftableCycles(recipe.id,cargo,barn,machine.input.amounts,includeBarn),cargo:{...cargo},barn:{...barn},machineInput:{...machine.input.amounts},missingInputs};})};}

export const DEFAULT_PROCESSING_PLANS:Readonly<Record<MachineId,RecipePlan>>={"grain-mill":{targetCyclesByRecipe:{"mill-flour":6,"mill-cornmeal":6}},bakery:{targetCyclesByRecipe:{"bakery-bread":3,"bakery-cornbread":3}}};
