import {describe,expect,it} from "vitest";
import {emptyResourceAmounts} from "../config/resourceDefinitions";
import {advanceProductionCycle,buildProcessingMachine,createMachine,purchaseProcessingYard,RECIPES,startProductionCycle,upgradeMachine} from "./processing";
import {chooseBlockingIngredient,getProcessingWorkerCapacity,hireProcessingWorker,isWorkerResourceAllowed,trainProcessingWorker} from "./processingWorkers";
import {chooseRecipeByDemand,chooseRoundRobin,getAvailableForRouting,getProtectedResource,getUnlockedResources,ROUTING_POLICY_IDS,scoreProductionDemand} from "./processingRouting";
describe("v0.9 processing",()=>{
 it("enforces exact construction progression without charging failures",()=>{const land={yardUnlocked:false,millBuilt:false,bakeryBuilt:false};expect(purchaseProcessingYard(land,900,false,true).walletCoins).toBe(900);const yard=purchaseProcessingYard(land,900,true,true);expect(yard.ok&&yard.walletCoins).toBe(100);if(!yard.ok)return;expect(buildProcessingMachine(yard.state,"grain-mill",349).walletCoins).toBe(349);const mill=buildProcessingMachine(yard.state,"grain-mill",1200);expect(mill.ok&&mill.walletCoins).toBe(850);if(!mill.ok)return;expect(buildProcessingMachine(mill.state,"bakery",850).ok).toBe(true)});
 it("atomically reserves and deterministically completes every recipe",()=>{for(const recipe of Object.values(RECIPES)){let machine=createMachine(recipe.machine);machine={...machine,built:true,level:1,selectedMode:recipe.id,input:{...machine.input,amounts:{...recipe.inputs}}};const start=startProductionCycle(machine,recipe.machine);expect(start.started).toBe(true);expect(start.machine.input.amounts).toEqual(emptyResourceAmounts());const done=advanceProductionCycle(start.machine,recipe.baseDurationMs);expect(done.completed).toBe(true);expect(done.machine.output.amounts).toEqual(recipe.outputs)}});
 it("preserves buffers and cycle on upgrade",()=>{const machine={...createMachine("grain-mill"),built:true,level:1 as const};const result=upgradeMachine(machine,"grain-mill",300);expect(result.ok&&result.state.level).toBe(2);expect(result.ok&&result.prioritySave).toBe(true)});
 it("supports all policies, reserves emergency feed and clamps availability",()=>{const barn={...emptyResourceAmounts(),corn:12};for(const policy of ROUTING_POLICY_IDS){const p=getProtectedResource("corn",policy,{feed:0,feedCapacity:6,activeContract:null,marketTarget:2,rawReserve:10,activeProduction:0});expect(p.chickenFeed).toBe(6);expect(getAvailableForRouting("corn",barn,p)).toBeGreaterThanOrEqual(0)}expect(getAvailableForRouting("corn",barn,{chickenFeed:0,activeContract:0,marketTarget:0,rawReserve:99,activeProduction:0,protectedTotal:99})).toBe(0)});
 it("unlocks processed market and contract goods with facilities",()=>{expect(getUnlockedResources({eastCornFieldUnlocked:true,southChickenCoopUnlocked:true},{millBuilt:true,bakeryBuilt:false})).toEqual(["wheat","corn","egg","flour","cornmeal"])});
 it("uses deterministic scoring and fair round robin",()=>{const demand=scoreProductionDemand({resource:"flour",contractNeed:2,marketNeed:1,bakeryNeed:1,currentBarn:0,machineOutput:0});expect(demand.score).toBe(285);expect(chooseRecipeByDemand([{recipeId:"mill-flour",demand}],0)).toBe("mill-flour");expect([0,1,2].map(i=>chooseRoundRobin(["wheat","corn","egg"],i).resource)).toEqual(["wheat","corn","egg"])});
 it("uses exact worker costs, capacities, cargo allowlists, and blocking ingredients",()=>{const worker={hired:false,level:0 as const,carriedResource:null,carriedAmount:0,publicStatus:"未雇用"};const hired=hireProcessingWorker("millOperator",worker,450);expect(hired.ok&&hired.walletCoins).toBe(0);if(!hired.ok)return;expect(trainProcessingWorker("millOperator",hired.worker,420).ok).toBe(true);expect(getProcessingWorkerCapacity("millOperator",3)).toBe(16);expect(isWorkerResourceAllowed("millOperator","bread")).toBe(false);expect(chooseBlockingIngredient({...emptyResourceAmounts(),flour:2,cornmeal:2,egg:2},{...emptyResourceAmounts(),flour:2,cornmeal:0,egg:1})).toBe("cornmeal")});
});
