import { RESOURCE_IDS, emptyResourceAmounts, type ResourceAmounts, type ResourceId } from "../config/resourceDefinitions";
import type { DeliveryContract } from "../contracts/contractTypes";
import type { RecipeId } from "./processing";
export type RoutingPolicyId="balanced"|"market-first"|"contract-first"|"processing-first";
export const ROUTING_POLICY_IDS:readonly RoutingPolicyId[]=["balanced","market-first","contract-first","processing-first"];
export interface ProtectedResourceBreakdown{chickenFeed:number;activeContract:number;marketTarget:number;rawReserve:number;activeProduction:number;protectedTotal:number}
export function getProtectedResource(resource:ResourceId,policy:RoutingPolicyId,input:{feed:number;feedCapacity:number;activeContract:DeliveryContract|null;marketTarget:number;rawReserve:number;activeProduction:number}):ProtectedResourceBreakdown{const chickenFeed=resource==="corn"?Math.max(0,input.feedCapacity-input.feed):0;const activeContract=input.activeContract?Math.max(0,input.activeContract.requirements[resource]-input.activeContract.delivered[resource]):0;const scale=policy==="processing-first"?0:policy==="contract-first"?.25:1;const marketTarget=Math.ceil(input.marketTarget*scale);const rawReserve=policy==="processing-first"?Math.min(4,input.rawReserve):policy==="market-first"?Math.ceil(input.rawReserve/2):input.rawReserve;const activeProduction=Math.max(0,input.activeProduction);const protectedTotal=Math.max(chickenFeed,activeContract,marketTarget,rawReserve)+activeProduction;return{chickenFeed,activeContract,marketTarget,rawReserve,activeProduction,protectedTotal}}
export const getAvailableForRouting=(resource:ResourceId,barn:ResourceAmounts,p:ProtectedResourceBreakdown)=>Math.max(0,Math.min(barn[resource],Math.floor(barn[resource]-p.protectedTotal)));
export const getUnlockedResources=(land:{eastCornFieldUnlocked:boolean;southChickenCoopUnlocked:boolean},processing:{millBuilt:boolean;bakeryBuilt:boolean}):ResourceId[]=>RESOURCE_IDS.filter(r=>r==="wheat"||(r==="corn"&&land.eastCornFieldUnlocked)||(r==="egg"&&land.southChickenCoopUnlocked)||(["flour","cornmeal"].includes(r)&&processing.millBuilt)||(["bread","cornbread"].includes(r)&&processing.bakeryBuilt));
export const getMarketRestockAvailability=(r:ResourceId,barn:ResourceAmounts,p:ProtectedResourceBreakdown,market:ResourceAmounts,capacity:ResourceAmounts)=>Math.min(getAvailableForRouting(r,barn,p),Math.max(0,capacity[r]-market[r]));
export function chooseRoundRobin(eligible:readonly ResourceId[],cursor:number):{resource:ResourceId|null;nextCursor:number}{if(!eligible.length)return{resource:null,nextCursor:cursor};const index=((cursor%eligible.length)+eligible.length)%eligible.length;return{resource:eligible[index]!,nextCursor:(index+1)%eligible.length}}
export interface ProductionDemand{resource:ResourceId;contractNeed:number;marketNeed:number;bakeryNeed:number;currentBarn:number;machineOutput:number;score:number}
export function scoreProductionDemand(d:Omit<ProductionDemand,"score">):ProductionDemand{return{...d,score:d.contractNeed*100+d.bakeryNeed*60+d.marketNeed*25-Math.max(0,d.currentBarn+d.machineOutput)*5}}
export function chooseRecipeByDemand(entries:readonly {recipeId:RecipeId;demand:ProductionDemand}[],roundRobin=0):RecipeId|null{if(!entries.length)return null;const best=Math.max(...entries.map(e=>e.demand.score));const tied=entries.filter(e=>e.demand.score===best).sort((a,b)=>a.recipeId.localeCompare(b.recipeId));return tied[((roundRobin%tied.length)+tied.length)%tied.length]!.recipeId}
export const defaultMarketTargets=():ResourceAmounts=>({...emptyResourceAmounts(),wheat:4,corn:4,egg:4,flour:3,cornmeal:3,bread:3,cornbread:2});
