import { RESOURCE_IDS, emptyResourceAmounts, type ResourceAmounts, type ResourceId } from "../config/resourceDefinitions";
import { addCargoOne, removeCargoOne, type CarriedCargo } from "./resources";

export type MachineId = "grain-mill" | "bakery";
export type RecipeId = "mill-flour" | "mill-cornmeal" | "bakery-bread" | "bakery-cornbread";
export type MachineLevel = 0 | 1 | 2 | 3;
export interface RecipeDefinition { id: RecipeId; machine: MachineId; publicName: string; inputs: ResourceAmounts; outputs: ResourceAmounts; baseDurationMs: number }
const amounts = (values: Partial<ResourceAmounts>): ResourceAmounts => ({ ...emptyResourceAmounts(), ...values });
export const RECIPES: Readonly<Record<RecipeId, RecipeDefinition>> = {
  "mill-flour": { id:"mill-flour", machine:"grain-mill", publicName:"小麦粉", inputs:amounts({wheat:2}), outputs:amounts({flour:1}), baseDurationMs:3500 },
  "mill-cornmeal": { id:"mill-cornmeal", machine:"grain-mill", publicName:"コーンミール", inputs:amounts({corn:2}), outputs:amounts({cornmeal:1}), baseDurationMs:4200 },
  "bakery-bread": { id:"bakery-bread", machine:"bakery", publicName:"パン", inputs:amounts({flour:1,egg:1}), outputs:amounts({bread:1}), baseDurationMs:5500 },
  "bakery-cornbread": { id:"bakery-cornbread", machine:"bakery", publicName:"コーンブレッド", inputs:amounts({flour:1,cornmeal:1,egg:1}), outputs:amounts({cornbread:1}), baseDurationMs:7500 },
};
export interface MachineBufferState { amounts: ResourceAmounts; capacity: number }
export interface ActiveProductionCycle { recipeId: RecipeId; remainingMs: number; durationMs: number; reservedInputs: ResourceAmounts }
export interface ProcessingMachineState { built:boolean; level:MachineLevel; enabled:boolean; selectedMode:"auto"|RecipeId; input:MachineBufferState; output:MachineBufferState; activeCycle:ActiveProductionCycle|null; completedCycles:number }
export interface ProcessingLandState { yardUnlocked:boolean; millBuilt:boolean; bakeryBuilt:boolean }
export const getBufferTotal=(b:MachineBufferState)=>RESOURCE_IDS.reduce((n,r)=>n+b.amounts[r],0);
export const getBufferRemainingCapacity=(b:MachineBufferState)=>Math.max(0,b.capacity-getBufferTotal(b));
export const canAddToBuffer=(b:MachineBufferState,r:ResourceId,amount=1)=>amount>=0&&Number.isInteger(amount)&&getBufferRemainingCapacity(b)>=amount&&b.amounts[r]>=0;
export function addBufferResourceOne(b:MachineBufferState,r:ResourceId):MachineBufferState{return canAddToBuffer(b,r)?{...b,amounts:{...b.amounts,[r]:b.amounts[r]+1}}:b}
export function removeBufferResourceOne(b:MachineBufferState,r:ResourceId):MachineBufferState{return b.amounts[r]>0?{...b,amounts:{...b.amounts,[r]:b.amounts[r]-1}}:b}
export const createMachine=(id:MachineId):ProcessingMachineState=>({built:false,level:0,enabled:true,selectedMode:"auto",input:{amounts:emptyResourceAmounts(),capacity:id==="grain-mill"?24:18},output:{amounts:emptyResourceAmounts(),capacity:id==="grain-mill"?16:12},activeCycle:null,completedCycles:0});
export type TransactionResult<T>={ok:true,state:T,walletCoins:number,prioritySave:true}|{ok:false,state:T,walletCoins:number,reason:string};
export function purchaseProcessingYard(land:ProcessingLandState,walletCoins:number,east:boolean,coop:boolean):TransactionResult<ProcessingLandState>{if(land.yardUnlocked)return{ok:false,state:land,walletCoins,reason:"duplicate"};if(!east||!coop)return{ok:false,state:land,walletCoins,reason:"prerequisite"};if(walletCoins<800)return{ok:false,state:land,walletCoins,reason:"coins"};return{ok:true,state:{...land,yardUnlocked:true},walletCoins:walletCoins-800,prioritySave:true}}
export function buildProcessingMachine(land:ProcessingLandState,id:MachineId,walletCoins:number):TransactionResult<ProcessingLandState>{const cost=id==="grain-mill"?350:850;const built=id==="grain-mill"?land.millBuilt:land.bakeryBuilt;const ready=land.yardUnlocked&&(id==="grain-mill"||land.millBuilt);if(built)return{ok:false,state:land,walletCoins,reason:"duplicate"};if(!ready)return{ok:false,state:land,walletCoins,reason:"prerequisite"};if(walletCoins<cost)return{ok:false,state:land,walletCoins,reason:"coins"};return{ok:true,state:{...land,[id==="grain-mill"?"millBuilt":"bakeryBuilt"]:true},walletCoins:walletCoins-cost,prioritySave:true}}
const speed=[0,1,.75,.55] as const;
export function startProductionCycle(machine:ProcessingMachineState,machineId:MachineId,autoOrder:readonly RecipeId[]=[]):{machine:ProcessingMachineState,started:boolean,reason?:string}{if(!machine.built)return{machine,started:false,reason:"not-built"};if(!machine.enabled)return{machine,started:false,reason:"disabled"};if(machine.activeCycle)return{machine,started:false,reason:"cycle-already-active"};const candidates=machine.selectedMode==="auto"?autoOrder:[machine.selectedMode];for(const id of candidates){const recipe=RECIPES[id];if(!recipe||recipe.machine!==machineId)continue;if(RESOURCE_IDS.some(r=>machine.input.amounts[r]<recipe.inputs[r]))continue;if(getBufferRemainingCapacity(machine.output)<getBufferTotal({amounts:recipe.outputs,capacity:Infinity}))continue;const input={...machine.input,amounts:{...machine.input.amounts}};for(const r of RESOURCE_IDS)input.amounts[r]-=recipe.inputs[r];const duration=Math.round(recipe.baseDurationMs*speed[machine.level]);return{started:true,machine:{...machine,input,activeCycle:{recipeId:id,remainingMs:duration,durationMs:duration,reservedInputs:{...recipe.inputs}}}}}return{machine,started:false,reason:machine.selectedMode==="auto"?"no-auto-recipe":"insufficient-input"}}
export function advanceProductionCycle(machine:ProcessingMachineState,deltaMs:number):{machine:ProcessingMachineState,completed:boolean}{if(!machine.activeCycle||deltaMs<=0)return{machine,completed:false};const remaining=Math.max(0,machine.activeCycle.remainingMs-deltaMs);if(remaining>0)return{machine:{...machine,activeCycle:{...machine.activeCycle,remainingMs:remaining}},completed:false};const recipe=RECIPES[machine.activeCycle.recipeId];if(getBufferRemainingCapacity(machine.output)<RESOURCE_IDS.reduce((n,r)=>n+recipe.outputs[r],0))return{machine:{...machine,activeCycle:{...machine.activeCycle,remainingMs:0}},completed:false};const output={...machine.output,amounts:{...machine.output.amounts}};for(const r of RESOURCE_IDS)output.amounts[r]+=recipe.outputs[r];return{machine:{...machine,output,activeCycle:null,completedCycles:machine.completedCycles+1},completed:true}}
export function cancelProductionCycle(machine:ProcessingMachineState):ProcessingMachineState{if(!machine.activeCycle)return machine;const input={...machine.input,amounts:{...machine.input.amounts}};for(const r of RESOURCE_IDS)input.amounts[r]+=machine.activeCycle.reservedInputs[r];return{...machine,input,activeCycle:null}}
const MANUAL_INPUTS:Readonly<Record<MachineId,readonly ResourceId[]>>={"grain-mill":["wheat","corn"],bakery:["flour","cornmeal","egg"]};
const MANUAL_OUTPUTS:Readonly<Record<MachineId,readonly ResourceId[]>>={"grain-mill":["flour","cornmeal"],bakery:["bread","cornbread"]};
export function transferManualInputOne(machine:ProcessingMachineState,id:MachineId,cargo:CarriedCargo){for(const resource of MANUAL_INPUTS[id]){if(cargo.amounts[resource]<=0)continue;if(!canAddToBuffer(machine.input,resource))return{machine,cargo,changed:false,reason:"buffer-full" as const};const removed=removeCargoOne(cargo,resource);return{machine:{...machine,input:addBufferResourceOne(machine.input,resource)},cargo:removed.cargo,changed:true,resource};}return{machine,cargo,changed:false,reason:"unavailable" as const};}
export function collectManualOutputOne(machine:ProcessingMachineState,id:MachineId,cargo:CarriedCargo){for(const resource of MANUAL_OUTPUTS[id]){if(machine.output.amounts[resource]<=0)continue;const added=addCargoOne(cargo,resource);if(!added.changed)return{machine,cargo,changed:false,reason:"cargo-full" as const};return{machine:{...machine,output:removeBufferResourceOne(machine.output,resource)},cargo:added.cargo,changed:true,resource};}return{machine,cargo,changed:false,reason:"unavailable" as const};}
export function upgradeMachine(machine:ProcessingMachineState,id:MachineId,walletCoins:number):TransactionResult<ProcessingMachineState>{if(!machine.built||machine.level===0)return{ok:false,state:machine,walletCoins,reason:"not-built"};if(machine.level===3)return{ok:false,state:machine,walletCoins,reason:"maximum"};const costs=id==="grain-mill"?[0,300,700]:[0,500,1000];const cost=costs[machine.level]!;if(walletCoins<cost)return{ok:false,state:machine,walletCoins,reason:"coins"};const level=(machine.level+1) as MachineLevel;const multiplier=[0,1,1.25,1.5][level]!;const bases=id==="grain-mill"?[24,16]:[18,12];return{ok:true,state:{...machine,level,input:{...machine.input,capacity:Math.floor(bases[0]*multiplier)},output:{...machine.output,capacity:Math.floor(bases[1]*multiplier)}},walletCoins:walletCoins-cost,prioritySave:true}}
