import type { ResourceAmounts,ResourceId } from "../config/resourceDefinitions";
export type ProcessingWorkerRole="millOperator"|"baker";
export interface ProcessingWorkerState{hired:boolean;level:0|1|2|3;carriedResource:ResourceId|null;carriedAmount:number;publicStatus:string}
const allowed:Record<ProcessingWorkerRole,readonly ResourceId[]>={millOperator:["wheat","corn","flour","cornmeal"],baker:["flour","cornmeal","egg","bread","cornbread"]};
export const isWorkerResourceAllowed=(role:ProcessingWorkerRole,r:ResourceId|null)=>r===null||allowed[role].includes(r);
export const getProcessingWorkerCapacity=(role:ProcessingWorkerRole,level:number)=>role==="millOperator"?[0,8,12,16][level]??0:[0,6,9,12][level]??0;
export function hireProcessingWorker(role:ProcessingWorkerRole,worker:ProcessingWorkerState,walletCoins:number){const cost=role==="millOperator"?450:700;if(worker.hired)return{ok:false as const,worker,walletCoins,reason:"duplicate"};if(walletCoins<cost)return{ok:false as const,worker,walletCoins,reason:"coins"};return{ok:true as const,worker:{...worker,hired:true,level:1 as const,publicStatus:"待機中"},walletCoins:walletCoins-cost,prioritySave:true as const}}
export function trainProcessingWorker(role:ProcessingWorkerRole,worker:ProcessingWorkerState,walletCoins:number){if(!worker.hired||worker.level===0)return{ok:false as const,worker,walletCoins,reason:"not-hired"};if(worker.level===3)return{ok:false as const,worker,walletCoins,reason:"maximum"};const costs=role==="millOperator"?[0,420,900]:[0,650,1300];const cost=costs[worker.level]!;if(walletCoins<cost)return{ok:false as const,worker,walletCoins,reason:"coins"};return{ok:true as const,worker:{...worker,level:(worker.level+1) as 2|3},walletCoins:walletCoins-cost,prioritySave:true as const}}
export function chooseBlockingIngredient(required:ResourceAmounts,input:ResourceAmounts):ResourceId|null{let best:ResourceId|null=null,bestMissing=0;for(const r of ["flour","cornmeal","egg"] as const){const missing=Math.max(0,required[r]-input[r]);if(missing>bestMissing){best=r;bestMissing=missing}}return best}
export const getWorkerBatchAmount=(available:number,needed:number,capacity:number)=>Math.max(0,Math.min(Math.floor(available),Math.floor(needed),capacity));
