import { describe,expect,it } from "vitest";
import { FARM_LAYOUT,getActiveWheatNodes,rectanglesOverlap } from "../config/farmLayout";
import { getWheatFieldCrateCapacity,getWheatFieldExpansionCost,getWheatFieldNodeCount,purchaseWheatFieldExpansion } from "./wheatFieldExpansion";
import { depositHarvestWorkerBatch,getAutomationWheatTotal,selectNextWheatNodeInCluster,selectWheatFieldCluster,shouldWheatWorkerReturnToCrate,type AutomationState } from "./workers";
import { getWheatWorkerRuntimeParameters } from "./workforce";
const state=(cargo:number,crate:number,capacity=16):AutomationState=>({inventory:{carried:0,barn:2,market:0,fieldCrate:crate,capacity:12,marketCapacity:8,fieldCrateCapacity:capacity},harvestWorker:{hired:true,carried:cargo},transportWorker:{hired:false,carried:0}});
describe("v0.9.5 wheat expansion",()=>{
 it("uses exact node counts, costs, capacities and stable IDs",()=>{expect(([0,1,2] as const).map(getWheatFieldNodeCount)).toEqual([30,42,54]);expect(([0,1,2] as const).map(getWheatFieldCrateCapacity)).toEqual([16,24,32]);expect(([0,1,2] as const).map(getWheatFieldExpansionCost)).toEqual([220,520,null]);for(const level of [0,1,2] as const){const nodes=getActiveWheatNodes(level);expect(nodes).toHaveLength(getWheatFieldNodeCount(level));expect(new Set(nodes.map(n=>n.id)).size).toBe(nodes.length);}});
 it("deducts exact prices and never charges failed/max purchases",()=>{const land={wheatFieldLevel:0 as const,eastCornFieldUnlocked:false,southChickenCoopUnlocked:false};expect(purchaseWheatFieldExpansion(219,land)).toMatchObject({purchased:false,walletCoins:219});const one=purchaseWheatFieldExpansion(1000,land);expect(one).toMatchObject({purchased:true,walletCoins:780,land:{wheatFieldLevel:1}});const two=purchaseWheatFieldExpansion(one.walletCoins,one.land);expect(two).toMatchObject({purchased:true,walletCoins:260,land:{wheatFieldLevel:2}});expect(purchaseWheatFieldExpansion(260,two.land)).toMatchObject({purchased:false,walletCoins:260,reason:"maximum-level"});});
});
describe("wheat batching",()=>{
 it("consumes trained 4/7/10 capacity and faster runtime",()=>{const p=[1,2,3].map(l=>getWheatWorkerRuntimeParameters("wheat-harvester",l as 1|2|3));expect(p.map(x=>x.capacity)).toEqual([4,7,10]);expect(p.map(x=>x.moveSpeed)).toEqual([155,178,202]);expect(p.map(x=>x.operationIntervalMs)).toEqual([850,650,480]);});
 it("keeps field affinity and deterministic nearest selection",()=>{const nodes=[{id:"b",cluster:"west" as const,x:9,y:0,ready:true},{id:"a",cluster:"west" as const,x:3,y:0,ready:true},{id:"c",cluster:"central" as const,x:1,y:0,ready:true}];expect(selectWheatFieldCluster(nodes,0,0,"west")).toBe("west");expect(selectNextWheatNodeInCluster(nodes,"west",0,0)?.id).toBe("a");});
 it("never returns empty and observes capacity/grace",()=>{expect(shouldWheatWorkerReturnToCrate(0,4,0,900)).toBe(false);expect(shouldWheatWorkerReturnToCrate(4,4,2,0)).toBe(true);expect(shouldWheatWorkerReturnToCrate(2,4,0,599)).toBe(false);expect(shouldWheatWorkerReturnToCrate(2,4,0,600)).toBe(true);});
 it("deposits atomically, partially, waits full, and conserves wheat",()=>{for(const [before,outcome,moved] of [[state(7,2),"deposited",7],[state(7,13),"partial",3],[state(7,16),"crate-full",0]] as const){const total=getAutomationWheatTotal(before),r=depositHarvestWorkerBatch(before);expect(r.outcome).toBe(outcome);expect(r.transferred).toBe(moved);expect(getAutomationWheatTotal(r.state)).toBe(total);}});
});
describe("authoritative layout",()=>{it("keeps lodge, fields, pond and nodes separate",()=>{const lodge=FARM_LAYOUT.trainingLodge.bounds;expect(rectanglesOverlap(lodge,FARM_LAYOUT.wheatFields.west.bounds)).toBe(false);expect(rectanglesOverlap(lodge,FARM_LAYOUT.wheatFields.central.bounds)).toBe(false);expect(rectanglesOverlap(lodge,FARM_LAYOUT.pond)).toBe(false);for(const n of FARM_LAYOUT.wheatNodes)expect(n.x>=lodge.x&&n.x<=lodge.x+lodge.width&&n.y>=lodge.y&&n.y<=lodge.y+lodge.height).toBe(false);});});
