import { describe,expect,it } from "vitest";
import { FARM_LAYOUT,getActiveWheatNodes,rectanglesOverlap } from "../config/farmLayout";
import { getWheatFieldCrateCapacity,getWheatFieldExpansionCost,getWheatFieldNodeCount,purchaseWheatFieldExpansion } from "./wheatFieldExpansion";
import { depositHarvestWorkerBatch,getAutomationWheatTotal,selectNearestReadyWheatNode,shouldWheatWorkerReturnToCrate,type AutomationState } from "./workers";
import { getWheatWorkerRuntimeParameters } from "./workforce";
const state=(cargo:number,crate:number,capacity=16):AutomationState=>({inventory:{carried:0,barn:2,market:0,fieldCrate:crate,capacity:12,marketCapacity:8,fieldCrateCapacity:capacity},harvestWorker:{hired:true,carried:cargo},transportWorker:{hired:false,carried:0}});
describe("v0.9.5 wheat expansion",()=>{
 it("uses exact node counts, costs, capacities and stable IDs",()=>{expect(([0,1,2] as const).map(getWheatFieldNodeCount)).toEqual([30,42,54]);expect(([0,1,2] as const).map(getWheatFieldCrateCapacity)).toEqual([16,24,32]);expect(([0,1,2] as const).map(getWheatFieldExpansionCost)).toEqual([220,520,null]);for(const level of [0,1,2] as const){const nodes=getActiveWheatNodes(level);expect(nodes).toHaveLength(getWheatFieldNodeCount(level));expect(new Set(nodes.map(n=>n.id)).size).toBe(nodes.length);}});
 it("deducts exact prices and never charges failed/max purchases",()=>{const land={wheatFieldLevel:0 as const,eastCornFieldUnlocked:false,southChickenCoopUnlocked:false};expect(purchaseWheatFieldExpansion(219,land)).toMatchObject({purchased:false,walletCoins:219});const one=purchaseWheatFieldExpansion(1000,land);expect(one).toMatchObject({purchased:true,walletCoins:780,land:{wheatFieldLevel:1}});const two=purchaseWheatFieldExpansion(one.walletCoins,one.land);expect(two).toMatchObject({purchased:true,walletCoins:260,land:{wheatFieldLevel:2}});expect(purchaseWheatFieldExpansion(260,two.land)).toMatchObject({purchased:false,walletCoins:260,reason:"maximum-level"});});
});
describe("wheat batching",()=>{
 it("consumes trained 4/7/10 capacity and faster runtime",()=>{const p=[1,2,3].map(l=>getWheatWorkerRuntimeParameters("wheat-harvester",l as 1|2|3));expect(p.map(x=>x.capacity)).toEqual([4,7,10]);expect(p.map(x=>x.moveSpeed)).toEqual([155,178,202]);expect(p.map(x=>x.operationIntervalMs)).toEqual([850,650,480]);});
 it("uses deterministic nearest selection in one field",()=>{const nodes=[{id:"b",x:3,y:0,ready:true},{id:"a",x:3,y:0,ready:true},{id:"c",x:1,y:0,ready:true}];expect(selectNearestReadyWheatNode(nodes,0,0)?.id).toBe("c");expect(selectNearestReadyWheatNode(nodes,3,0)?.id).toBe("a");});
 it("never returns empty and observes capacity/grace",()=>{expect(shouldWheatWorkerReturnToCrate(0,4,0,900)).toBe(false);expect(shouldWheatWorkerReturnToCrate(4,4,2,0)).toBe(true);expect(shouldWheatWorkerReturnToCrate(2,4,0,599)).toBe(false);expect(shouldWheatWorkerReturnToCrate(2,4,0,600)).toBe(true);});
 it("deposits atomically, partially, waits full, and conserves wheat",()=>{for(const [before,outcome,moved] of [[state(7,2),"deposited",7],[state(7,13),"partial",3],[state(7,16),"crate-full",0]] as const){const total=getAutomationWheatTotal(before),r=depositHarvestWorkerBatch(before);expect(r.outcome).toBe(outcome);expect(r.transferred).toBe(moved);expect(getAutomationWheatTotal(r.state)).toBe(total);}});
});
describe("authoritative unified layout",()=>{it("is a contiguous 9 by 6 grid separated from facilities",()=>{const field=FARM_LAYOUT.wheatField.bounds,lodge=FARM_LAYOUT.trainingLodge.bounds,entry=FARM_LAYOUT.wheatField.entry,pad=FARM_LAYOUT.wheatExpansion,path=FARM_LAYOUT.farmPath;expect(rectanglesOverlap(lodge,field)).toBe(false);expect(rectanglesOverlap(FARM_LAYOUT.pond,field)).toBe(false);expect(Math.hypot(entry.x-pad.x,entry.y-pad.y)).toBeGreaterThan(pad.radius);expect(pad.x).toBeGreaterThanOrEqual(path.x);expect(pad.x).toBeLessThanOrEqual(path.x+path.width);expect(pad.y).toBeGreaterThanOrEqual(path.y);expect(pad.y).toBeLessThanOrEqual(path.y+path.height);expect(FARM_LAYOUT.wheatNodes.map(n=>n.column)).toEqual(expect.arrayContaining([0,1,2,3,4,5,6,7,8]));expect(new Set(FARM_LAYOUT.wheatNodes.map(n=>n.row))).toEqual(new Set([0,1,2,3,4,5]));for(const n of FARM_LAYOUT.wheatNodes){expect(n.field).toBe("main");expect(n.id).toMatch(/^wheat-main-/);expect(n.x).toBeGreaterThanOrEqual(field.x);expect(n.x).toBeLessThanOrEqual(field.x+field.width);expect(n.y).toBeGreaterThanOrEqual(field.y);expect(n.y).toBeLessThanOrEqual(field.y+field.height);}});});
