import Phaser from "phaser";
import { GameScene } from "./game/scenes/GameScene";
import { UIScene } from "./game/scenes/UIScene";
import { palette } from "./game/art/palette";
import { IndexedDbSaveRepository } from "./game/persistence/IndexedDbSaveRepository";
import { LocalStorageSaveRepository } from "./game/persistence/LocalStorageSaveRepository";
import { ResilientSaveRepository } from "./game/persistence/ResilientSaveRepository";
import { SaveService } from "./game/persistence/SaveService";
import { SaveCoordinator,type SaveRequestReason } from "./game/persistence/SaveCoordinator";
import { normalizePersistedSnapshot } from "./game/logic/normalizePersistedSnapshot";
import { DEFAULT_SETTINGS, type PersistedGameSnapshot, type PersistedSettings, type SaveEnvelope } from "./game/persistence/saveSchema";
import { downloadEnvelope, parseImportedSave } from "./game/persistence/exportImport";
import { GAME_EVENTS } from "./game/state/GameState";
import "./style.css";

const emergencyRepository=new LocalStorageSaveRepository();
const repository = new ResilientSaveRepository(new IndexedDbSaveRepository(),emergencyRepository);
const saves = new SaveService(repository);
let game: Phaser.Game | null = null, currentEnvelope: SaveEnvelope | null = null, coordinator=new SaveCoordinator(saves), lastSaveError:string|null=null;
let settings: PersistedSettings = DEFAULT_SETTINGS;
const root = document.getElementById("game")!;

function screen(title: string, message: string): HTMLDivElement { root.innerHTML=""; const el=document.createElement("div");el.className="menu-screen";el.innerHTML=`<section class="menu-card"><h1>${title}</h1><p>${message}</p><div class="menu-actions"></div></section>`;root.append(el);return el; }
function button(host:HTMLElement,label:string,action:()=>void):void{const b=document.createElement("button");b.textContent=label;b.onclick=action;host.querySelector(".menu-actions")?.append(b);}
async function boot():Promise<void>{const loading=screen("Hurry-Go-Round","農場を準備しています…");try{await repository.initialize();settings={...DEFAULT_SETTINGS,...await repository.loadSettings()};applySettings();const loaded=await saves.load();let notice=loaded.recovered?"セーブデータに問題があったため、バックアップから復元しました":"";currentEnvelope=loaded.envelope;if(!currentEnvelope){const emergency=emergencyRepository.loadEmergency<PersistedGameSnapshot>();if(emergency){try{currentEnvelope=await saves.save(emergency);notice="緊急保存から農場を復元しました";}catch(error){console.warn("Emergency save was not valid",error);}}}coordinator=new SaveCoordinator(saves,currentEnvelope?.payload.saveSequence??0);showTitle(notice);}catch(error){console.error("Save startup failed",error);loading.querySelector("p")!.textContent="セーブデータを読み込めませんでした";button(loading,"新しくはじめる",()=>startGame());button(loading,"セーブデータを読み込む",chooseImport);}}
function showTitle(notice=""):void{if(game){game.destroy(true);game=null;}const summary=currentEnvelope?`最終保存　${new Date(currentEnvelope.updatedAt).toLocaleString("ja-JP")}<br>所持金　${currentEnvelope.payload.economy.walletCoins}<br>評判　レベル${currentEnvelope.payload.contracts.reputation.level}<br>契約　${currentEnvelope.payload.contracts.active?"進行中":"なし"}`:"セーブデータはありません";const el=screen("Hurry-Go-Round",`${notice}<br>${summary}<br><small>v0.9.4 — Collection Runtime</small>`);button(el,currentEnvelope?"つづきから":"はじめる",()=>startGame(currentEnvelope?.payload));button(el,currentEnvelope?"新しくはじめる":"セーブデータを読み込む",currentEnvelope?()=>newGameConfirm(el):chooseImport);if(currentEnvelope)button(el,"セーブデータを読み込む",chooseImport);button(el,"設定",()=>showSettings(el));}
function newGameConfirm(host:HTMLElement):void{const p=host.querySelector("p")!;p.textContent="現在の農場を置き換えます。もう一度確認してください。";const actions=host.querySelector(".menu-actions")!;actions.innerHTML="";button(host,"やめる",()=>showTitle());button(host,"すべて消して最初から",async()=>{await repository.deleteAll();await emergencyRepository.deleteAll();currentEnvelope=null;coordinator=new SaveCoordinator(saves);startGame();});}
function showSettings(host:HTMLElement):void{const p=host.querySelector("p")!;p.textContent=`保存先：${saves.backend}`;const actions=host.querySelector(".menu-actions")!;actions.innerHTML="";for(const [label,key,values] of [["文字サイズ","textScale",[1,1.15,1.3]],["ジョイスティックサイズ","joystickScale",[.85,1,1.15]],["ジョイスティック透明度","joystickOpacity",[.45,.65,.85]]] as const)button(host,`${label} ${settings[key]}`,async()=>{const i=values.indexOf(settings[key] as never);settings={...settings,[key]:values[(i+1)%values.length]};await repository.saveSettings(settings);applySettings();showSettings(host);});button(host,`動きを控えめにする ${settings.reducedMotion?"入":"切"}`,async()=>{settings={...settings,reducedMotion:!settings.reducedMotion};await repository.saveSettings(settings);applySettings();showSettings(host);});button(host,`操作案内を表示する ${settings.contextualHints?"入":"切"}`,async()=>{settings={...settings,contextualHints:!settings.contextualHints};await repository.saveSettings(settings);showSettings(host);});button(host,"保存機能を確認",async()=>{try{const s=scene();if(s)await saves.diagnose(s.getPersistedSnapshot(coordinator.currentSequence));else await repository.probe();p.textContent=`保存機能は正常です　保存先：${saves.backend}`;}catch(error){console.error("Save diagnostic failed",error);p.textContent="保存機能を利用できません　JSON書き出しを使用してください";}});button(host,"戻る",()=>showTitle());}
function applySettings():void{document.documentElement.style.setProperty("--text-scale",String(settings.textScale));document.documentElement.classList.toggle("reduced-motion",settings.reducedMotion);}
function startGame(snapshot?:PersistedGameSnapshot):void{root.innerHTML="";game=new Phaser.Game({type:Phaser.AUTO,parent:"game",backgroundColor:palette.grass,scale:{mode:Phaser.Scale.RESIZE,width:"100%",height:"100%"},render:{antialias:true,roundPixels:true},scene:[GameScene,UIScene],callbacks:{postBoot:g=>{if(snapshot)g.scene.start("game",{snapshot});bindLifecycle(g);}}});}
function scene():GameScene|null{return game?.scene.getScene("game") as GameScene|null;}
async function saveNow(reason:SaveRequestReason="manual"):Promise<void>{const active=scene();if(!active)return;game?.events.emit("save-status",`保存中…　保存先：${saves.backend}`);try{const result=await coordinator.request(reason,n=>active.getPersistedSnapshot(n));if(result)currentEnvelope=result.envelope;lastSaveError=null;game?.events.emit("save-status",`保存しました　${new Date().toLocaleTimeString("ja-JP")}　保存先：${saves.backend}`);}catch(error){lastSaveError=error instanceof Error?error.message:String(error);console.error("Save failed",{reason,error});game?.events.emit("save-status","保存に失敗しました　もう一度試すかJSONを書き出してください");}}
function bindLifecycle(g:Phaser.Game):void{g.events.on(GAME_EVENTS.dirty,(priority?:string)=>{coordinator.markDirty();g.events.emit("save-status","未保存");if(priority)setTimeout(()=>void saveNow("priority"),500);});for(const label of ["今すぐ保存","セーブデータを書き出す","セーブデータを読み込む","タイトルへ戻る","農場を最初からやり直す"]){g.events.on(`management-${label}`,()=>void manage(label));}const interval=window.setInterval(()=>{if(coordinator.isDirty)void saveNow("autosave");},15000);const visibility=()=>{if(document.visibilityState==="hidden"&&coordinator.isDirty)void saveNow("visibility-hidden");};const pagehide=()=>{const active=scene();if(active){try{emergencyRepository.saveEmergency(normalizePersistedSnapshot(active.getPersistedSnapshot(coordinator.currentSequence)));}catch(error){console.error("Emergency save failed",error);}}if(coordinator.isDirty)void saveNow("pagehide");};document.addEventListener("visibilitychange",visibility);window.addEventListener("pagehide",pagehide);g.events.once(Phaser.Core.Events.DESTROY,()=>{clearInterval(interval);document.removeEventListener("visibilitychange",visibility);window.removeEventListener("pagehide",pagehide);});}
async function manage(label:string):Promise<void>{if(label==="今すぐ保存")await saveNow("manual");else if(label==="セーブデータを書き出す"){await saveNow("manual");if(currentEnvelope)downloadEnvelope(currentEnvelope);}else if(label==="セーブデータを読み込む")chooseImport();else if(label==="タイトルへ戻る"){if(coordinator.isDirty)await saveNow("before-title");showTitle();}else if(label==="農場を最初からやり直す"){showTitle("リセットはタイトル画面から二段階で確認できます");}}
function chooseImport():void{const input=document.createElement("input");input.type="file";input.accept="application/json,.json";input.onchange=async()=>{const file=input.files?.[0];if(!file)return;const parsed=await parseImportedSave(await file.text(),file.size);if(!parsed.ok){showTitle(parsed.error);return;}const p=parsed.preview;const el=screen("読み込み内容の確認",`保存日時 ${new Date(p.updatedAt).toLocaleString("ja-JP")}<br>ゲーム版 ${p.gameVersion}<br>所持金 ${p.walletCoins}<br>土地 ${p.eastUnlocked?"東農地 ":""}${p.coopUnlocked?"鶏小屋":""}<br>雇用済みスタッフ ${p.hiredWorkers}<br>評判 レベル${p.reputationLevel}<br>契約 ${p.activeContract?"進行中":"なし"}`);button(el,"やめる",()=>showTitle());button(el,"このデータを読み込む",async()=>{const old=await repository.loadPrimary();if(old)await repository.saveBackup(old);await repository.savePrimary(parsed.envelope);currentEnvelope=parsed.envelope;startGame(parsed.envelope.payload);});};input.click();}
void boot();

declare global{interface Window{__HGR_E2E__?:{getStateSummary:()=>{saveSequence:number;coins:number|null};requestSave:()=>Promise<void>;waitForSave:()=>Promise<void>;getSaveBackend:()=>string;getLastSaveError:()=>string|null;corruptPrimary:()=>Promise<void>}}}
if(import.meta.env.VITE_E2E==="1")window.__HGR_E2E__={getStateSummary:()=>({saveSequence:coordinator.currentSequence,coins:scene()?.getPersistedSnapshot(coordinator.currentSequence).economy.walletCoins??currentEnvelope?.payload.economy.walletCoins??null}),requestSave:async()=>{coordinator.markDirty();await saveNow("manual");},waitForSave:async()=>{await saveNow("manual");},getSaveBackend:()=>saves.backend,getLastSaveError:()=>lastSaveError,corruptPrimary:async()=>{const envelope=await repository.loadPrimary();if(envelope)await repository.savePrimary({...envelope,checksum:"corrupt"});}};
